force-app/main/default/objects/GGPartsSpecAutoNotifications__c/GGPartsSpecAutoNotifications__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>GG Part Spec Auto Notifications</label>
</CustomObject>

force-app/main/default/objects/GGPartsSpecAutoNotifications__c/fields/message__c.field-meta.xml
<CustomField>
    <fullName>message__c</fullName>
    <inlineHelpText>Filtered entries do not contain a message. Message is stored in the non-filtered entry.</inlineHelpText>
    <label>Message</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GGPartsSpecAutoNotifications__c/fields/userIdList__c.field-meta.xml
<CustomField>
    <fullName>userIdList__c</fullName>
    <inlineHelpText>Comma Delimited, Enclosed in Brackets {000000000000000},{000000000000000}</inlineHelpText>
    <label>User Id List</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Specification__c/Specification__c.object-meta.xml
<CustomObject>
    <description>Specification/MTO</description>
    <label>Specification</label>
    <nameField>
        <label>Spec Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>MTO Finisher or TPM</description>
    <inlineHelpText>MTO Finisher or TPM</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Specifications</relationshipLabel>
    <relationshipName>Specifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/arEtcPvd__c.field-meta.xml
<CustomField>
    <fullName>arEtcPvd__c</fullName>
    <label>AR/ETC (PVD)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes, No</fullName>
                <isActive>false</isActive>
                <label>Yes, No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/capabilityAssessmentComplete__c.field-meta.xml
<CustomField>
    <fullName>capabilityAssessmentComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Capability Assessment Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/capable__c.field-meta.xml
<CustomField>
    <fullName>capable__c</fullName>
    <label>Capable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Evaluate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/cncNeeded__c.field-meta.xml
<CustomField>
    <fullName>cncNeeded__c</fullName>
    <label>CNC Needed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/costApproval__c.field-meta.xml
<CustomField>
    <fullName>costApproval__c</fullName>
    <label>Source 1 Cost Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Not Accepted</fullName>
            </value>
            <value>
                <fullName>Reassign CM</fullName>
            </value>
            <value>
                <fullName>Reevaluate Risk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/costAssessmentComplete__c.field-meta.xml
<CustomField>
    <fullName>costAssessmentComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Source 1 Cost Assessment Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/glassComposition__c.field-meta.xml
<CustomField>
    <fullName>glassComposition__c</fullName>
    <label>Glass Composition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlassComposition</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/location__c.field-meta.xml
<CustomField>
    <fullName>location__c</fullName>
    <description>Manufacturing facility/location</description>
    <label>Primary CM Selected Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Manufacturing_Facility</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/manufacturingAssignmentComplete__c.field-meta.xml
<CustomField>
    <fullName>manufacturingAssignmentComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Manufacturing Assignment Complet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/missingInformation__c.field-meta.xml
<CustomField>
    <fullName>missingInformation__c</fullName>
    <label>Missing Information</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/missingInformationAssessmentComplete__c.field-meta.xml
<CustomField>
    <fullName>missingInformationAssessmentComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Missing Information Assessment Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/New_Thickness_or_Size__c.field-meta.xml
<CustomField>
    <fullName>New_Thickness_or_Size__c</fullName>
    <label>New Thickness or Size?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Thickness</fullName>
            </value>
            <value>
                <fullName>New Size</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/potential12MoVolume__c.field-meta.xml
<CustomField>
    <fullName>potential12MoVolume__c</fullName>
    <label>Potential 12 Mo Volume (#Sheets)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/qualityEngineerApproval__c.field-meta.xml
<CustomField>
    <fullName>qualityEngineerApproval__c</fullName>
    <label>Primary QE Approval / AE Response</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reviewed - More Information Required</fullName>
            </value>
            <value>
                <fullName>Approved - Includes Plant Eng Approval</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Reassign CM</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Customer Responded - QA to Confirm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/requestedSampleVolume__c.field-meta.xml
<CustomField>
    <fullName>requestedSampleVolume__c</fullName>
    <label>Requested Sample Volume (#Sheets)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/screenPrint__c.field-meta.xml
<CustomField>
    <fullName>screenPrint__c</fullName>
    <label>Screen Print</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/standard__c.field-meta.xml
<CustomField>
    <fullName>standard__c</fullName>
    <label>Standard</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/standardAssessmentComplete__c.field-meta.xml
<CustomField>
    <fullName>standardAssessmentComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Standard Assessment Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Innovation Assessment</fullName>
            </value>
            <value>
                <fullName>Missing Information Assessment</fullName>
            </value>
            <value>
                <fullName>Capable Assessment</fullName>
            </value>
            <value>
                <fullName>Standard Assessment</fullName>
            </value>
            <value>
                <fullName>Manufacturer Assignment</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>CM Cost Assessment</fullName>
            </value>
            <value>
                <fullName>Supply, Allocation, and Inventory Review</fullName>
            </value>
            <value>
                <fullName>Product Engineering Input</fullName>
            </value>
            <value>
                <fullName>Plant Engineering Input</fullName>
            </value>
            <value>
                <fullName>Supply Chain Input</fullName>
            </value>
            <value>
                <fullName>Pricing Assignment</fullName>
            </value>
            <value>
                <fullName>Business Case Finalization</fullName>
            </value>
            <value>
                <fullName>Finance Review</fullName>
            </value>
            <value>
                <fullName>Commercial/Ops Review</fullName>
            </value>
            <value>
                <fullName>Pricing Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Business Case Assessment</fullName>
                <isActive>false</isActive>
                <label>Business Case Assessment</label>
            </value>
            <value>
                <fullName>Supply, Allocation, &amp; Inventory Assessment</fullName>
                <isActive>false</isActive>
                <label>Supply, Allocation, &amp; Inventory Assessment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/statusChangeDate__c.field-meta.xml
<CustomField>
    <fullName>statusChangeDate__c</fullName>
    <label>Status Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/submitForApproval__c.field-meta.xml
<CustomField>
    <fullName>submitForApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit for Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/TPM__c.field-meta.xml
<CustomField>
    <fullName>TPM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TPM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.isTPM__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Specifications (TPM)</relationshipLabel>
    <relationshipName>SpecificationsTPM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/Urgency_of_Case__c.field-meta.xml
<CustomField>
    <fullName>Urgency_of_Case__c</fullName>
    <label>Urgency of Case</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medium</fullName>
                <default>true</default>
                <label>Medium</label>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/Why_Ask_for_MOQ_Exception__c.field-meta.xml
<CustomField>
    <fullName>Why_Ask_for_MOQ_Exception__c</fullName>
    <inlineHelpText>Why does the Minimum Order Quantity Not Work?</inlineHelpText>
    <label>Why Ask for MOQ Exception</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Specification__c/recordTypes/Concore.recordType-meta.xml
<RecordType>
    <fullName>Concore</fullName>
    <active>true</active>
    <description>Gorilla Glass Concore MTO specification</description>
    <label>Concore</label>
</RecordType>

force-app/main/default/objects/Specification__c/recordTypes/Parts.recordType-meta.xml
<RecordType>
    <fullName>Parts</fullName>
    <active>true</active>
    <description>Gorilla Glass Parts specification</description>
    <label>Parts</label>
</RecordType>

force-app/main/default/globalValueSets/GlassComposition.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1805</fullName>
    </customValue>
    <customValue>
        <fullName>1807</fullName>
    </customValue>
    <customValue>
        <fullName>1811</fullName>
    </customValue>
    <customValue>
        <fullName>1815</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2317</fullName>
    </customValue>
    <customValue>
        <fullName>2318</fullName>
    </customValue>
    <customValue>
        <fullName>2319</fullName>
    </customValue>
    <customValue>
        <fullName>2320 (GG3)</fullName>
    </customValue>
    <customValue>
        <fullName>2521 (GG3+)</fullName>
    </customValue>
    <customValue>
        <fullName>3318</fullName>
    </customValue>
    <customValue>
        <fullName>4318</fullName>
    </customValue>
    <customValue>
        <fullName>5318 (GG4)</fullName>
    </customValue>
    <customValue>
        <fullName>7321 (GG5)</fullName>
    </customValue>
    <customValue>
        <fullName>7418</fullName>
    </customValue>
    <customValue>
        <fullName>7431 (GG6)</fullName>
    </customValue>
    <customValue>
        <fullName>7541 (Victus)</fullName>
    </customValue>
    <customValue>
        <fullName>7518</fullName>
    </customValue>
    <customValue>
        <fullName>9218</fullName>
    </customValue>
    <customValue>
        <fullName>9318</fullName>
    </customValue>
    <customValue>
        <fullName>9319</fullName>
    </customValue>
    <customValue>
        <fullName>9724</fullName>
    </customValue>
    <customValue>
        <fullName>9726</fullName>
    </customValue>
    <customValue>
        <fullName>Maxwell GC</fullName>
    </customValue>
    <customValue>
        <fullName>MGC</fullName>
    </customValue>
    <customValue>
        <fullName>MM-B</fullName>
    </customValue>
    <customValue>
        <fullName>MX-B</fullName>
    </customValue>
    <customValue>
        <fullName>PHY2</fullName>
    </customValue>
    <customValue>
        <fullName>PHY2.1</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Glass Composition</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Manufacturing_Facility.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Biel</fullName>
    </customValue>
    <customValue>
        <fullName>BOE</fullName>
    </customValue>
    <customValue>
        <fullName>BYD-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>CGK</fullName>
    </customValue>
    <customValue>
        <fullName>CPM</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal</fullName>
    </customValue>
    <customValue>
        <fullName>DSBJ</fullName>
    </customValue>
    <customValue>
        <fullName>Fuzhou</fullName>
    </customValue>
    <customValue>
        <fullName>GIS</fullName>
    </customValue>
    <customValue>
        <fullName>GO</fullName>
    </customValue>
    <customValue>
        <fullName>GTOC</fullName>
    </customValue>
    <customValue>
        <fullName>HDC</fullName>
    </customValue>
    <customValue>
        <fullName>HH-LowR</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong Warehouse</fullName>
    </customValue>
    <customValue>
        <fullName>Hony</fullName>
    </customValue>
    <customValue>
        <fullName>HTF</fullName>
    </customValue>
    <customValue>
        <fullName>Huaqing</fullName>
    </customValue>
    <customValue>
        <fullName>J3D</fullName>
    </customValue>
    <customValue>
        <fullName>Jiangmen</fullName>
    </customValue>
    <customValue>
        <fullName>JNTC-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>Kaymao</fullName>
    </customValue>
    <customValue>
        <fullName>KOTL-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>LCE-LR</fullName>
    </customValue>
    <customValue>
        <fullName>LENS-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>LOT</fullName>
    </customValue>
    <customValue>
        <fullName>MFD-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>NGS</fullName>
    </customValue>
    <customValue>
        <fullName>NVD</fullName>
    </customValue>
    <customValue>
        <fullName>Opton</fullName>
    </customValue>
    <customValue>
        <fullName>RKL</fullName>
    </customValue>
    <description>Manufacturing facility selected in the spec</description>
    <masterLabel>Manufacturing Facility</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/SpecificationReminderBatchTest.cls
@isTest
private class SpecificationReminderBatchTest {
    static TestUtilities tUtils = new TestUtilities();
    private static string acctRT;
    private static string oppRT;
    private static string specRT;
    private static string specRT2;
    private static string specRT3;
    private static string profileId;
    
    static {
        acctRT = tUtils.getRecordTypeId('Account', 'GG Account');
        oppRT = tUtils.getRecordTypeId('Opportunity', 'GG Program');
        specRT = tUtils.getRecordTypeId('Specification__c', 'Parts');
        specRT2 = tUtils.getRecordTypeId('Specification__c', 'Raw Glass');
        specRT3 = tUtils.getRecordTypeId('Specification__c', 'Concore');
        profileId = tUtils.getProfileId('GG Account Manager');
    }
       
static testMethod void testSpecificationReminderBatch() {

        // add custom settings
        List<GGPartsSpecAutoNotifications__c> csParts = new List<GGPartsSpecAutoNotifications__c>();
        csParts.add(new GGPartsSpecAutoNotifications__c(Name = 'N~MIA', message__c = '*', userIdList__c = '{005o0000001BKMPAA4}'));
        csParts.add(new GGPartsSpecAutoNotifications__c(Name = 'SA~MA', message__c = '*', userIdList__c = '{005o0000001BKMPAA4}'));        
        csParts.add(new GGPartsSpecAutoNotifications__c(Name = 'MA~RA~Biel', message__c = '*', userIdList__c = '{005o0000001BKMPAA4}'));        
        csParts.add(new GGPartsSpecAutoNotifications__c(Name = 'RA~CA', message__c = '*', userIdList__c = '{005o0000001BKMPAA4}'));        
        csParts.add(new GGPartsSpecAutoNotifications__c(Name = 'CA~PA', message__c = '*', userIdList__c = '{005o0000001BKMPAA4}'));        
        insert csParts;
        
        List<GGMTOSpecAutoNotifications__c> csRaw = new List<GGMTOSpecAutoNotifications__c>();
        csRaw.add(new GGMTOSpecAutoNotifications__c(Name = 'P1~N~SAIR', message__c = '*', userIdList__c = '{005o0000001BKMPAA4}'));
        csRaw.add(new GGMTOSpecAutoNotifications__c(Name = 'P1~SIAR~PREI', message__c = '*', userIdList__c = '{005o0000001BKMPAA4}'));        
        csRaw.add(new GGMTOSpecAutoNotifications__c(Name = 'P1~PREI~PLEI', message__c = '*', userIdList__c = '{005o0000001BKMPAA4}'));        
        csRaw.add(new GGMTOSpecAutoNotifications__c(Name = 'P1~PLEI~SCI', message__c = '*', userIdList__c = '{005o0000001BKMPAA4}')); 
        csRaw.add(new GGMTOSpecAutoNotifications__c(Name = 'P1~SCI~PA', message__c = '*', userIdList__c = '{005o0000001BKMPAA4}')); 
        csRaw.add(new GGMTOSpecAutoNotifications__c(Name = 'P1~PA~BCF', message__c = '*', userIdList__c = '{005o0000001BKMPAA4}')); 
        csRaw.add(new GGMTOSpecAutoNotifications__c(Name = 'P1~BCF~COR', message__c = '*', userIdList__c = '{005o0000001BKMPAA4}'));              
        insert csRaw;
       
        Account a = tUtils.addTestAccount(acctRT);
        a.accountType__c = 'TPM';
        update a;
        
        Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
        
        Specification__c testSpec = tUtils.createTestSpec(a.id, o.id, specRT);
        testSpec.tpm__c = a.id;
        testSpec.submitForApproval__c = true;
        testSpec.Status__c = 'New';
        testSpec.cncNeeded__c = 'No'; 
        testSpec.arEtcPvd__c = 'No';
        testSpec.screenPrint__c = 'No';
        insert testSpec;
        
        string testId = testSpec.id;
        Specification__c testSpec2 = [SELECT Id, missingInformation__c, missingInformationAssessmentComplete__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.missingInformation__c = 'No';
        testSpec2.missingInformationAssessmentComplete__c = True;
        update testSpec2;
        testSpec2.statusChangeDate__c = Date.newInstance(1988, 2, 17);
        update testSpec2;

        Specification__c testSpec3 = [SELECT Id, capable__c, capabilityAssessmentComplete__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.capable__c = 'Yes';
        testSpec3.capabilityAssessmentComplete__c = True;
        update testSpec3;
        testSpec3.statusChangeDate__c = Date.newInstance(1988, 2, 17);
        update testSpec3;

        Specification__c testSpec4 = [SELECT Id, standard__c, standardAssessmentComplete__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.standard__c = 'Yes';
        testSpec4.standardAssessmentComplete__c = True;
        update testSpec4;
        testSpec4.statusChangeDate__c = Date.newInstance(1988, 2, 17);
        update testSpec4;
 
        Specification__c testSpec5 = [SELECT Id, location__c, manufacturingAssignmentComplete__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec5.location__c = 'Biel';
        testSpec5.manufacturingAssignmentComplete__c = True;
        update testSpec5;
        testSpec5.statusChangeDate__c = Date.newInstance(1988, 2, 17);
        update testSpec5;
 
        Specification__c testSpec6 = [SELECT Id, qualityEngineerApproval__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec6.qualityEngineerApproval__c = 'Approved - Includes Plant Eng Approval';
        update testSpec6;
        testSpec6.statusChangeDate__c = Date.newInstance(1988, 2, 17);
        update testSpec6;
 
        Specification__c testSpec7 = [SELECT Id, costApproval__c, costAssessmentComplete__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec7.costApproval__c = 'Accepted';
        testSpec7.costAssessmentComplete__c = True;
        update testSpec7;
        testSpec7.statusChangeDate__c = Date.newInstance(1988, 2, 17);
        update testSpec7;

        // **** RAW ****

        Specification__c testSpecRaw = tUtils.createTestSpec(a.id, o.id, specRT2);
        testSpecRaw.account__c = a.id;
        testSpecRaw.submitForApproval__c = true;
        testSpecRaw.Status__c = 'New';
        testSpecRaw.Urgency_of_Case__c = 'Low'; 
        testSpecRaw.Why_Ask_for_MOQ_Exception__c = 'No';
        testSpecRaw.New_Thickness_or_Size__c = 'Both';
        testSpecRaw.requestedSampleVolume__c = 100;
        testSpecRaw.potential12MoVolume__c = 1000;
        testSpecRaw.glassComposition__c = '2320 (GG3)';// 11-16-20 jd (change to '2320 (GG3)'')
        insert testSpecRaw;
        
        string testIdRaw = testSpecRaw.id;
        Specification__c testSpec2Raw = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c FROM Specification__c WHERE id =: testIdRaw limit 1];
        testSpec2Raw.supplyAllocationInventory__c = 'Approved';
        testSpec2Raw.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2Raw;
        testSpec2Raw.statusChangeDate__c = Date.newInstance(1988, 2, 17);
        update testSpec2Raw;

        Specification__c testSpec3Raw = [SELECT Id, productEngineeringInputReceived__c FROM Specification__c WHERE id =: testIdRaw limit 1];
        testSpec3Raw.productEngineeringInputReceived__c = True;
        update testSpec3Raw;
        testSpec3Raw.statusChangeDate__c = Date.newInstance(1988, 2, 17);
        update testSpec3Raw;

        Specification__c testSpec4Raw = [SELECT Id, engineeringInputReceived__c FROM Specification__c WHERE id =: testIdRaw limit 1];     
        testSpec4Raw.engineeringInputReceived__c = True;
        update testSpec4Raw;
        testSpec4Raw.statusChangeDate__c = Date.newInstance(1988, 2, 17);
        update testSpec4Raw;
 
        Specification__c testSpec5Raw = [SELECT Id, supplyChainInputReceived__c FROM Specification__c WHERE id =: testIdRaw limit 1];               
        testSpec5Raw.supplyChainInputReceived__c = True;
        update testSpec5Raw;
        testSpec5Raw.statusChangeDate__c = Date.newInstance(1988, 2, 17);
        update testSpec5Raw;
 
        Specification__c testSpec6Raw = [SELECT Id, moq__c, moqUom__c, unitCostSqFt__c, shippingCostSqFt__c, pricingAssignmentComplete__c FROM Specification__c WHERE id =: testIdRaw limit 1];       
        testSpec6Raw.moq__c = 1;
        testSpec6Raw.moqUom__c = 'Each';
        testSpec6Raw.unitCostSqFt__c = 1;
        testSpec6Raw.shippingCostSqFt__c = 1;
        testSpec6Raw.pricingAssignmentComplete__c = True;
        update testSpec6Raw;
        testSpec6Raw.statusChangeDate__c = Date.newInstance(1988, 2, 17);
        update testSpec6Raw;
 
        Specification__c testSpec7Raw = [SELECT Id, finalBusinessCaseComplete__c FROM Specification__c WHERE id =: testIdRaw limit 1];       
        testSpec7Raw.finalBusinessCaseComplete__c = True;
        update testSpec7Raw; 
        testSpec7Raw.statusChangeDate__c = Date.newInstance(1988, 2, 17);
        update testSpec7Raw;
        
        Specification__c testSpec8Raw = [SELECT Id, mtoReview__c, operationalApproval__c, commercialApproval__c FROM Specification__c WHERE id =: testIdRaw limit 1];
        testSpec8Raw.mtoReview__c = 'Approved';
        testSpec8Raw.operationalApproval__c = True;
        testSpec8Raw.commercialApproval__c = False; // don't create the product records. just testing chatter helper
        update testSpec8Raw;
        testSpec8Raw.statusChangeDate__c = Date.newInstance(1988, 2, 17);
        update testSpec8Raw;

        Test.startTest();
            Database.executeBatch(new SpecificationReminderBatch(), 200);
        Test.stopTest();  
    
}

static testMethod void testSpecificationReminderBatchScheduler() {
    Test.startTest();
        SpecificationReminderScheduler scheduledJob = new SpecificationReminderScheduler();     
        String sch = '0 0 2 * * ?';
        String jobId = System.schedule('Test Schedule', sch, scheduledJob);
    
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id =: jobId];
        System.assertEquals('0 0 2 * * ?', ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
    Test.stopTest();
}
}