force-app/main/default/objects/GG_Currency_Display_Settings__c/GG_Currency_Display_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>GG Currency Display Settings</label>
</CustomObject>

force-app/main/default/objects/GG_Currency_Display_Settings__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GG_Currency_Display_Settings__c/fields/currencyDisplay__c.field-meta.xml
<CustomField>
    <fullName>currencyDisplay__c</fullName>
    <label>Currency Display</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GG_Currency_Display_Settings__c/fields/exchangeValue__c.field-meta.xml
<CustomField>
    <fullName>exchangeValue__c</fullName>
    <description>Amount of Foreign Currency to the Dollar</description>
    <inlineHelpText>Amount of Foreign Currency to the Dollar</inlineHelpText>
    <label>Exchange Value</label>
    <precision>12</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GG_Currency_Display_Settings__c/fields/vat__c.field-meta.xml
<CustomField>
    <fullName>vat__c</fullName>
    <inlineHelpText>In Percent</inlineHelpText>
    <label>VAT</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/GG_Quote_Expiration_Settings__c/GG_Quote_Expiration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings used in pdf quote generation to set expiration date for raw/concore/parts quotes.</description>
    <label>GG Quote Expiration Settings</label>
</CustomObject>

force-app/main/default/objects/GG_Quote_Expiration_Settings__c/fields/daysToExpiration__c.field-meta.xml
<CustomField>
    <fullName>daysToExpiration__c</fullName>
    <description>Quote: Number of days from the creation to the expiration date.</description>
    <label>Days To Expiration</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GG_Quote_Language__c/GG_Quote_Language__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>GG Quote Language</label>
</CustomObject>

force-app/main/default/objects/GG_Quote_Language__c/fields/Output_Language__c.field-meta.xml
<CustomField>
    <fullName>Output_Language__c</fullName>
    <label>Output Language</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GG_Quote_Language__c/fields/Output_Language_Code__c.field-meta.xml
<CustomField>
    <fullName>Output_Language_Code__c</fullName>
    <label>Output Language Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GG_Shipping_Term__c/GG_Shipping_Term__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>GG Shipping Term</label>
</CustomObject>

force-app/main/default/objects/GG_Shipping_Term__c/fields/shippingTerm__c.field-meta.xml
<CustomField>
    <fullName>shippingTerm__c</fullName>
    <label>Shipping Term</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GG_Shipping_Term__c/fields/shippingTermCode__c.field-meta.xml
<CustomField>
    <fullName>shippingTermCode__c</fullName>
    <label>Shipping Term Code</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteBoilerplate__c/QuoteBoilerplate__c.object-meta.xml
<CustomObject>
    <description>Contains text blocks used in quote PDF&apos;s. These are organized by Corning Selling Entity and Language.</description>
    <label>Quote Boilerplate</label>
    <nameField>
        <label>Quote Boilerplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Boilerplate</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteBoilerplate__c/fields/concoreRemarks__c.field-meta.xml
<CustomField>
    <fullName>concoreRemarks__c</fullName>
    <label>Remarks (Concore)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/QuoteBoilerplate__c/fields/corningSellingEntity__c.field-meta.xml
<CustomField>
    <fullName>corningSellingEntity__c</fullName>
    <description>Corning Ceramic Materials (Shanghai) Co. vs Corning Specialty Materials Incorporated</description>
    <inlineHelpText>Corning Ceramic Materials (Shanghai) Co. vs Corning Specialty Materials Incorporated</inlineHelpText>
    <label>Corning Selling Entity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCMS</fullName>
            </value>
            <value>
                <fullName>CSMI</fullName>
            </value>
            <value>
                <fullName>CIKK</fullName>
            </value>
            <value>
                <fullName>CVCL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteBoilerplate__c/fields/corningSellingEntityLabel__c.field-meta.xml
<CustomField>
    <fullName>corningSellingEntityLabel__c</fullName>
    <label>Corning Selling Entity Label</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteBoilerplate__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteBoilerplate__c/fields/partsRemarks__c.field-meta.xml
<CustomField>
    <fullName>partsRemarks__c</fullName>
    <label>Remarks (Parts)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/QuoteBoilerplate__c/fields/preparedBy__c.field-meta.xml
<CustomField>
    <fullName>preparedBy__c</fullName>
    <label>Prepared By</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteBoilerplate__c/fields/preparedFor__c.field-meta.xml
<CustomField>
    <fullName>preparedFor__c</fullName>
    <label>Prepared For</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteBoilerplate__c/fields/quoteLanguage__c.field-meta.xml
<CustomField>
    <fullName>quoteLanguage__c</fullName>
    <label>Quote Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>quoteLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteBoilerplate__c/fields/rawRemarks__c.field-meta.xml
<CustomField>
    <fullName>rawRemarks__c</fullName>
    <label>Remarks (Raw Glass)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/QuoteBoilerplate__c/fields/returnAddress__c.field-meta.xml
<CustomField>
    <fullName>returnAddress__c</fullName>
    <label>Return Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QuoteBoilerplate__c/fields/termsAndConditions__c.field-meta.xml
<CustomField>
    <fullName>termsAndConditions__c</fullName>
    <label>Terms and Conditions</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/QuoteBoilerplate__c/fields/thankYou__c.field-meta.xml
<CustomField>
    <fullName>thankYou__c</fullName>
    <label>Thank You</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/quoteLanguage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>en_US</fullName>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>zh_CN</fullName>
        <label>Chinese and English</label>
    </customValue>
    <customValue>
        <fullName>ja</fullName>
        <label>Japanese and English</label>
    </customValue>
    <customValue>
        <fullName>ko</fullName>
        <isActive>false</isActive>
        <label>Korean and English</label>
    </customValue>
    <customValue>
        <fullName>zh_HK</fullName>
        <isActive>false</isActive>
        <label>Chinese</label>
    </customValue>
    <masterLabel>Quote Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuotePDFControllerTest.cls
///*** Added for Gorilla Glass Implementation ***///
///*** Salesforce Cloud Services - 3/28/2017 ***///
///*** Controller test class used in the Quote PDF Generation Component. ***///
@isTest(SeeAllData=true)
private class QuotePDFControllerTest {
    static TestUtilities tUtils = new TestUtilities();
    private static string acctRT;
    private static string contactRT;
    private static string oppRT;
    private static string oppRT2;
    private static string quoteRT;
    private static string quoteRT2;
    private static string profileId;
    private static string roleId;
    
    static {
        acctRT = tUtils.getRecordTypeId('Account', 'GG Account');
        contactRT = tUtils.getRecordTypeId('Contact', 'GG Contact');
        oppRT = tUtils.getRecordTypeId('Opportunity', 'GG Program');
        oppRT2 = tUtils.getRecordTypeId('Opportunity', 'GG Parts Sample Request');
        quoteRT = tUtils.getRecordTypeId('Quote', Label.GGQuoteParts);
        quoteRT2 = tUtils.getRecordTypeId('Quote', Label.GGQuoteSample);
        profileId = tUtils.getProfileId('GG Account Manager');
        roleId = tUtils.getRoleId('GG Sales Mgr Americas/EMEA');
    }
    
    static testMethod void constructorTest() {
        Test.startTest();
        User ta = (tUtils.addTestUsers(profileId,1))[0];
        Account a = tUtils.addTestAccount(acctRT);
        Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
        Opportunity o2 = tUtils.createTestOppt(a.Id,oppRT2);
        o2.massProductionOpportunity__c = o.id;
        insert o2;
        o2.StageName = Label.GGSamplePricingAssignment;
        o2.pricingAssignmentComplete__c = true;
        update o2; 
        Quote q = tUtils.addTestQuote(a.Id,o2.Id,quoteRt);
        
        PageReference pageRef = Page.QuotePDFGenerator;
        Test.setCurrentPage(pageRef);
        
        ApexPages.currentPage().getParameters().put('id', q.Id);
        ApexPages.currentPage().getParameters().put('lang', 'en_US');
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(q);
        QuotePDFController con = new QuotePDFController(stdController);
        Test.stopTest();
    }
    
    //Correct
    static testMethod void getPDFInfoWrapperTest() {
        
        Quote q = setupQuote();
        q.incotermAdder__c = 1.00;
        update q;
        
        test.startTest();
        QuotePDFController.pdfWrapper theWrapper = QuotePDFController.getPDFInfo(q.id); 
        //system.assertEquals(true,theWrapper.canCreatePDF); 
        test.stopTest();
    }
    
    static testMethod void getPDFInfoWrapperTest2() {
        
        Quote q = setupQuote2();
        q.incotermAdder__c = 1.00;
        update q;
        
        test.startTest();
        QuotePDFController.pdfWrapper theWrapper = QuotePDFController.getPDFInfo(q.id); 
        //system.assertEquals(true,theWrapper.canCreatePDF); 
        test.stopTest();
    }
    /** AN 1/17/18 - revisit these test scenarios
//Missing Boilerplate
static testMethod void getPDFInfoWrapperError5Test() {
User ta = (tUtils.addTestUsers(profileId,1))[0];
Account a = tUtils.addTestAccount(acctRT);
Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
Quote q = tUtils.addTestQuote(a.Id,o.Id,quoteRt); 

GG_Quote_Language__c cs2 = new GG_Quote_Language__c();
cs2.Name = 'Chinese and English';
cs2.Output_Language__c = 'Chinese and English';
cs2.Output_Language_Code__c = 'zh_CN';
insert cs2;

QuotePDFController.pdfWrapper theWrapper = QuotePDFController.getPDFInfo(q.id); 
system.assertEquals(false,theWrapper.canCreatePDF); 
system.assertEquals(Label.GGQuoteBoilerplateError,theWrapper.pdfCreationError);
}

//Missing Language
static testMethod void getPDFInfoWrapperError1Test() {
User ta = (tUtils.addTestUsers(profileId,1))[0];
Account a = tUtils.addTestAccount(acctRT);
Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
Quote q = tUtils.createTestQuote(a.Id,o.Id,quoteRt);
q.language__c = null;
insert q;

GG_Quote_Language__c cs2 = new GG_Quote_Language__c();
cs2.Name = 'Chinese and English';
cs2.Output_Language__c = 'Chinese and English';
cs2.Output_Language_Code__c = 'zh_CN';
insert cs2;

test.startTest();
QuotePDFController.pdfWrapper theWrapper = QuotePDFController.getPDFInfo(q.id); 
system.assertEquals(false,theWrapper.canCreatePDF);
system.assertEquals(Label.GGLanguageQuoteError,theWrapper.pdfCreationError);
test.stopTest();
}

//Wrong Quote Status
static testMethod void getPDFInfoWrapperError2Test() {
User ta = (tUtils.addTestUsers(profileId,1))[0];
Account a = tUtils.addTestAccount(acctRT);
Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
Quote q = tUtils.createTestQuote(a.Id,o.Id,quoteRt);
q.status = Label.GGQuotePricingReview;
insert q;

GG_Quote_Language__c cs2 = new GG_Quote_Language__c();
cs2.Name = 'Chinese and English';
cs2.Output_Language__c = 'Chinese and English';
cs2.Output_Language_Code__c = 'zh_CN';
insert cs2;

test.startTest();
QuotePDFController.pdfWrapper theWrapper = QuotePDFController.getPDFInfo(q.id); 
system.assertEquals(false,theWrapper.canCreatePDF);
system.assertEquals(Label.GGPricingReviewQuoteError,theWrapper.pdfCreationError);
test.stopTest();
}
**/
    //Inactive Product
    static testMethod void getPDFInfoWrapperError3Test() {
        
        Quote q = setupQuote(); 
        test.startTest();
        q.incotermAdder__c = 1.00;
        update q;
        Id oppId = q.OpportunityId;
        list<Product2> prods = [SELECT Id, isActive FROM Product2 WHERE Opportunity__c = :oppId];
        for(Product2 prod : prods){
            prod.isActive = false;
        }
        update prods;
        
        
        QuotePDFController.pdfWrapper theWrapper = QuotePDFController.getPDFInfo(q.id); 
        //system.assertEquals(false,theWrapper.canCreatePDF);
        //system.assertEquals(Label.GGInactiveProductQuoteError,theWrapper.pdfCreationError);
        test.stopTest();
    }
    
    static testMethod void generateQuotePDFTest() {
        
        Quote q = setupQuote();
        //QuoteLineItem qli = [SELECT Id, QuoteId FROM QuoteLineItem WHERE QuoteId = :q.Id LIMIT 1];
        //System.debug('QLI IN Method$$$$$>>' + qli);
        test.startTest();
        PageReference pageRef = Page.QuotePDFGenerator;
        Test.setCurrentPage(pageRef);
        
        ApexPages.currentPage().getParameters().put('id', q.Id);
        ApexPages.currentPage().getParameters().put('lang', 'zh_CN');
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(q);
        QuotePDFController con = new QuotePDFController(stdController);
        con.generateQuotePDF();
        
        //system.assertEquals('Corning Restricted - ',con.securityString);
        //system.assertEquals('MassParts', con.lineItemType);
        test.stopTest();
    }
    
    static testMethod void generateQuotePDFTest2() {
        
        Quote q = setupQuote2();
        //QuoteLineItem qli = [SELECT Id, QuoteId FROM QuoteLineItem WHERE QuoteId = :q.Id LIMIT 1];
        //System.debug('QLI IN Method$$$$$>>' + qli);
        test.startTest();
        PageReference pageRef = Page.QuotePDFGenerator;
        Test.setCurrentPage(pageRef);
        
        ApexPages.currentPage().getParameters().put('id', q.Id);
        ApexPages.currentPage().getParameters().put('lang', 'zh_CN');
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(q);
        QuotePDFController con = new QuotePDFController(stdController);
        con.generateQuotePDF();
        
        //system.assertEquals('Corning Restricted - ',con.securityString);
        //system.assertEquals('MassParts', con.lineItemType);
        test.stopTest();
    }
    
    static testMethod void savePDFtoQuoteTest (){
        Quote q = setupQuote();
        test.startTest();
        QuotePDFController.savePDFtoQuote(q.id,'zh_CN');
        system.assertNotEquals(null,[SELECT Id, Document FROM QuoteDocument WHERE QuoteId = :q.id]);
        QuotePDFController.pdfWrapper pdfw = new QuotePDFController.pdfWrapper(false, null);
        test.stopTest();    
    }
    
    //Utility for Quote PDF testing
    static Quote setUpQuote() {
       /* User ta, cc;
        Quote q;
        //tUtils.SetTriggersOnForTesting();
        User thisUser = [Select Id From User Where Id =: UserInfo.getUserId() ];
        system.runAs ( thisUser ) {
            ta = (tUtils.addTestUsers(profileId,1,roleId))[0];
            cc = (tUtils.addTestUsers(profileId, 1))[0];
        }
        
        system.runAs ( ta ) {  
            /*Account a = tUtils.addTestAccount(acctRT);
Contact c = tUtils.addTestContact(a.id,contactRT);
Account tpm = tUtils.createTestAccount(acctRT);
tpm.containsPricing__c = true;
insert tpm;
Account finisher = tUtils.createTestAccount(acctRT);
finisher.containsPricing__c = true;
insert finisher;

Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
OpportunityTeamMember otm = tUtils.addTestOppTeamMember(o.id, ta.id, 'Account Manager');
tUtils.AddTestGGProductAndPriceBookEntry(o, tpm, finisher); */
           /* Account a = tUtils.addTestAccount(acctRT);
            Account tpm = tUtils.createTestAccount(acctRT);
            tpm.containsPricing__c = true;
            insert tpm;
            Account finisher = tUtils.createTestAccount(acctRT);
            finisher.containsPricing__c = true;
            insert finisher;
            Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
            Opportunity o2 = tUtils.createTestOppt(a.Id,oppRT2);
            o2.massProductionOpportunity__c = o.id;
            insert o2;
            o2.StageName = Label.GGSamplePricingAssignment;
            o2.pricingAssignmentComplete__c = true;
            update o2; 
            List<PricebookEntry> pbList = tUtils.AddTestGGProductAndPriceBookEntry2(o, tpm, finisher);
            q = tUtils.addTestQuote(a.Id,o2.Id,quoteRt);
            List<Id> pIds = new List<Id>();
            for (Price__c p : [SELECT Id FROM Price__c]){ 
                pIds.add(p.Id);
            } 
            //Test.startTest();
            //OptyQuoteLIUtility util1 = new OptyQuoteLIUtility(q.Id, pIds);
               // util1.addLineItems();
             QuoteLineItem qli = new QuoteLineItem();
        	qli.QuoteId = q.Id;
        	qli.Quantity = 12;
        	qli.PricebookEntryId = pbList.get(0).Id;
       		 qli.UnitPrice = 10;
            insert qli;
            list<QuoteLineItem> qliList = new list<QuoteLineItem>();
            //q = tUtils.createTestQuote(a.Id,o.Id,quoteRt);
            q.CorningContact__c = cc.id;
            //q.ContactId = cc.id;
            //insert q;*/
            
            //OptyQuoteLIUtility util = new OptyQuoteLIUtility(q.Id, pIds);
            //util.addLineItems();
            //Test.stopTest();
        User ta;
        Quote q;
        User thisUser = [Select Id From User Where Id =: UserInfo.getUserId() ];
        system.runAs ( thisUser ) {
            ta = (tUtils.addTestUsers(profileId,1,roleId))[0];
        }
        
        system.runAs ( ta ) {
            /*Account a = tUtils.addTestAccount(acctRT);
            Account tpm = tUtils.createTestAccount(acctRT);
            tpm.containsPricing__c = true;
            insert tpm;
            Account finisher = tUtils.createTestAccount(acctRT);
            finisher.containsPricing__c = true;
            insert finisher;
            
            Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
            OpportunityTeamMember otm = tUtils.addTestOppTeamMember(o.id, ta.id, 'Account Manager');
            tUtils.AddTestGGProductAndPriceBookEntry(o, tpm, finisher);*/
            Account a = tUtils.addTestAccount(acctRT);
            Account tpm = tUtils.createTestAccount(acctRT);
            tpm.containsPricing__c = true;
            //insert tpm;
            Account finisher = tUtils.createTestAccount(acctRT);
            finisher.containsPricing__c = true;
            //insert finisher;
            
            Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
            Opportunity o2 = tUtils.createTestOppt(a.Id,oppRT2);
            o2.massProductionOpportunity__c = o.id;
            insert o2;
            o2.StageName = Label.GGSamplePricingAssignment;
            o2.pricingAssignmentComplete__c = true;
            update o2;    
            System.debug('O2==%%%%>' + o2);
            List<PricebookEntry> pbList = tUtils.AddTestGGProductAndPriceBookEntry2(o, tpm, finisher);
            Contact c = tUtils.addTestContact(a.id,contactRT);
            q = tUtils.createTestQuote2(a.id, o2.id,quoteRT);
            q.corningContact__c = ta.Id;
            q.ContactId = c.Id;
            q.currency__c = 'Yuan';
            q.corningSellingEntity__c = 'CCMS';
            insert q;
            
            System.Debug('quoterecordId======>' + q.Id);
            
            //List<Id> pIds = new List<Id>();
            //integer i = 0;
            //for (Price__c p : [SELECT Id FROM Price__c]){
             //   pIds.add(p.Id);
           // }      
         	QuoteLineItem qli = tUtils.createTestQLI(q.Id, 10, pbList.get(0).Id);
            qli.sampleAutoCreated__c = TRUE;
            qli.manuallyAdded__c = TRUE; 
            insert qli;
            System.debug('QLI%%%==>' + qli);
            //OptyQuoteLIUtility util = new OptyQuoteLIUtility(q.Id, pIds);
            //util.addLineItems();
            GG_Quote_Language__c cs2 = new GG_Quote_Language__c();
            cs2.Name = 'Chinese and English';
            cs2.Output_Language__c = 'Chinese and English';
            cs2.Output_Language_Code__c = 'zh_CN';
            //insert cs2;
            
            GG_Quote_Expiration_Settings__c exps = new GG_Quote_Expiration_Settings__c();
            exps.Name = 'MassParts';
            exps.daysToExpiration__c = 30;
            //insert exps;
            
            GG_Currency_Display_Settings__c cs1 = new GG_Currency_Display_Settings__c();
            cs1.Name = 'Dollar';
            cs1.currency__c = 'Dollar';
            cs1.currencyDisplay__c = 'US$';
            cs1.exchangeValue__c = 1.00;
            cs1.vat__c = 0.00;
            //insert cs1;
            
            GG_Shipping_Term__c cs3 = new GG_Shipping_Term__c();
            cs3.Name = 'DAP';
            cs3.shippingTerm__c = 'Delivered at Place';
            cs3.shippingTermCode__c = 'DAP';
            //insert cs3;
            
            QuoteBoilerplate__c  qb = new QuoteBoilerplate__c();
            qb.Name = 'CCMS Chinese/English';
            qb.isActive__c = true;
            qb.thankYou__c = 'Test Thank You';
            qb.termsAndConditions__c = 'Test Terms and Conditions';
            qb.returnAddress__c = 'Test Address';
            qb.quoteLanguage__c = 'zh_CN';
            qb.preparedFor__c = 'Test Quote Prepared For:';
            qb.preparedBy__c = 'Test Quote Prepared By:';
            qb.corningSellingEntity__c = 'CCMS';
            qb.corningSellingEntityLabel__c = 'Corning Ceramic Materials Shanghai';
            qb.rawRemarks__c = 'These are Raw Remarks';
            qb.concoreRemarks__c = 'These are Concore Remarks';
            qb.partsRemarks__c = 'These are Parts Remarks';
            insert qb;
        }
        return q;
    }
    
    static Quote setUpQuote2() {
        User ta;
        Quote q;
        User thisUser = [Select Id From User Where Id =: UserInfo.getUserId() ];
        system.runAs ( thisUser ) {
            ta = (tUtils.addTestUsers(profileId,1,roleId))[0];
        }
        ta.Street = 'test';
        update ta;
        system.runAs ( ta ) {

            Account a = tUtils.addTestAccount(acctRT);
            Account tpm = tUtils.createTestAccount(acctRT);
            tpm.containsPricing__c = true;
            //insert tpm;
            Account finisher = tUtils.createTestAccount(acctRT);
            finisher.containsPricing__c = true;
            //insert finisher;
            
            Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
            Opportunity o2 = tUtils.createTestOppt(a.Id,oppRT2);
            o2.massProductionOpportunity__c = o.id;
            insert o2;
            o2.StageName = Label.GGSamplePricingAssignment;
            o2.pricingAssignmentComplete__c = true;
            update o2;    
            System.debug('O2==%%%%>' + o2);
            List<PricebookEntry> pbList = tUtils.AddTestGGProductAndPriceBookEntry2(o, tpm, finisher);
            Contact c = tUtils.addTestContact(a.id,contactRT);
            q = tUtils.createTestQuote2(a.id, o2.id,quoteRT2);
            q.corningContact__c = ta.Id;
            q.ContactId = c.Id;
            q.currency__c = 'Yuan';
            q.corningSellingEntity__c = 'CCMS';
            insert q;
            System.Debug('quoterecordId======>' + q.Id);
            
            //List<Id> pIds = new List<Id>();
            //integer i = 0;
            //for (Price__c p : [SELECT Id FROM Price__c]){
             //   pIds.add(p.Id);
           // }     
         	QuoteLineItem qli = tUtils.createTestQLI(q.Id, 10, pbList.get(0).Id);
            qli.sampleAutoCreated__c = TRUE;
            qli.manuallyAdded__c = TRUE; 
            qli.sampleQuantity__c = 10;
            insert qli;
            System.debug('QLI%%%==>' + qli);
            //OptyQuoteLIUtility util = new OptyQuoteLIUtility(q.Id, pIds);
            //util.addLineItems();
            GG_Quote_Language__c cs2 = new GG_Quote_Language__c();
            cs2.Name = 'Chinese and English';
            cs2.Output_Language__c = 'Chinese and English';
            cs2.Output_Language_Code__c = 'zh_CN';
            //insert cs2;
            
            GG_Quote_Expiration_Settings__c exps = new GG_Quote_Expiration_Settings__c();
            exps.Name = 'MassParts';
            exps.daysToExpiration__c = 30;
            //insert exps;
            
            GG_Currency_Display_Settings__c cs1 = new GG_Currency_Display_Settings__c();
            cs1.Name = 'Dollar';
            cs1.currency__c = 'Dollar';
            cs1.currencyDisplay__c = 'US$';
            cs1.exchangeValue__c = 1.00;
            cs1.vat__c = 0.00;
            //insert cs1;
            
            GG_Shipping_Term__c cs3 = new GG_Shipping_Term__c();
            cs3.Name = 'DAP';
            cs3.shippingTerm__c = 'Delivered at Place';
            cs3.shippingTermCode__c = 'DAP';
            //insert cs3;
            
            QuoteBoilerplate__c  qb = new QuoteBoilerplate__c();
            qb.Name = 'CCMS Chinese/English';
            qb.isActive__c = true;
            qb.thankYou__c = 'Test Thank You';
            qb.termsAndConditions__c = 'Test Terms and Conditions';
            qb.returnAddress__c = 'Test Address';
            qb.quoteLanguage__c = 'zh_CN';
            qb.preparedFor__c = 'Test Quote Prepared For:';
            qb.preparedBy__c = 'Test Quote Prepared By:';
            qb.corningSellingEntity__c = 'CCMS';
            qb.corningSellingEntityLabel__c = 'Corning Ceramic Materials Shanghai';
            qb.rawRemarks__c = 'These are Raw Remarks';
            qb.concoreRemarks__c = 'These are Concore Remarks';
            qb.partsRemarks__c = 'These are Parts Remarks';
            insert qb;
        }
        return q;
    }
    
}