force-app/main/default/objects/ForecastOutput52Week__c/ForecastOutput52Week__c.object-meta.xml
<CustomObject>
    <label>Forecast Output</label>
    <nameField>
        <displayFormat>F52-{0000000000}</displayFormat>
        <label>Forecast Output - 52 Week Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Output</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ForecastOutput52Week__c/fields/comments__c.field-meta.xml
<CustomField>
    <fullName>comments__c</fullName>
    <label>Comments</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/coverScreenSize__c.field-meta.xml
<CustomField>
    <fullName>coverScreenSize__c</fullName>
    <label>Cover Screen Size (inches)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/deviceCategory__c.field-meta.xml
<CustomField>
    <fullName>deviceCategory__c</fullName>
    <label>Device Category</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/finalFinishedGlassPartThickness__c.field-meta.xml
<CustomField>
    <fullName>finalFinishedGlassPartThickness__c</fullName>
    <label>Final Finished Glass Part Thickness</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/finisherAccount__c.field-meta.xml
<CustomField>
    <fullName>finisherAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finisher Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Forecast Output (Finisher Account)</relationshipLabel>
    <relationshipName>Forecast_Output</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/finisherMix__c.field-meta.xml
<CustomField>
    <fullName>finisherMix__c</fullName>
    <label>Finisher Mix %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/finisherOwner__c.field-meta.xml
<CustomField>
    <fullName>finisherOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finisher Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Forecast_Output</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/finisherYield__c.field-meta.xml
<CustomField>
    <fullName>finisherYield__c</fullName>
    <label>Finisher Yield %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/glassComposition__c.field-meta.xml
<CustomField>
    <fullName>glassComposition__c</fullName>
    <label>Glass Composition</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/glassCurvature__c.field-meta.xml
<CustomField>
    <fullName>glassCurvature__c</fullName>
    <label>Glass Curvature</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/length__c.field-meta.xml
<CustomField>
    <fullName>length__c</fullName>
    <label>Length</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/m1Date__c.field-meta.xml
<CustomField>
    <fullName>m1Date__c</fullName>
    <label>M1 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/opportunity__c.field-meta.xml
<CustomField>
    <fullName>opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Forecast_Output_52_Weeks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/productName__c.field-meta.xml
<CustomField>
    <fullName>productName__c</fullName>
    <label>Product Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/productSegmentation__c.field-meta.xml
<CustomField>
    <fullName>productSegmentation__c</fullName>
    <label>Product Segmentation</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/programCompleted__c.field-meta.xml
<CustomField>
    <fullName>programCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Program Completed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/specification__c.field-meta.xml
<CustomField>
    <fullName>specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specification</label>
    <referenceTo>Specification__c</referenceTo>
    <relationshipName>Forecast_Output_52_Weeks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/squareFeet__c.field-meta.xml
<CustomField>
    <fullName>squareFeet__c</fullName>
    <label>Square Feet</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/thickness__c.field-meta.xml
<CustomField>
    <fullName>thickness__c</fullName>
    <label>Thickness</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/treatment__c.field-meta.xml
<CustomField>
    <fullName>treatment__c</fullName>
    <label>Treatment</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ForecastOutput52Week__c/fields/width__c.field-meta.xml
<CustomField>
    <fullName>width__c</fullName>
    <label>Width</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/Specification__c.object-meta.xml
<CustomObject>
    <description>Specification/MTO</description>
    <label>Specification</label>
    <nameField>
        <label>Spec Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification__c/fields/age__c.field-meta.xml
<CustomField>
    <fullName>age__c</fullName>
    <formula>IF(isClosed__c,( 
statusChangeDate__c - DATEVALUE(CreatedDate)), 
TODAY() - DATEVALUE(CreatedDate))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/glassComposition__c.field-meta.xml
<CustomField>
    <fullName>glassComposition__c</fullName>
    <label>Glass Composition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlassComposition</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/length__c.field-meta.xml
<CustomField>
    <fullName>length__c</fullName>
    <label>Length (mm)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/opportunity__c.field-meta.xml
<CustomField>
    <fullName>opportunity__c</fullName>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>GG Program, GG Inquiry</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Specifications</relationshipLabel>
    <relationshipName>Specifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Specification__c/fields/productName__c.field-meta.xml
<CustomField>
    <fullName>productName__c</fullName>
    <formula>IF(CONTAINS(RecordType.DeveloperName, &quot;Parts&quot;), 

TEXT(glassComposition__c )+ &quot;; &quot;+ TEXT( FLOOR(thickness__c) ) + &quot;.&quot; + right( text( ( 1 + thickness__c - floor(thickness__c) ) * 1000 ), 3 ) 
+&quot;mm; &quot; + TEXT( FLOOR( width__c ) ) + &quot;.&quot; + right( text( ( 1 + width__c - floor( width__c ) ) * 1000 ), 3 )+&quot;mm x &quot; +TEXT( FLOOR(length__c) ) + &quot;.&quot; + right( text( ( 1 + length__c - floor(length__c) ) * 1000 ), 3 )+&quot;mm; &quot;+productLine__c+ &quot;; &quot;+ (  IF(  ISBLANK(TEXT(application__c)) , opportunityApplication__c, TEXT(application__c))  ) , 

TEXT(glassComposition__c )+ &quot;; &quot;+ TEXT( FLOOR(thickness__c) ) + &quot;.&quot; + right( text( ( 1 + thickness__c - floor(thickness__c) ) * 1000 ), 3 ) 
+&quot;mm; &quot; + TEXT( FLOOR( width__c ) ) + &quot;.&quot; + right( text( ( 1 + width__c - floor( width__c ) ) * 1000 ), 3 )+&quot;mm x &quot; +TEXT( FLOOR(length__c) ) + &quot;.&quot; + right( text( ( 1 + length__c - floor(length__c) ) * 1000 ), 3 )+&quot;mm; &quot;+productLine__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/squareFeet__c.field-meta.xml
<CustomField>
    <fullName>squareFeet__c</fullName>
    <formula>(((width__c * length__c )/25.4)/25.4)/144</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Square Feet (1 Piece)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Innovation Assessment</fullName>
            </value>
            <value>
                <fullName>Missing Information Assessment</fullName>
            </value>
            <value>
                <fullName>Capable Assessment</fullName>
            </value>
            <value>
                <fullName>Standard Assessment</fullName>
            </value>
            <value>
                <fullName>Manufacturer Assignment</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>CM Cost Assessment</fullName>
            </value>
            <value>
                <fullName>Supply, Allocation, and Inventory Review</fullName>
            </value>
            <value>
                <fullName>Product Engineering Input</fullName>
            </value>
            <value>
                <fullName>Plant Engineering Input</fullName>
            </value>
            <value>
                <fullName>Supply Chain Input</fullName>
            </value>
            <value>
                <fullName>Pricing Assignment</fullName>
            </value>
            <value>
                <fullName>Business Case Finalization</fullName>
            </value>
            <value>
                <fullName>Finance Review</fullName>
            </value>
            <value>
                <fullName>Commercial/Ops Review</fullName>
            </value>
            <value>
                <fullName>Pricing Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Business Case Assessment</fullName>
                <isActive>false</isActive>
                <label>Business Case Assessment</label>
            </value>
            <value>
                <fullName>Supply, Allocation, &amp; Inventory Assessment</fullName>
                <isActive>false</isActive>
                <label>Supply, Allocation, &amp; Inventory Assessment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/thickness__c.field-meta.xml
<CustomField>
    <fullName>thickness__c</fullName>
    <label>Thickness (mm)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/TPM__c.field-meta.xml
<CustomField>
    <fullName>TPM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TPM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.isTPM__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Specifications (TPM)</relationshipLabel>
    <relationshipName>SpecificationsTPM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/treatment__c.field-meta.xml
<CustomField>
    <fullName>treatment__c</fullName>
    <label>Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AG+AM</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>Blank+ETC</fullName>
            </value>
            <value>
                <fullName>Blanks</fullName>
            </value>
            <value>
                <fullName>ETC</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/width__c.field-meta.xml
<CustomField>
    <fullName>width__c</fullName>
    <label>Width (mm)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/GlassComposition.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1805</fullName>
    </customValue>
    <customValue>
        <fullName>1807</fullName>
    </customValue>
    <customValue>
        <fullName>1811</fullName>
    </customValue>
    <customValue>
        <fullName>1815</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2317</fullName>
    </customValue>
    <customValue>
        <fullName>2318</fullName>
    </customValue>
    <customValue>
        <fullName>2319</fullName>
    </customValue>
    <customValue>
        <fullName>2320 (GG3)</fullName>
    </customValue>
    <customValue>
        <fullName>2521 (GG3+)</fullName>
    </customValue>
    <customValue>
        <fullName>3318</fullName>
    </customValue>
    <customValue>
        <fullName>4318</fullName>
    </customValue>
    <customValue>
        <fullName>5318 (GG4)</fullName>
    </customValue>
    <customValue>
        <fullName>7321 (GG5)</fullName>
    </customValue>
    <customValue>
        <fullName>7418</fullName>
    </customValue>
    <customValue>
        <fullName>7431 (GG6)</fullName>
    </customValue>
    <customValue>
        <fullName>7541 (Victus)</fullName>
    </customValue>
    <customValue>
        <fullName>7518</fullName>
    </customValue>
    <customValue>
        <fullName>9218</fullName>
    </customValue>
    <customValue>
        <fullName>9318</fullName>
    </customValue>
    <customValue>
        <fullName>9319</fullName>
    </customValue>
    <customValue>
        <fullName>9724</fullName>
    </customValue>
    <customValue>
        <fullName>9726</fullName>
    </customValue>
    <customValue>
        <fullName>Maxwell GC</fullName>
    </customValue>
    <customValue>
        <fullName>MGC</fullName>
    </customValue>
    <customValue>
        <fullName>MM-B</fullName>
    </customValue>
    <customValue>
        <fullName>MX-B</fullName>
    </customValue>
    <customValue>
        <fullName>PHY2</fullName>
    </customValue>
    <customValue>
        <fullName>PHY2.1</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Glass Composition</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityForecastActions.cls
public without sharing class OpportunityForecastActions {

    @AuraEnabled
    public static List<Opportunity> submitForecast(Id oppId) {

       List<Opportunity> updateList = new List<Opportunity>();

       List<Opportunity> oList = new List<Opportunity>([Select Id, createForecast__c
            FROM Opportunity WHERE id = :oppId]);
       
       For (Opportunity o : oList) {
           if (o.createForecast__c == FALSE) {
               o.createForecast__c = TRUE;                          
               updateList.add(o);
           }
       }

       if (updateList.size() == 0) {
       
           throw new AuraHandledException('A forecast for this program has already been created.');
       
       } else {
       
           try {
                update updateList;
           } catch (Exception e) {
                throw new AuraHandledException('Something went wrong: ' + e.getMessage() + '<P/><BR/>' + 'Please edit the record and correct errors before creating the forecast.');   
           }
       
       }
              
       List<Opportunity> returnList = new List<Opportunity>([Select Id
            FROM Opportunity WHERE id = :oppId]);    
       
       return returnList;
     
    }

    @AuraEnabled
    public static List<Opportunity> restoreForecast(Id oppId) {

        List<Opportunity> updateList = getOpportunity(oppId);
        
        // Need to restore OEM forecast *** TO DO ***
        List<ForecastOutput52Week__c> updateForecastList = getForecastOutput(oppId);
        
        
        
        if (updateList.size() == 0) {
           throw new AuraHandledException(ConstantController.RESTORE_ACTIVE_ERR_MSG);
        
        } else {
            if(updateForecastList.size() > 0){
                try {
                    UPDATE updateList;
                    UPSERT updateForecastList;
                } catch (Exception e) {
                    throw new AuraHandledException('Something went wrong: ' + e.getMessage());   
                }
            }else{
                throw new AuraHandledException(ConstantController.RESTORE_COMPLETRD_ERR_MSG);
            }
            
        }
                                 
        List<Opportunity> 
            returnList = new List<Opportunity>([Select Id
                        FROM Opportunity 
                        WHERE id = :oppId]);    
        
        return returnList;
    }
    
    //get the opportunity records.
    private static List<Opportunity> getOpportunity(Id oppId){
        List<Opportunity> updateList = new List<Opportunity>();
        
        try{
            For (Opportunity o : [Select Id, programCompleted__c, createForecast__c
                                  FROM Opportunity 
                                  WHERE id = :oppId
                                  AND programCompleted__c = true]) {
               o.programCompleted__c = FALSE;                          
               updateList.add(o);
            }
        }catch(Exception e){
        }
        return updateList;
    }
    
    //Forecast records that need to change.
    private static List<ForecastOutput52Week__c> getForecastOutput(Id oppId){
        List<ForecastOutput52Week__c> updateForecastList = new List<ForecastOutput52Week__c>();
        
        Date currentMonthDate = Date.newInstance(system.today().Year(), system.today().month(), 1);
        Date preMonthDate = currentMonthDate.addMonths(-1);
        List<Date> forecastDates = new List<Date>{currentMonthDate, preMonthDate};
        System.debug('@@## forecastDates: ' + forecastDates);
        
        List<ForecastOutput52Week__c> fList = getForecastList(oppId, forecastDates);
        System.debug('@@## fList.size=' + fList.size());
        Boolean isCurrentMonth = false;
        Boolean isPrevMonth = false;
        
        try{
            For (ForecastOutput52Week__c f : fList) {
                if(f.m1Date__c == currentMonthDate){
                   f.programCompleted__c = FALSE;     
                   f.status__c = 'Active';                      
                   isCurrentMonth = TRUE;
                   updateForecastList.add(f);
                }
            }
            if(!isCurrentMonth){
                For(ForecastOutput52Week__c f : fList) {
                   if(f.m1Date__c == preMonthDate){
                       f.programCompleted__c = FALSE;     
                       f.status__c = 'Archived'; 
                       isPrevMonth = TRUE;
                       updateForecastList.add(f);
                   }
                }
            }
            if(isPrevMonth){
                List<OpportunityLineItem> olis = getOLIs(oppId);
                List<ForecastOutput52Week__c> forecastToInsert = new List<ForecastOutput52Week__c>();
                forecastToInsert = ForecastHelper.process52(olis, 'Active');
                updateForecastList.addAll(forecastToInsert);
            }
            // JDJD
            if (!isCurrentMonth && !isPrevMonth && overrideM1Date()) {
                For (ForecastOutput52Week__c f : fList) {
                    //if(f.m1Date__c == currentMonthDate){
                       //f.programCompleted__c = FALSE;     
                       f.status__c = 'Active';                      
                       updateForecastList.add(f);
                    //}
                }             
            }
            // END JDJD
        }catch(Exception e){}
     System.debug('@@## updateForecastList size=' + updateForecastList.size())  ;
        return updateForecastList;
    }
    
    private static List<OpportunityLineItem> getOLIs(Id oppId){
        List<OpportunityLineItem> olis = new List<OpportunityLineItem>();
        Date som = System.Date.today().toStartOfMonth();
        try{
        // requery OLI now that schedule is added, create 52 initial week forecast
        olis = [SELECT Id, Opportunity.Id, Opportunity.OwnerId, Opportunity.ForecastCategory, Opportunity.StageName, Opportunity.Amount, 
                Opportunity.CloseDate, Opportunity.age__c, Opportunity.RecordTypeId, 
                Opportunity.Name, Opportunity.AccountId,
                Opportunity.gorillaGlassPercent__c, Opportunity.Competitive_Material__c, 
                Opportunity.pandaPercent__c, Opportunity.agcPercent__c, Opportunity.massProductionYield__c,
                Opportunity.schottPercent__c, Opportunity.negPercent__c, Opportunity.otherPercent__c, Opportunity.deviceCategory__c, 
                Opportunity.productSegmentation__c, Opportunity.competitiveGlasses__c, 
                forecastApplication__c, forecastBrandCustomer__c, coverScreenSize__c, glassComposition__c, 
                glassCurvature__c, length__c, forecastMarketSegment__c,
                forecastMarketSubSegment__c, forecastMassProductionStartDate__c, forecastModelProgramName__c, 
                forecastMonthsInProduction__c, forecastCategory__c,
                LastModifiedById, LastModifiedDate, Product2Id, forecastProductCode__c, 
                forecastProductionVolumePartsMonth__c, ProductName__c,
                forecastProgramName__c, forecastRegion__c, forecastShipToCustomer__c, specification__c,
                specification__r.name, specification__r.tpm__r.id, specification__r.tpm__r.OwnerId, 
                tpmOverride__c, tpmOverride__r.OwnerId,
                squareFeet__c, thickness__c, TotalPrice, Quantity, treatment__c, width__c,
                finisherAccount__c, finisherAccount__r.Name, finisherMix__c, finisherOwner__c, 
                finisherYield__c, comments__c, glassThickness__c,
                finalFinishedGlassPartThickness__c,
                (SELECT Id, Quantity, Revenue, Description, ScheduleDate, LastModifiedById, LastModifiedDate 
                 FROM OpportunityLineItemSchedules WHERE ScheduleDate >= :som ORDER BY ScheduleDate ASC )        
                FROM OpportunityLineItem 
                WHERE HasQuantitySchedule = True 
                AND HasRevenueSchedule = True 
                AND Opportunity.RecordTypeId = '0121J000000U1cZQAS' 
                AND OpportunityId = :oppId] ; 
        }catch(Exception e){}
        
        return olis;
    }
    
    //Method to get all the existing forecast that are created either in current month or previous month.
    private static List<ForecastOutput52Week__c> getForecastList(Id oppId, List<Date> forecastDates){
        List<ForecastOutput52Week__c> 
           fList = new List<ForecastOutput52Week__c>();
        String status = 'Completed';
        // JDJD
        if (overrideM1date()) {
System.debug('@@## overriding .. look for oppId=' + oppId +'status=' + status);
            fList = [Select Id, opportunity__c, m1Date__c,
                     programCompleted__c, status__c
                     FROM ForecastOutput52Week__c 
                     WHERE opportunity__c = :oppId
                     AND Status__c = :status
                    ];           
        }
        // END JDJD
        else {
            try{    
                fList = [Select Id, opportunity__c, m1Date__c,
                         programCompleted__c, status__c
                         FROM ForecastOutput52Week__c 
                         WHERE opportunity__c = :oppId
                         AND m1Date__c IN :forecastDates
                         AND Status__c = :status
                        ];
            }catch(Exception e){
            }
        }
        return fList;
    }
    // Method to check if we allowing current user to reopen a closed forecast ...
    public static Boolean overrideM1date() {
        Set<Id> accessiblePermissionIds = new Set<Id>();
        for (SetupEntityAccess access : [
            SELECT SetupEntityId FROM SetupEntityAccess
            WHERE SetupEntityType = 'CustomPermission' AND ParentId IN (
                SELECT PermissionSetId FROM PermissionSetAssignment
                WHERE AssigneeId = :UserInfo.getUserId()
            )
        ]) accessiblePermissionIds.add(access.SetupEntityId);

    	return 0 < [
            SELECT count() FROM CustomPermission
            WHERE Id IN :accessiblePermissionIds
            AND DeveloperName = 'GG_Allow_Reopen_Forecast'
    	];
    }