force-app/main/default/objects/AccountContract__c/AccountContract__c.object-meta.xml
<CustomObject>
    <label>Account Contract</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContract__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountContract__c/fields/isEvergreen__c.field-meta.xml
<CustomField>
    <fullName>isEvergreen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Evergreen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContractControllerTest.cls
@isTest
private class ContractControllerTest {
    @isTest
    static void TestGetContractRecords()
    {
        Account a = new Account();
        a.name = 'Test';
        insert a;
        
        AccountContract__c ac = new AccountContract__c();
        ac.isEvergreen__c = true;
        ac.account__c = a.id;
        insert ac;
        
        ContractController.GetContractRecords(a.id);
        
    }
}