force-app/main/default/objects/AccountContract__c/AccountContract__c.object-meta.xml
<CustomObject>
    <label>Account Contract</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountContract__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountContract__c/fields/accountName__c.field-meta.xml
<CustomField>
    <fullName>accountName__c</fullName>
    <formula>account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContract__c/fields/expirationDate__c.field-meta.xml
<CustomField>
    <fullName>expirationDate__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AccountContract__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <formula>IF( OR(TODAY() &lt;  expirationDate__c, isEvergreen__c = TRUE) , TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountContract__c/fields/isEvergreen__c.field-meta.xml
<CustomField>
    <fullName>isEvergreen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Evergreen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountContract__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-disclosure Agreement (NDA)</fullName>
            </value>
            <value>
                <fullName>Technical License Agreement (TLA)</fullName>
            </value>
            <value>
                <fullName>Memorandum of Understanding (MOU)</fullName>
            </value>
            <value>
                <fullName>Commercial Framework Agreement (CFA)</fullName>
            </value>
            <value>
                <fullName>Capacity Access Agreement (CAA)</fullName>
            </value>
            <value>
                <fullName>Limited Trademark License Agreement (LTLA)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractController.cls
public without sharing class ContractController {

    @AuraEnabled
    public static List<AccountContract__c> getContractRecords(string accId) {
    
        Set <Id> aIdSet = new Set <Id>();
        
        List <Account> records = new List <Account>([Select Parent.Parent.Parent.Parent.Parent.ParentId, 
             Parent.Parent.Parent.Parent.ParentId,
             Parent.Parent.Parent.ParentId,
             Parent.Parent.ParentId,
             Parent.ParentId,
             ParentId From Account Where Id =: accId LIMIT 1]);
         
        for (Account a : records) {
            aIdSet.add(a.id);
            aIdSet.add(a.ParentId);
            aIdSet.add(a.Parent.ParentId);
            aIdSet.add(a.Parent.Parent.ParentId);
            aIdSet.add(a.Parent.Parent.Parent.ParentId);
            aIdSet.add(a.Parent.Parent.Parent.Parent.ParentId);
            aIdSet.add(a.Parent.Parent.Parent.Parent.Parent.ParentId);
        }
        
        List<ID> aIdList = new List<ID>(aIdSet);
        
        return new List<AccountContract__c>([Select id, isEvergreen__c, isActive__c, accountName__c, type__c, expirationDate__c from AccountContract__c 
        Where account__c =: aIdList LIMIT 100]);
    }
    
}