force-app/main/default/objects/Specification__c/Specification__c.object-meta.xml
<CustomObject>
    <description>Specification/MTO</description>
    <label>Specification</label>
    <nameField>
        <label>Spec Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification__c/fields/opportunity__c.field-meta.xml
<CustomField>
    <fullName>opportunity__c</fullName>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>GG Program, GG Inquiry</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Specifications</relationshipLabel>
    <relationshipName>Specifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Specification__c/fields/PreBuildApproved__c.field-meta.xml
<CustomField>
    <fullName>PreBuildApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pre Build Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Innovation Assessment</fullName>
            </value>
            <value>
                <fullName>Missing Information Assessment</fullName>
            </value>
            <value>
                <fullName>Capable Assessment</fullName>
            </value>
            <value>
                <fullName>Standard Assessment</fullName>
            </value>
            <value>
                <fullName>Manufacturer Assignment</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>CM Cost Assessment</fullName>
            </value>
            <value>
                <fullName>Supply, Allocation, and Inventory Review</fullName>
            </value>
            <value>
                <fullName>Product Engineering Input</fullName>
            </value>
            <value>
                <fullName>Plant Engineering Input</fullName>
            </value>
            <value>
                <fullName>Supply Chain Input</fullName>
            </value>
            <value>
                <fullName>Pricing Assignment</fullName>
            </value>
            <value>
                <fullName>Business Case Finalization</fullName>
            </value>
            <value>
                <fullName>Finance Review</fullName>
            </value>
            <value>
                <fullName>Commercial/Ops Review</fullName>
            </value>
            <value>
                <fullName>Pricing Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Business Case Assessment</fullName>
                <isActive>false</isActive>
                <label>Business Case Assessment</label>
            </value>
            <value>
                <fullName>Supply, Allocation, &amp; Inventory Assessment</fullName>
                <isActive>false</isActive>
                <label>Supply, Allocation, &amp; Inventory Assessment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomLookUpController.cls
/**
 * @description       : 
 * @author            : Adam Nicholson?
 * @group             : 
 * @last modified on  : 07-29-2020
 * @last modified by  : Arquimidez Mora
 * Modifications Log 
 * Ver   Date         Author                 Modification
 * 1.1   ?? ??-2020   Atageldi Atageldiyev   Included query for prebuild specification(Urgent paid sample request)
 * 1.2   07 12-2020   Arquimidez Mora        Fixing issue that doesn't find finisher accounts anymore
 * 1.2.1   07 12-2020   Arquimidez Mora      Removed filter that discarded pricing approved products
**/
public class CustomLookUpController {
    @AuraEnabled
    // This component should be extended to accept the filter field and filter if reused
    public static List < sObject > fetchLookUpValues(String searchKeyWord, String ObjectName, String recordId) {
        system.debug('ObjectName-->' + ObjectName);
        String searchKey = searchKeyWord + '%';
        
        List < sObject > returnList = new List < sObject > ();
      
        // Create a Dynamic SOQL Query For Fetch Record List with LIMIT 5   
        //String sQuery = '';
        // removed TPM filter 
        //String addFilterString = 'TPM'; 
        //sQuery =  'select id, accountType__c, ownerId, Name from ' +ObjectName + ' where accountType__c INCLUDES(:addFilterString) AND Name LIKE: searchKey order by createdDate DESC limit 5';
        String sQuery =  'select id, Name from ' +ObjectName + ' where  Name LIKE: searchKey order by createdDate DESC limit 5';
        if(ObjectName == 'Specification__c'){
            sQuery =  'select id, Name from ' +ObjectName + ' where opportunity__c = \''+ recordId + '\' AND PreBuildApproved__c = TRUE AND status__c != \'Declined\' AND Name LIKE: searchKey order by createdDate DESC limit 5';
        }
		System.debug('query==>' + sQuery);        
        List < sObject > lstOfRecords = Database.query(sQuery);
        
        for (sObject obj: lstOfRecords) {
            returnList.add(obj);
        }
        return returnList;
    }
}