force-app/main/default/objects/Specification__c/Specification__c.object-meta.xml
<CustomObject>
    <description>Specification/MTO</description>
    <label>Specification</label>
    <nameField>
        <label>Spec Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification__c/fields/arEtcPvd__c.field-meta.xml
<CustomField>
    <fullName>arEtcPvd__c</fullName>
    <label>AR/ETC (PVD)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes, No</fullName>
                <isActive>false</isActive>
                <label>Yes, No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/cncNeeded__c.field-meta.xml
<CustomField>
    <fullName>cncNeeded__c</fullName>
    <label>CNC Needed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/Innovation_Type__c.field-meta.xml
<CustomField>
    <fullName>Innovation_Type__c</fullName>
    <label>Innovation Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AntiGlare (AG)</fullName>
            </value>
            <value>
                <fullName>AntiMicrobial</fullName>
            </value>
            <value>
                <fullName>ArtEng</fullName>
            </value>
            <value>
                <fullName>DAR2.0</fullName>
            </value>
            <value>
                <fullName>DX</fullName>
            </value>
            <value>
                <fullName>DXPlus</fullName>
                <label>DX+</label>
            </value>
            <value>
                <fullName>DXC</fullName>
            </value>
            <value>
                <fullName>EZ/AR</fullName>
            </value>
            <value>
                <fullName>AR – Camera Hole</fullName>
            </value>
            <value>
                <fullName>FPS</fullName>
            </value>
            <value>
                <fullName>Glass Back</fullName>
            </value>
            <value>
                <fullName>Glass Ceramics</fullName>
            </value>
            <value>
                <fullName>IT Size 3D</fullName>
            </value>
            <value>
                <fullName>Large Cover Glass</fullName>
            </value>
            <value>
                <fullName>NextGenSRPlus</fullName>
                <label>Next Gen SR+</label>
            </value>
            <value>
                <fullName>non-CE AR</fullName>
            </value>
            <value>
                <fullName>Corning Bendable Glass</fullName>
            </value>
            <value>
                <fullName>Screen Protector</fullName>
            </value>
            <value>
                <fullName>SRPlus</fullName>
                <label>SR+</label>
            </value>
            <value>
                <fullName>Vibrant</fullName>
            </value>
            <value>
                <fullName>Phire 2.0</fullName>
                <isActive>false</isActive>
                <label>Phire 2.0</label>
            </value>
            <value>
                <fullName>Phire 3.0</fullName>
                <isActive>false</isActive>
                <label>Phire 3.0</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/screenPrint__c.field-meta.xml
<CustomField>
    <fullName>screenPrint__c</fullName>
    <label>Screen Print</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Innovation Assessment</fullName>
            </value>
            <value>
                <fullName>Missing Information Assessment</fullName>
            </value>
            <value>
                <fullName>Capable Assessment</fullName>
            </value>
            <value>
                <fullName>Standard Assessment</fullName>
            </value>
            <value>
                <fullName>Manufacturer Assignment</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>CM Cost Assessment</fullName>
            </value>
            <value>
                <fullName>Supply, Allocation, and Inventory Review</fullName>
            </value>
            <value>
                <fullName>Product Engineering Input</fullName>
            </value>
            <value>
                <fullName>Plant Engineering Input</fullName>
            </value>
            <value>
                <fullName>Supply Chain Input</fullName>
            </value>
            <value>
                <fullName>Pricing Assignment</fullName>
            </value>
            <value>
                <fullName>Business Case Finalization</fullName>
            </value>
            <value>
                <fullName>Finance Review</fullName>
            </value>
            <value>
                <fullName>Commercial/Ops Review</fullName>
            </value>
            <value>
                <fullName>Pricing Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Business Case Assessment</fullName>
                <isActive>false</isActive>
                <label>Business Case Assessment</label>
            </value>
            <value>
                <fullName>Supply, Allocation, &amp; Inventory Assessment</fullName>
                <isActive>false</isActive>
                <label>Supply, Allocation, &amp; Inventory Assessment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/submitForApproval__c.field-meta.xml
<CustomField>
    <fullName>submitForApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit for Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/TPM__c.field-meta.xml
<CustomField>
    <fullName>TPM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TPM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.isTPM__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Specifications (TPM)</relationshipLabel>
    <relationshipName>SpecificationsTPM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ImportCostSpecificationDataTest.cls
/*******************************************************************************************************
Class Name       : ImportCostSpecificationDataTest
Purpose          : 
Author           : 
Revision History : 
*****************************************************************************************************/
@isTest
public class ImportCostSpecificationDataTest {    

    // Test Method for data with errors
    static testmethod void testImportCostSpecificationDataErrors(){ 
                
        //Create Data for CSV File
        string header = 'Name,Cost Approval,Cost Assessment Complete,Cost Assessment Comment,Source 1 Incremental GFO,Source 1 Incremental Glass Cost Roof 1YL,Source 1 Incremental Glass Cost Roof 2YL,Source 1 Incremental Glass Cost w/o YL,Source 1 Incremental Process Fee Roof 1,Source 1 Incremental Process Fee Roof 2,Source 1 Incremental Roof 1,Source 1 Incremental Roof 2,Source 1 Incremental TCO,Source 1 Incremental Transportation,Source 1 Incremental Yield Roof 1,Source 1 Incremental Yield Roof 2,Source 2 Incremental GFO,Source 2 Incremental Glass Cost Roof 1YL,Source 2 Incremental Glass Cost Roof 2YL,Source 2 Incremental Glass Cost w/o YL,Source 2 Incremental Process Fee Roof 1,Source 2 Incremental Process Fee Roof 2,Source 2 Incremental Roof 1,Source 2 Incremental Roof 2,Sour;ce 2 Incremental TCO,Source 2 Incremental Transportation,Source 2 Incremental Yield Roof 1,Source 2 Incremental Yield Roof 2 \n';
        string finalstr = header;
        string recordString = 'S-001530-06,Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            'SP001530-06,Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            'SP-X01530-06,Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            'SP-001530.06,Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            ',Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            ',Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            ',Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            ',Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            ',Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            ',Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            ',Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            ',Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            ',Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            ',Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            ',Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            ',Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n' +
            'SP-001530-XX,Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n';        

        finalstr = finalstr + recordString;
        
        Test.startTest();        
            ImportCostSpecificationDataController csv = new ImportCostSpecificationDataController();
            blob csvBlob = Blob.valueOf(finalstr);
            csv.csvFileBody = csvBlob;
            csv.hasNext = true;
            csv.hasPrevious = false;
                    
            csv.importCSVFile();
            csv.ExportCSVFile();
            csv.next();
            csv.previous();
            csv.redirectpage();
            
            MethodException me = new MethodException();
        Test.stopTest();
    }
    
    //Test Method for valid data   
    static testmethod void testImportCostSpecificationDataValid() { 
        
        TestUtilities tUtils = new TestUtilities();  
        String acctRT = '0121J000000U1cV';
        String oppRT = '0121J000000U1cZ';
        String specRT = '0121J000000U1cj';
        String profileId = '00e1J000000h0j3';
        
        Account a = tUtils.addTestAccount(acctRT);
        a.accountType__c = 'TPM';
        update a;
        
        Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
        
        Specification__c testSpec = tUtils.createTestSpec(a.id, o.id, specRT);
        testSpec.tpm__c = a.id;
        testSpec.submitForApproval__c = true;
        testSpec.Status__c = 'New';
        testSpec.cncNeeded__c = 'No'; 
        testSpec.arEtcPvd__c = 'No';
        testSpec.screenPrint__c = 'No';
        testSpec.innovation_Type__c = 'ArtEng';
        insert testSpec;

        testSpec.Status__c = 'CM Cost Assessment';
        testSpec.RecordTypeId = '0121J000000U1cl';
        update testSpec;
        
        String specName = [SELECT Name FROM Specification__c where Id =: testSpec.id].Name;
                        
        string header = 'Name,Cost Approval,Cost Assessment Complete,Cost Assessment Comment,Source 1 Incremental GFO,Source 1 Incremental Glass Cost Roof 1YL,Source 1 Incremental Glass Cost Roof 2YL,Source 1 Incremental Glass Cost w/o YL,Source 1 Incremental Process Fee Roof 1,Source 1 Incremental Process Fee Roof 2,Source 1 Incremental Roof 1,Source 1 Incremental Roof 2,Source 1 Incremental TCO,Source 1 Incremental Transportation,Source 1 Incremental Yield Roof 1,Source 1 Incremental Yield Roof 2,Source 2 Incremental GFO,Source 2 Incremental Glass Cost Roof 1YL,Source 2 Incremental Glass Cost Roof 2YL,Source 2 Incremental Glass Cost w/o YL,Source 2 Incremental Process Fee Roof 1,Source 2 Incremental Process Fee Roof 2,Source 2 Incremental Roof 1,Source 2 Incremental Roof 2,Sour;ce 2 Incremental TCO,Source 2 Incremental Transportation,Source 2 Incremental Yield Roof 1,Source 2 Incremental Yield Roof 2 \n';
        string finalstr = header ;
        string recordString = specName + ',Accepted,TRUE,12345,0.07,0.3,1.82,0.09,0.2,0.06,Jiangmen,Fuzhou,0.08,0.01,0.01,0,0.19,0.1,0.15,0.01,0.1,0.16,CPM,BOE,0.03,0.14,0.12,0.13 \n';

        finalstr = finalstr + recordString;
        
        Test.startTest();
        
            ImportCostSpecificationDataController csv = new ImportCostSpecificationDataController();
            blob csvBlob = Blob.valueOf(finalstr);
            csv.csvFileBody = csvBlob;
                    
            csv.importCSVFile();
        
        Test.stopTest();
    }
 
}