force-app/main/default/objects/Specification__c/Specification__c.object-meta.xml
<CustomObject>
    <description>Specification/MTO</description>
    <label>Specification</label>
    <nameField>
        <label>Spec Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification__c/fields/application__c.field-meta.xml
<CustomField>
    <fullName>application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>application</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/glassComposition__c.field-meta.xml
<CustomField>
    <fullName>glassComposition__c</fullName>
    <label>Glass Composition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlassComposition</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/length__c.field-meta.xml
<CustomField>
    <fullName>length__c</fullName>
    <label>Length (mm)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/marketSegment__c.field-meta.xml
<CustomField>
    <fullName>marketSegment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/marketSubSegment__c.field-meta.xml
<CustomField>
    <fullName>marketSubSegment__c</fullName>
    <label>Market Sub-Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>marketSegment__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>marketSubSegment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/opportunity__c.field-meta.xml
<CustomField>
    <fullName>opportunity__c</fullName>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>GG Program, GG Inquiry</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Specifications</relationshipLabel>
    <relationshipName>Specifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Specification__c/fields/specialShapes__c.field-meta.xml
<CustomField>
    <fullName>specialShapes__c</fullName>
    <label>Glass Curvature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2D</fullName>
            </value>
            <value>
                <fullName>2.5D</fullName>
            </value>
            <value>
                <fullName>3D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Innovation Assessment</fullName>
            </value>
            <value>
                <fullName>Missing Information Assessment</fullName>
            </value>
            <value>
                <fullName>Capable Assessment</fullName>
            </value>
            <value>
                <fullName>Standard Assessment</fullName>
            </value>
            <value>
                <fullName>Manufacturer Assignment</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>CM Cost Assessment</fullName>
            </value>
            <value>
                <fullName>Supply, Allocation, and Inventory Review</fullName>
            </value>
            <value>
                <fullName>Product Engineering Input</fullName>
            </value>
            <value>
                <fullName>Plant Engineering Input</fullName>
            </value>
            <value>
                <fullName>Supply Chain Input</fullName>
            </value>
            <value>
                <fullName>Pricing Assignment</fullName>
            </value>
            <value>
                <fullName>Business Case Finalization</fullName>
            </value>
            <value>
                <fullName>Finance Review</fullName>
            </value>
            <value>
                <fullName>Commercial/Ops Review</fullName>
            </value>
            <value>
                <fullName>Pricing Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Business Case Assessment</fullName>
                <isActive>false</isActive>
                <label>Business Case Assessment</label>
            </value>
            <value>
                <fullName>Supply, Allocation, &amp; Inventory Assessment</fullName>
                <isActive>false</isActive>
                <label>Supply, Allocation, &amp; Inventory Assessment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/thickness__c.field-meta.xml
<CustomField>
    <fullName>thickness__c</fullName>
    <label>Thickness (mm)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/treatment__c.field-meta.xml
<CustomField>
    <fullName>treatment__c</fullName>
    <label>Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AG+AM</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>Blank+ETC</fullName>
            </value>
            <value>
                <fullName>Blanks</fullName>
            </value>
            <value>
                <fullName>ETC</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/width__c.field-meta.xml
<CustomField>
    <fullName>width__c</fullName>
    <label>Width (mm)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/application.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Back Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Camera Lens Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Front Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Home Button</fullName>
    </customValue>
    <customValue>
        <fullName>LCM</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Scanner Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Screen Protector</fullName>
    </customValue>
    <customValue>
        <fullName>Touch Keypad Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Touch Sensor</fullName>
    </customValue>
    <masterLabel>Application</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/GlassComposition.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1805</fullName>
    </customValue>
    <customValue>
        <fullName>1807</fullName>
    </customValue>
    <customValue>
        <fullName>1811</fullName>
    </customValue>
    <customValue>
        <fullName>1815</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2317</fullName>
    </customValue>
    <customValue>
        <fullName>2318</fullName>
    </customValue>
    <customValue>
        <fullName>2319</fullName>
    </customValue>
    <customValue>
        <fullName>2320 (GG3)</fullName>
    </customValue>
    <customValue>
        <fullName>2521 (GG3+)</fullName>
    </customValue>
    <customValue>
        <fullName>3318</fullName>
    </customValue>
    <customValue>
        <fullName>4318</fullName>
    </customValue>
    <customValue>
        <fullName>5318 (GG4)</fullName>
    </customValue>
    <customValue>
        <fullName>7321 (GG5)</fullName>
    </customValue>
    <customValue>
        <fullName>7418</fullName>
    </customValue>
    <customValue>
        <fullName>7431 (GG6)</fullName>
    </customValue>
    <customValue>
        <fullName>7541 (Victus)</fullName>
    </customValue>
    <customValue>
        <fullName>7518</fullName>
    </customValue>
    <customValue>
        <fullName>9218</fullName>
    </customValue>
    <customValue>
        <fullName>9318</fullName>
    </customValue>
    <customValue>
        <fullName>9319</fullName>
    </customValue>
    <customValue>
        <fullName>9724</fullName>
    </customValue>
    <customValue>
        <fullName>9726</fullName>
    </customValue>
    <customValue>
        <fullName>Maxwell GC</fullName>
    </customValue>
    <customValue>
        <fullName>MGC</fullName>
    </customValue>
    <customValue>
        <fullName>MM-B</fullName>
    </customValue>
    <customValue>
        <fullName>MX-B</fullName>
    </customValue>
    <customValue>
        <fullName>PHY2</fullName>
    </customValue>
    <customValue>
        <fullName>PHY2.1</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Glass Composition</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Market_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AIO (desktop)</fullName>
    </customValue>
    <customValue>
        <fullName>Handheld (Phone)</fullName>
    </customValue>
    <customValue>
        <fullName>LCG</fullName>
    </customValue>
    <customValue>
        <fullName>NBD (Module)</fullName>
    </customValue>
    <customValue>
        <fullName>Notebook</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Screen Protector - Amplify</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet</fullName>
    </customValue>
    <customValue>
        <fullName>Wearable</fullName>
    </customValue>
    <masterLabel>Market Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/marketSubSegment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Appliance (refrigerator, oven, etc.)</fullName>
    </customValue>
    <customValue>
        <fullName>AR Head Mounted Device</fullName>
    </customValue>
    <customValue>
        <fullName>Auto</fullName>
    </customValue>
    <customValue>
        <fullName>Camcorder</fullName>
    </customValue>
    <customValue>
        <fullName>Camera</fullName>
    </customValue>
    <customValue>
        <fullName>Clamshell</fullName>
    </customValue>
    <customValue>
        <fullName>Convertible</fullName>
    </customValue>
    <customValue>
        <fullName>Detachable 2-in-1</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Assistant/Scanner</fullName>
    </customValue>
    <customValue>
        <fullName>Feature Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Gaming Device</fullName>
    </customValue>
    <customValue>
        <fullName>Glasses</fullName>
    </customValue>
    <customValue>
        <fullName>IFPD</fullName>
    </customValue>
    <customValue>
        <fullName>Keyboard</fullName>
    </customValue>
    <customValue>
        <fullName>LCM</fullName>
    </customValue>
    <customValue>
        <fullName>Marker Board</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Device</fullName>
    </customValue>
    <customValue>
        <fullName>Monitor</fullName>
    </customValue>
    <customValue>
        <fullName>Music Device</fullName>
    </customValue>
    <customValue>
        <fullName>Navigation Device</fullName>
    </customValue>
    <customValue>
        <fullName>Non-touch NB</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>POS Signature Pad</fullName>
    </customValue>
    <customValue>
        <fullName>Projector</fullName>
    </customValue>
    <customValue>
        <fullName>Screen Protector</fullName>
    </customValue>
    <customValue>
        <fullName>Signage</fullName>
    </customValue>
    <customValue>
        <fullName>Slate</fullName>
    </customValue>
    <customValue>
        <fullName>Smartphone</fullName>
    </customValue>
    <customValue>
        <fullName>Smart Remote</fullName>
    </customValue>
    <customValue>
        <fullName>Solar Technology</fullName>
    </customValue>
    <customValue>
        <fullName>Watch</fullName>
    </customValue>
    <masterLabel>Market Sub-Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/GGSpecificationFileControllerTest.cls
/**
    Name                : GGSpecificationFileControllerTest
    Description         : This is a test class for the GGSpecificationFileController.
*/


@isTest
public class GGSpecificationFileControllerTest {
    @testSetup static void methodName() {
        
        Account acc = new Account(Name = 'Test Account', Type = 'OEM');
        insert acc;
        
        Date myDate = date.newInstance(2020, 01, 21);
        Opportunity opp = new Opportunity(Name = 'Test Opp', AccountId = acc.Id, StageName = '0 - Status Quo',CloseDate = myDate
                                          , type = 'Raw Glass', customerProductModelName__c = 'Testing Product'
                                          , estimatedLaunchDate__c = myDate, application__c = 'Back Cover'
                                          , primaryGlassComposition__c = '1815', region__c = 'CHN', marketSegment__c = 'Wearable'
                                          , specialShapes__c = '2D', treatment__c = 'AG', marketSubSegment__c = 'Watch'
                                          , Start_of_Production__c = myDate, estimatedMonthsInProduction__c = '7'
                                          , estimatedTotalVolume__c = 5, Competitive_Material__c = 'Plastic', gorillaGlassPercent__c = 100
                                          , massProductionYield__c = 1, finalFinishedGlassPartThickness__c = '0.50'
                                          , glassSelectionDate__c = system.today());
        insert opp;
        
        Specification__c spec = new Specification__c(Name = 'Test Spec Name', opportunity__c = opp.Id, glassComposition__c = '1805'
                                                     , width__c = 7387, length__c = 3748, thickness__c = 3874);
        insert spec;
        
        Specification__c specTwo = new Specification__c(Name = 'Test Spec Two', opportunity__c = opp.Id, glassComposition__c = '1815', 
                                                        Status__c ='Pricing Approved'
                                                        , width__c = 7387, length__c = 3748, thickness__c = 3874);
        insert specTwo;
        
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document one';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
        
        ContentVersion cv2 = new ContentVersion();
        cv2.Title = 'Test Document Pricing';
        cv2.PathOnClient = 'TestDocument.pdf';
        cv2.VersionData = Blob.valueOf('Test Content');
        cv2.IsMajorVersion = true;
        Insert cv2;
        
        List<ContentDocument> documentOne = [SELECT Id, Title, LatestPublishedVersionId 
                                            FROM ContentDocument
                                            WHERE Title = 'Test Document one'];
        List<ContentDocument> documentTwo = [SELECT Id, Title, LatestPublishedVersionId 
                                            FROM ContentDocument
                                            WHERE Title = 'Test Document Pricing'];
        
        System.Assert(documentOne.size() == 1);
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=spec.id;
        contentlink.ShareType= 'V';
        contentlink.ContentDocumentId=documentOne[0].Id;
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;
        
        ContentDocumentLink contentlinkTwo =new ContentDocumentLink();
        contentlinkTwo.LinkedEntityId=specTwo.id;
        contentlinkTwo.ShareType= 'V';
        contentlinkTwo.ContentDocumentId=documentTwo[0].Id;
        contentlinkTwo.Visibility = 'AllUsers'; 
        insert contentlinkTwo;
    }
    
    @isTest
    public static void ggcontentUnitTest(){
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId 
                                            FROM ContentDocument
                                            WHERE Title = 'Test Document one'];
        Specification__c specification = [SELECT Id 
                                            FROM Specification__c 
                                            WHERE glassComposition__c = '1805' 
                                            LIMIT 1];
        
        
        List<String> docid = new List<String>();
        for(ContentDocument c: documents){
            docid.add(c.id);
        }
        
        GGSpecificationFileController.getFilesDetails(specification.Id); 
        GGSpecificationFileController.deleteSpecificationFiles(docid,specification.Id);
        
        documents = [SELECT Id, Title, LatestPublishedVersionId 
                                            FROM ContentDocument
                                            WHERE Title = 'Test Document one'];
        System.Assert(documents.size() == 0);
    }
    
    
    @isTest
    public static void ggcontentUnitNegativeTest(){
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId 
                                            FROM ContentDocument
                                            WHERE Title = 'Test Document Pricing'];
        List<String> docids = new List<String>();
        for(ContentDocument c: documents){
            docids.add(c.id);
        }
        
        Specification__c specidTwo = [SELECT Id 
                                       FROM Specification__c 
                                       WHERE glassComposition__c = '1815' 
                                       LIMIT 1];
        
        GGSpecificationFileController.deleteSpecificationFiles(docids, specidTwo.Id);
    }
    
}