force-app/main/default/objects/Specification__c/Specification__c.object-meta.xml
<CustomObject>
    <description>Specification/MTO</description>
    <label>Specification</label>
    <nameField>
        <label>Spec Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification__c/fields/application__c.field-meta.xml
<CustomField>
    <fullName>application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>application</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/cloneReason__c.field-meta.xml
<CustomField>
    <fullName>cloneReason__c</fullName>
    <description>Clone reason</description>
    <inlineHelpText>Clone reason</inlineHelpText>
    <label>Clone Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/ioxNeeded__c.field-meta.xml
<CustomField>
    <fullName>ioxNeeded__c</fullName>
    <label>IOX Needed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/opportunity__c.field-meta.xml
<CustomField>
    <fullName>opportunity__c</fullName>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>GG Program, GG Inquiry</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Specifications</relationshipLabel>
    <relationshipName>Specifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Specification__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Innovation Assessment</fullName>
            </value>
            <value>
                <fullName>Missing Information Assessment</fullName>
            </value>
            <value>
                <fullName>Capable Assessment</fullName>
            </value>
            <value>
                <fullName>Standard Assessment</fullName>
            </value>
            <value>
                <fullName>Manufacturer Assignment</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>CM Cost Assessment</fullName>
            </value>
            <value>
                <fullName>Supply, Allocation, and Inventory Review</fullName>
            </value>
            <value>
                <fullName>Product Engineering Input</fullName>
            </value>
            <value>
                <fullName>Plant Engineering Input</fullName>
            </value>
            <value>
                <fullName>Supply Chain Input</fullName>
            </value>
            <value>
                <fullName>Pricing Assignment</fullName>
            </value>
            <value>
                <fullName>Business Case Finalization</fullName>
            </value>
            <value>
                <fullName>Finance Review</fullName>
            </value>
            <value>
                <fullName>Commercial/Ops Review</fullName>
            </value>
            <value>
                <fullName>Pricing Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Business Case Assessment</fullName>
                <isActive>false</isActive>
                <label>Business Case Assessment</label>
            </value>
            <value>
                <fullName>Supply, Allocation, &amp; Inventory Assessment</fullName>
                <isActive>false</isActive>
                <label>Supply, Allocation, &amp; Inventory Assessment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/submitForApproval__c.field-meta.xml
<CustomField>
    <fullName>submitForApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit for Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/TPM__c.field-meta.xml
<CustomField>
    <fullName>TPM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TPM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.isTPM__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Specifications (TPM)</relationshipLabel>
    <relationshipName>SpecificationsTPM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specification__c/recordTypes/Parts.recordType-meta.xml
<RecordType>
    <fullName>Parts</fullName>
    <active>true</active>
    <description>Gorilla Glass Parts specification</description>
    <label>Parts</label>
</RecordType>

force-app/main/default/globalValueSets/application.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Back Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Camera Lens Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Front Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Home Button</fullName>
    </customValue>
    <customValue>
        <fullName>LCM</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Scanner Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Screen Protector</fullName>
    </customValue>
    <customValue>
        <fullName>Touch Keypad Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Touch Sensor</fullName>
    </customValue>
    <masterLabel>Application</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/SpecificationCloneControllerTest.cls
///*** Added for Gorilla Glass Implementation ***///
///*** Salesforce Cloud Services - 2/15/2017 ***///
///*** Test class for Controller class used in the specification clone custom Lightning component ***///
@isTest
private class SpecificationCloneControllerTest {
    static TestUtilities tUtils = new TestUtilities();
    private static string acctRT;
    private static string oppRT;
    private static string specRT;
    
    static {
        acctRT = tUtils.getRecordTypeId('Account', 'GG Account');
        oppRT = tUtils.getRecordTypeId('Opportunity', 'GG Program');
        specRT = tUtils.getRecordTypeId('Specification__c', 'Parts');
    }

    static testMethod void testCloneSpecNoAttach() {
        tUtils.SetTriggersOnForTesting();
        Account a = tUtils.addTestAccount(acctRT);
        a.accountType__c = 'TPM';
        update a;
        Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
        Specification__c testSpec = tUtils.createTestSpec(a.id, o.id, specRT);
        testSpec.TPM__c = a.id;
        testSpec.ioxNeeded__c = 'No';
        testSpec.status__c = 'New';
        insert testSpec;
        
        Specification__c originalSpec = [SELECT application__c, RecordType.Name 
                                            FROM Specification__c 
                                            WHERE Id = :testSpec.Id LIMIT 1];
                                        
        system.assertEquals('Parts', originalSpec.RecordType.Name); 
                                        
        system.test.startTest();
            SpecificationCloneController.CloneResultWrapper cw = SpecificationCloneController.cloneSpec(testSpec.id, null, false, null);
            string newId = cw.clonedSpecId;
         
            system.assertNotEquals('', newId);
            
            Specification__c insertedSpec = [SELECT Id, status__c, SubmitforApproval__c, RecordType.Name 
                                            FROM Specification__c 
                                            WHERE Id = :newId LIMIT 1];
            
            system.assertEquals('New', insertedSpec.status__c);
            system.assertEquals(false, insertedSpec.SubmitforApproval__c);
            system.assertEquals('Parts', insertedSpec.RecordType.Name);
        system.test.stopTest();
    }
    
    static testMethod void testCloneSpecAttach() {
        tUtils.SetTriggersOnForTesting();
        Account a = tUtils.addTestAccount(acctRT);
        a.accountType__c = 'TPM';
        update a;
        Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
        Specification__c testSpec = tUtils.createTestSpec(a.id, o.id, specRT);
        testSpec.TPM__c = a.id;
        testSpec.ioxNeeded__c = 'No';
        testSpec.status__c = 'New';
        insert testSpec;
        
        Specification__c originalSpec = [SELECT RecordType.Name 
                                            FROM Specification__c 
                                            WHERE Id = :testSpec.Id LIMIT 1];
                                        
        system.assertEquals('Parts', originalSpec.RecordType.Name);                            
        
        //Create Document to Attach
        ContentVersion newCV = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert newCV;
        
        ContentVersion newCV2 = new ContentVersion(
            Title = 'Polar Bears',
            PathOnClient = 'Bears.jpg',
            VersionData = Blob.valueOf('More Test Content'),
            IsMajorVersion = true
        );
        insert newCV2;
        
        List<ContentVersion> insertedCVs = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :newCV.Id];
        List<ContentDocument> cds = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
    
        //Attach to Spec
        ContentDocumentLink newCDL = new ContentDocumentLink();
        newCDL.Visibility = 'AllUsers';
        newCDL.ShareType = 'V';
        newCDL.LinkedEntityId = testSpec.Id;
        newCDL.ContentDocumentId = cds[0].Id;
        insert newCDL;
        
        ContentDocumentLink newCDL2 = new ContentDocumentLink();
        newCDL2.Visibility = 'AllUsers';
        newCDL2.ShareType = 'V';
        newCDL2.LinkedEntityId = testSpec.Id;
        newCDL2.ContentDocumentId = cds[1].Id;
        insert newCDL2;

        system.test.startTest();
        SpecificationCloneController.CloneResultWrapper cw = SpecificationCloneController.cloneSpec(testSpec.id, testSpec.opportunity__c, true, 'Test123');
            string newId = cw.clonedSpecId;
            system.assertNotEquals('', newId);
            
            Specification__c insertedSpec = [SELECT Id, status__c, SubmitforApproval__c, RecordType.Name,cloneReason__c 
                                            FROM Specification__c 
                                            WHERE Id = :newId LIMIT 1];
            
            system.assertEquals('New', insertedSpec.status__c);
            system.assertEquals(false, insertedSpec.SubmitforApproval__c);
            system.assertEquals('Parts', insertedSpec.RecordType.Name);
            system.assertEquals('Test123', insertedSpec.cloneReason__c);
            
            list<ContentDocumentLink> testLink =  [SELECT Visibility, ShareType, LinkedEntityId, ContentDocumentId, ContentDocument.Title
                            FROM ContentDocumentLink 
                            WHERE LinkedEntityId=:insertedSpec.Id];
                            
            system.assertEquals(2, testLink.size());    
            system.assertEquals('AllUsers', testLink[0].Visibility);    
            system.assertEquals('Penguins', testLink[0].ContentDocument.Title); 
            system.assertEquals('Polar Bears', testLink[1].ContentDocument.Title);  

        system.test.stopTest();     
    }
}