force-app/main/default/objects/Specification__c/Specification__c.object-meta.xml
<CustomObject>
    <description>Specification/MTO</description>
    <label>Specification</label>
    <nameField>
        <label>Spec Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification__c/fields/capabilityAssessmentComplete__c.field-meta.xml
<CustomField>
    <fullName>capabilityAssessmentComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Capability Assessment Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/capable__c.field-meta.xml
<CustomField>
    <fullName>capable__c</fullName>
    <label>Capable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Evaluate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/dsActualSource__c.field-meta.xml
<CustomField>
    <fullName>dsActualSource__c</fullName>
    <label>Actual Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual Source</fullName>
            </value>
            <value>
                <fullName>Single Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/dsLocation__c.field-meta.xml
<CustomField>
    <fullName>dsLocation__c</fullName>
    <label>Secondary CM Selected Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Manufacturing_Facility</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/dsManufacturingAssignmentComplete__c.field-meta.xml
<CustomField>
    <fullName>dsManufacturingAssignmentComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Secondary Manufacturing Assignment Compl</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/dsQualityEngineerApproval__c.field-meta.xml
<CustomField>
    <fullName>dsQualityEngineerApproval__c</fullName>
    <label>Secondary QE Approval / AE Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reviewed - More Information Required</fullName>
            </value>
            <value>
                <fullName>Approved - Requires Plant Eng Approval</fullName>
            </value>
            <value>
                <fullName>Approved - Includes Plant Eng Approval</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Reassign CM</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Customer Responded - QA to Confirm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/dsReminderCompleted__c.field-meta.xml
<CustomField>
    <fullName>dsReminderCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/dsSource__c.field-meta.xml
<CustomField>
    <fullName>dsSource__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual Source Accepted</fullName>
            </value>
            <value>
                <fullName>Single Source Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/dsStatus__c.field-meta.xml
<CustomField>
    <fullName>dsStatus__c</fullName>
    <label>Secondary CM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Manufacturer Assignment</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>CM Cost Assessment</fullName>
            </value>
            <value>
                <fullName>Cost Assessment Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Omitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/dsStatusChangeDate__c.field-meta.xml
<CustomField>
    <fullName>dsStatusChangeDate__c</fullName>
    <label>Status Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/Innovation_Type__c.field-meta.xml
<CustomField>
    <fullName>Innovation_Type__c</fullName>
    <label>Innovation Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AntiGlare (AG)</fullName>
            </value>
            <value>
                <fullName>AntiMicrobial</fullName>
            </value>
            <value>
                <fullName>ArtEng</fullName>
            </value>
            <value>
                <fullName>DAR2.0</fullName>
            </value>
            <value>
                <fullName>DX</fullName>
            </value>
            <value>
                <fullName>DXPlus</fullName>
                <label>DX+</label>
            </value>
            <value>
                <fullName>DXC</fullName>
            </value>
            <value>
                <fullName>EZ/AR</fullName>
            </value>
            <value>
                <fullName>AR – Camera Hole</fullName>
            </value>
            <value>
                <fullName>FPS</fullName>
            </value>
            <value>
                <fullName>Glass Back</fullName>
            </value>
            <value>
                <fullName>Glass Ceramics</fullName>
            </value>
            <value>
                <fullName>IT Size 3D</fullName>
            </value>
            <value>
                <fullName>Large Cover Glass</fullName>
            </value>
            <value>
                <fullName>NextGenSRPlus</fullName>
                <label>Next Gen SR+</label>
            </value>
            <value>
                <fullName>non-CE AR</fullName>
            </value>
            <value>
                <fullName>Corning Bendable Glass</fullName>
            </value>
            <value>
                <fullName>Screen Protector</fullName>
            </value>
            <value>
                <fullName>SRPlus</fullName>
                <label>SR+</label>
            </value>
            <value>
                <fullName>Vibrant</fullName>
            </value>
            <value>
                <fullName>Phire 2.0</fullName>
                <isActive>false</isActive>
                <label>Phire 2.0</label>
            </value>
            <value>
                <fullName>Phire 3.0</fullName>
                <isActive>false</isActive>
                <label>Phire 3.0</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/location__c.field-meta.xml
<CustomField>
    <fullName>location__c</fullName>
    <description>Manufacturing facility/location</description>
    <label>Primary CM Selected Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Manufacturing_Facility</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/manufacturingAssignmentComplete__c.field-meta.xml
<CustomField>
    <fullName>manufacturingAssignmentComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Manufacturing Assignment Complet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/missingInformation__c.field-meta.xml
<CustomField>
    <fullName>missingInformation__c</fullName>
    <label>Missing Information</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/missingInformationAssessmentComplete__c.field-meta.xml
<CustomField>
    <fullName>missingInformationAssessmentComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Missing Information Assessment Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/productLine__c.field-meta.xml
<CustomField>
    <fullName>productLine__c</fullName>
    <formula>IF( CONTAINS(RecordType.DeveloperName, &quot;Raw&quot;), &quot;Raw Glass&quot;,
IF( CONTAINS(RecordType.DeveloperName, &quot;Parts&quot;), &quot;Parts&quot;, &quot;Concore&quot;))</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/qualityEngineerApproval__c.field-meta.xml
<CustomField>
    <fullName>qualityEngineerApproval__c</fullName>
    <label>Primary QE Approval / AE Response</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reviewed - More Information Required</fullName>
            </value>
            <value>
                <fullName>Approved - Includes Plant Eng Approval</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Reassign CM</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Customer Responded - QA to Confirm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/reminderCompleted__c.field-meta.xml
<CustomField>
    <fullName>reminderCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/standard__c.field-meta.xml
<CustomField>
    <fullName>standard__c</fullName>
    <label>Standard</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/standardAssessmentComplete__c.field-meta.xml
<CustomField>
    <fullName>standardAssessmentComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Standard Assessment Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Innovation Assessment</fullName>
            </value>
            <value>
                <fullName>Missing Information Assessment</fullName>
            </value>
            <value>
                <fullName>Capable Assessment</fullName>
            </value>
            <value>
                <fullName>Standard Assessment</fullName>
            </value>
            <value>
                <fullName>Manufacturer Assignment</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>CM Cost Assessment</fullName>
            </value>
            <value>
                <fullName>Supply, Allocation, and Inventory Review</fullName>
            </value>
            <value>
                <fullName>Product Engineering Input</fullName>
            </value>
            <value>
                <fullName>Plant Engineering Input</fullName>
            </value>
            <value>
                <fullName>Supply Chain Input</fullName>
            </value>
            <value>
                <fullName>Pricing Assignment</fullName>
            </value>
            <value>
                <fullName>Business Case Finalization</fullName>
            </value>
            <value>
                <fullName>Finance Review</fullName>
            </value>
            <value>
                <fullName>Commercial/Ops Review</fullName>
            </value>
            <value>
                <fullName>Pricing Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Business Case Assessment</fullName>
                <isActive>false</isActive>
                <label>Business Case Assessment</label>
            </value>
            <value>
                <fullName>Supply, Allocation, &amp; Inventory Assessment</fullName>
                <isActive>false</isActive>
                <label>Supply, Allocation, &amp; Inventory Assessment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/statusChangeDate__c.field-meta.xml
<CustomField>
    <fullName>statusChangeDate__c</fullName>
    <label>Status Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/submitForApproval__c.field-meta.xml
<CustomField>
    <fullName>submitForApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit for Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/recordTypes/Parts.recordType-meta.xml
<RecordType>
    <fullName>Parts</fullName>
    <active>true</active>
    <description>Gorilla Glass Parts specification</description>
    <label>Parts</label>
</RecordType>

force-app/main/default/globalValueSets/Manufacturing_Facility.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Biel</fullName>
    </customValue>
    <customValue>
        <fullName>BOE</fullName>
    </customValue>
    <customValue>
        <fullName>BYD-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>CGK</fullName>
    </customValue>
    <customValue>
        <fullName>CPM</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal</fullName>
    </customValue>
    <customValue>
        <fullName>DSBJ</fullName>
    </customValue>
    <customValue>
        <fullName>Fuzhou</fullName>
    </customValue>
    <customValue>
        <fullName>GIS</fullName>
    </customValue>
    <customValue>
        <fullName>GO</fullName>
    </customValue>
    <customValue>
        <fullName>GTOC</fullName>
    </customValue>
    <customValue>
        <fullName>HDC</fullName>
    </customValue>
    <customValue>
        <fullName>HH-LowR</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong Warehouse</fullName>
    </customValue>
    <customValue>
        <fullName>Hony</fullName>
    </customValue>
    <customValue>
        <fullName>HTF</fullName>
    </customValue>
    <customValue>
        <fullName>Huaqing</fullName>
    </customValue>
    <customValue>
        <fullName>J3D</fullName>
    </customValue>
    <customValue>
        <fullName>Jiangmen</fullName>
    </customValue>
    <customValue>
        <fullName>JNTC-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>Kaymao</fullName>
    </customValue>
    <customValue>
        <fullName>KOTL-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>LCE-LR</fullName>
    </customValue>
    <customValue>
        <fullName>LENS-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>LOT</fullName>
    </customValue>
    <customValue>
        <fullName>MFD-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>NGS</fullName>
    </customValue>
    <customValue>
        <fullName>NVD</fullName>
    </customValue>
    <customValue>
        <fullName>Opton</fullName>
    </customValue>
    <customValue>
        <fullName>RKL</fullName>
    </customValue>
    <description>Manufacturing facility selected in the spec</description>
    <masterLabel>Manufacturing Facility</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ChatterHelperRemindersTest.cls
/**
 * @description       : 
 * @author            : Adam Nicholson?
 * @group             : 
 * @last modified on  : 07-10-2020
 * @last modified by  : Arquimidez Mora
 * Modifications Log 
 * Ver   Date         Author            Modification
 * 1.1   07-10-2020   Arquimidez Mora   Fixing test class
**/
// ConnectApi methods are not supported in data siloed tests.
// Please use @IsTest(SeeAllData=true). Class.ConnectApi.ChatterFeeds.postFeedElement

@IsTest(SeeAllData=true)
private class ChatterHelperRemindersTest {
    static TestUtilities tUtils = new TestUtilities();
    private static string acctRT;
    private static string oppRT;
    private static string specRT;
    private static string specRT2;
    private static string specRT3;
    private static string specRT4;
    private static string profileId;
    
    static {
        acctRT = '0121J000000U1cV'; // GG Account
        oppRT = '0121J000000U1cZ'; // GG Program
        specRT = '0121J000000U1cj'; // Parts
        specRT2 = '0121J000000U1cm'; // Raw Glass
        specRT4 = '0121J000001DcdR'; // Parts - RFI
    }

    static Specification__c createNewTestSpec(String recordId, String acctType) { 
        Account a = tUtils.addTestAccount(acctRT, acctType);        
        Opportunity o = tUtils.addTestOppt(a.Id, oppRT);        
        Specification__c s = tUtils.createTestSpec(a.id, o.id, recordId);
        return s;
    }

    // Parts Reminder
    static testMethod void validatePartsReminderMissingInformationAssessment() {
         
        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT, 'TPM');
        testSpec.submitForApproval__c = true;
        insert testSpec;

        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];

        testSpec2.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec2.reminderCompleted__c = false;
        update testSpec2;
        
        Specification__c testSpec3 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, location__c, dsStatusChangeDate__c, dsReminderCompleted__c, dsStatus__c, dsLocation__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec3);
        
        ChatterHelper.specificationReminder( sList ); 
                
    }
 
    // Parts Reminder
    static testMethod void validatePartsReminderManufacturerAssignment() {
         
        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT, 'TPM');
        testSpec.dsSource__c = 'Dual Source Accepted';
        testSpec.submitForApproval__c = true;
        insert testSpec;

        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, missingInformation__c, missingInformationAssessmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.missingInformation__c = 'No';
        testSpec2.missingInformationAssessmentComplete__c = True;
        update testSpec2;
        
        Specification__c testSpec3 = [SELECT Id, capable__c, capabilityAssessmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.capable__c = 'Yes';
        testSpec3.capabilityAssessmentComplete__c = True;
        update testSpec3;

        Specification__c testSpec4 = [SELECT Id, standard__c, standardAssessmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.standard__c = 'Yes';
        testSpec4.standardAssessmentComplete__c = True;
        update testSpec4;

        Specification__c testSpec5 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, location__c, dsStatusChangeDate__c, dsReminderCompleted__c, dsLocation__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec5.location__c = 'Biel';
        testSpec5.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec5.reminderCompleted__c = false;
        testSpec5.dsLocation__c = 'Biel';
        testSpec5.dsStatusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec5.dsReminderCompleted__c = false;        
        update testSpec5;
        
        Specification__c testSpec6 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, location__c, dsStatusChangeDate__c, dsReminderCompleted__c, dsStatus__c, dsLocation__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];           
        sList.add(testSpec6);
        
        ChatterHelper.specificationReminder( sList ); 
                
    }

    // Parts Reminder
    static testMethod void validatePartsReminderRiskAssessment() {
         
        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT, 'TPM');
        testSpec.dsSource__c = 'Dual Source Accepted';
        testSpec.submitForApproval__c = true;
        insert testSpec;

        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, missingInformation__c, missingInformationAssessmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.missingInformation__c = 'No';
        testSpec2.missingInformationAssessmentComplete__c = True;
        update testSpec2;
        
        Specification__c testSpec3 = [SELECT Id, capable__c, capabilityAssessmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.capable__c = 'Yes';
        testSpec3.capabilityAssessmentComplete__c = True;
        update testSpec3;

        Specification__c testSpec4 = [SELECT Id, standard__c, standardAssessmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.standard__c = 'Yes';
        testSpec4.standardAssessmentComplete__c = True;
        update testSpec4;

        Specification__c testSpec5 = [SELECT Id, location__c, manufacturingAssignmentComplete__c, dsActualSource__c, dsLocation__c, dsManufacturingAssignmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec5.location__c = 'Biel';
        testSpec5.manufacturingAssignmentComplete__c = True;
        testSpec5.dsActualSource__c = 'Dual Source';
        testSpec5.dsLocation__c = 'Biel';
        testSpec5.dsManufacturingAssignmentComplete__c = True;
        update testSpec5;

        Specification__c testSpec6 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, dsStatusChangeDate__c, dsReminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec6.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec6.reminderCompleted__c = false;
        testSpec6.dsStatusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec6.dsReminderCompleted__c = false;
        update testSpec6;
        
        Specification__c testSpec7 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, location__c, dsStatusChangeDate__c, dsReminderCompleted__c, dsStatus__c, dsLocation__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec7);
        
        ChatterHelper.specificationReminder( sList ); 
                
    }

    // Parts Reminder
    static testMethod void validatePartsReminderCMCostAssessment() {
         
        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT, 'TPM');
        testSpec.dsSource__c = 'Dual Source Accepted';
        testSpec.submitForApproval__c = true;
        insert testSpec;

        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, missingInformation__c, missingInformationAssessmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.missingInformation__c = 'No';
        testSpec2.missingInformationAssessmentComplete__c = True;
        update testSpec2;
        
        Specification__c testSpec3 = [SELECT Id, capable__c, capabilityAssessmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.capable__c = 'Yes';
        testSpec3.capabilityAssessmentComplete__c = True;
        update testSpec3;

        Specification__c testSpec4 = [SELECT Id, standard__c, standardAssessmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.standard__c = 'Yes';
        testSpec4.standardAssessmentComplete__c = True;
        update testSpec4;

        Specification__c testSpec5 = [SELECT Id, status__c, dsStatus__c, location__c, manufacturingAssignmentComplete__c, dsActualSource__c, dsLocation__c, dsManufacturingAssignmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        system.debug('!!!!! ' + testSpec5.status__c + ' | ' + testSpec5.dsStatus__c); 

        testSpec5.location__c = 'Biel';
        testSpec5.manufacturingAssignmentComplete__c = True;
        testSpec5.dsActualSource__c = 'Dual Source';
        testSpec5.dsLocation__c = 'Biel';
        testSpec5.dsManufacturingAssignmentComplete__c = True;
        update testSpec5;

        Specification__c testSpec6 = [SELECT Id, status__c, dsStatus__c, qualityEngineerApproval__c, dsQualityEngineerApproval__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        system.debug('!!!!! ' + testSpec6.status__c + ' | ' + testSpec6.dsStatus__c); 

        testSpec6.qualityEngineerApproval__c = 'Approved - Includes Plant Eng Approval';
        testSpec6.dsQualityEngineerApproval__c = 'Approved - Includes Plant Eng Approval';
        update testSpec6;

        Specification__c testSpec7 = [SELECT Id, status__c, dsStatus__c, statusChangeDate__c, reminderCompleted__c, dsStatusChangeDate__c, dsReminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        system.debug('!!!!! ' + testSpec7.status__c + ' | ' + testSpec7.dsStatus__c); 
        
        testSpec7.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec7.reminderCompleted__c = false;
        testSpec7.dsStatusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec7.dsReminderCompleted__c = false;
        update testSpec7;
        
        Specification__c testSpec8 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, location__c, dsStatusChangeDate__c, dsReminderCompleted__c, dsStatus__c, dsLocation__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        system.debug('!!!!! ' + testSpec8.status__c + ' | ' + testSpec8.dsStatus__c);        

        sList.add(testSpec8);
        
        ChatterHelper.specificationReminder( sList ); 
                
    }
    
    // Parts Reminder
    static testMethod void validatePartsReminderPricingAssignment() {
         
        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT, 'TPM');
        testSpec.submitForApproval__c = true;
        insert testSpec;

        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, missingInformation__c, missingInformationAssessmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.missingInformation__c = 'No';
        testSpec2.missingInformationAssessmentComplete__c = True;
        update testSpec2;
        
        Specification__c testSpec3 = [SELECT Id, capable__c, capabilityAssessmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.capable__c = 'Yes';
        testSpec3.capabilityAssessmentComplete__c = True;
        update testSpec3;

        Specification__c testSpec4 = [SELECT Id, standard__c, standardAssessmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.standard__c = 'Yes';
        testSpec4.standardAssessmentComplete__c = True;
        update testSpec4;

        Specification__c testSpec5 = [SELECT Id, location__c, manufacturingAssignmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec5.location__c = 'Biel';
        testSpec5.manufacturingAssignmentComplete__c = True;
        update testSpec5;

        Specification__c testSpec6 = [SELECT Id, qualityEngineerApproval__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec6.qualityEngineerApproval__c = 'Approved - Includes Plant Eng Approval';
        update testSpec6;
        
        Specification__c testSpec7 = [SELECT Id, costApproval__c, costAssessmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec7.costApproval__c = 'Accepted';
        testSpec7.costAssessmentComplete__c = True;
        update testSpec7;

        Specification__c testSpec8 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec8.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec8.reminderCompleted__c = false;
        update testSpec8;
        
        Specification__c testSpec9 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, location__c, dsStatusChangeDate__c, dsReminderCompleted__c, dsStatus__c, dsLocation__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec9);
        
        ChatterHelper.specificationReminder( sList ); 
                
    }
        
    // Raw Path 1
    static testMethod void validateRawReminderSAIR() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '2320 (GG3)'; // 2320 is Path 1 // 11-16-20 jd (change to '2320 (GG3)'')
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec2.reminderCompleted__c = false;
        update testSpec2;
        
        Specification__c testSpec3 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec3);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }
    
    // Raw Path 1
    static testMethod void validateRawReminderProductEngineeringInput() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '2320 (GG3)'; // 2320 is Path 1 // 11-16-20 jd (change to '2320 (GG3)'')
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;
       
        Specification__c testSpec3 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec3.reminderCompleted__c = false;
        update testSpec3;
        
        Specification__c testSpec4 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec4);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

    // Raw Path 1
    static testMethod void validateRawReminderPlantEngineeringInput() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '2320 (GG3)'; // 2320 is Path 1 // 11-16-20 jd (change to '2320 (GG3)'')
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;

        Specification__c testSpec3 = [SELECT Id, productEngineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.productEngineeringInputReceived__c = True;
        update testSpec3;
       
        Specification__c testSpec4 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec4.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec4.reminderCompleted__c = false;
        update testSpec4;
        
        Specification__c testSpec5 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec5);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

    // Raw Path 1
    static testMethod void validateRawReminderSupplyChainInput() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '2320 (GG3)'; // 2320 is Path 1 // 11-16-20 jd (change to '2320 (GG3)'')
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;

        Specification__c testSpec3 = [SELECT Id, productEngineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.productEngineeringInputReceived__c = True;
        update testSpec3;
        
        Specification__c testSpec4 = [SELECT Id, engineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.engineeringInputReceived__c = True;
        update testSpec4;
       
        Specification__c testSpec5 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec5.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec5.reminderCompleted__c = false;
        update testSpec5;
        
        Specification__c testSpec6 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec6);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

    // Raw Path 1
    static testMethod void validateRawReminderPricingassignment() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '2320 (GG3)'; // 2320 is Path 1 // 11-16-20 jd (change to '2320 (GG3)'')
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;

        Specification__c testSpec3 = [SELECT Id, productEngineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.productEngineeringInputReceived__c = True;
        update testSpec3;
        
        Specification__c testSpec4 = [SELECT Id, engineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.engineeringInputReceived__c = True;
        update testSpec4;

        Specification__c testSpec5 = [SELECT Id, supplyChainInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec5.supplyChainInputReceived__c = True;
        update testSpec5;
       
        Specification__c testSpec6 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec6.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec6.reminderCompleted__c = false;
        update testSpec6;
        
        Specification__c testSpec7 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec7);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

    // Raw Path 1
    static testMethod void validateRawReminderBusinessCaseFinalization() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '2320 (GG3)'; // 2320 is Path 1 // 11-16-20 jd (change to '2320 (GG3)'')
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;

        Specification__c testSpec3 = [SELECT Id, productEngineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.productEngineeringInputReceived__c = True;
        update testSpec3;
        
        Specification__c testSpec4 = [SELECT Id, engineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.engineeringInputReceived__c = True;
        update testSpec4;

        Specification__c testSpec5 = [SELECT Id, supplyChainInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec5.supplyChainInputReceived__c = True;
        update testSpec5;
 
        Specification__c testSpec6 = [SELECT Id, moq__c, moqUom__c, unitCostSqFt__c, shippingCostSqFt__c, pricingAssignmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec6.moq__c = 1;
        testSpec6.moqUom__c = 'Each';
        testSpec6.unitCostSqFt__c = 1;
        testSpec6.shippingCostSqFt__c = 1;
        testSpec6.pricingAssignmentComplete__c = True;
        update testSpec6;
       
        Specification__c testSpec7 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec7.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec7.reminderCompleted__c = false;
        update testSpec7;
        
        Specification__c testSpec8 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec8);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

    // Raw Path 1
    static testMethod void validateRawReminderFinanceReview() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '2320 (GG3)'; // 2320 is Path 1 // 11-16-20 jd (change to '2320 (GG3)'')
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;

        Specification__c testSpec3 = [SELECT Id, productEngineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.productEngineeringInputReceived__c = True;
        update testSpec3;
        
        Specification__c testSpec4 = [SELECT Id, engineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.engineeringInputReceived__c = True;
        update testSpec4;

        Specification__c testSpec5 = [SELECT Id, supplyChainInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec5.supplyChainInputReceived__c = True;
        update testSpec5;
 
        Specification__c testSpec6 = [SELECT Id, moq__c, moqUom__c, unitCostSqFt__c, shippingCostSqFt__c, pricingAssignmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec6.moq__c = 1;
        testSpec6.moqUom__c = 'Each';
        testSpec6.unitCostSqFt__c = 1;
        testSpec6.shippingCostSqFt__c = 1;
        testSpec6.pricingAssignmentComplete__c = True;
        update testSpec6;

        Specification__c testSpec7 = [SELECT Id, finalBusinessCaseComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec7.finalBusinessCaseComplete__c = True;
        update testSpec7; 
       
        Specification__c testSpec8 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec8.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec8.reminderCompleted__c = false;
        update testSpec8;
        
        Specification__c testSpec9 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, recordTypeId, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec9);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

    // Raw Path 1
    static testMethod void validateRawReminderCommercialOpsReview() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '2320 (GG3)'; // 2320 is Path 1 // 11-16-20 jd (change to '2320 (GG3)'')
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;

        Specification__c testSpec3 = [SELECT Id, productEngineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.productEngineeringInputReceived__c = True;
        update testSpec3;
        
        Specification__c testSpec4 = [SELECT Id, engineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.engineeringInputReceived__c = True;
        update testSpec4;

        Specification__c testSpec5 = [SELECT Id, supplyChainInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec5.supplyChainInputReceived__c = True;
        update testSpec5;
 
        Specification__c testSpec6 = [SELECT Id, moq__c, moqUom__c, unitCostSqFt__c, shippingCostSqFt__c, pricingAssignmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec6.moq__c = 1;
        testSpec6.moqUom__c = 'Each';
        testSpec6.unitCostSqFt__c = 1;
        testSpec6.shippingCostSqFt__c = 1;
        testSpec6.pricingAssignmentComplete__c = True;
        update testSpec6;
 
        Specification__c testSpec7 = [SELECT Id, finalBusinessCaseComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec7.finalBusinessCaseComplete__c = True;
        update testSpec7; 
       
        Specification__c testSpec8 = [SELECT Id, Finance_Review_Complete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec8.Finance_Review_Complete__c = True;
        update testSpec8; 

        Specification__c testSpec9 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec9.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec9.reminderCompleted__c = false;
        update testSpec9;
        
        Specification__c testSpec10 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, recordTypeId, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec10);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

    // Raw Path 2
    static testMethod void validateRawReminderSAIR2() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '9318'; // 9318 is Path 2
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec2.reminderCompleted__c = false;
        update testSpec2;
        
        Specification__c testSpec3 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec3);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }
    
    // Raw Path 2
    static testMethod void validateRawReminderProductEngineeringInput2() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '9318'; // 9318 is Path 2
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;
       
        Specification__c testSpec3 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec3.reminderCompleted__c = false;
        update testSpec3;
        
        Specification__c testSpec4 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec4);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

    // Raw Path 2
    static testMethod void validateRawReminderPlantEngineeringInput2() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '9318'; // 9318 is Path 2
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;

        Specification__c testSpec3 = [SELECT Id, productEngineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.productEngineeringInputReceived__c = True;
        update testSpec3;
       
        Specification__c testSpec4 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec4.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec4.reminderCompleted__c = false;
        update testSpec4;
        
        Specification__c testSpec5 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec5);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

    // Raw Path 2
    static testMethod void validateRawReminderSupplyChainInput2() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '9318'; // 9318 is Path 2
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;

        Specification__c testSpec3 = [SELECT Id, productEngineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.productEngineeringInputReceived__c = True;
        update testSpec3;
        
        Specification__c testSpec4 = [SELECT Id, engineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.engineeringInputReceived__c = True;
        update testSpec4;
       
        Specification__c testSpec5 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec5.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec5.reminderCompleted__c = false;
        update testSpec5;
        
        Specification__c testSpec6 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec6);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

    // Raw Path 2
    static testMethod void validateRawReminderPricingassignment2() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '9318'; // 9318 is Path 2
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;

        Specification__c testSpec3 = [SELECT Id, productEngineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.productEngineeringInputReceived__c = True;
        update testSpec3;
        
        Specification__c testSpec4 = [SELECT Id, engineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.engineeringInputReceived__c = True;
        update testSpec4;

        Specification__c testSpec5 = [SELECT Id, supplyChainInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec5.supplyChainInputReceived__c = True;
        update testSpec5;
       
        Specification__c testSpec6 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec6.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec6.reminderCompleted__c = false;
        update testSpec6;
        
        Specification__c testSpec7 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec7);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

    // Raw Path 2
    static testMethod void validateRawReminderBusinessCaseFinalization2() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '9318'; // 9318 is Path 2
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;

        Specification__c testSpec3 = [SELECT Id, productEngineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.productEngineeringInputReceived__c = True;
        update testSpec3;
        
        Specification__c testSpec4 = [SELECT Id, engineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.engineeringInputReceived__c = True;
        update testSpec4;

        Specification__c testSpec5 = [SELECT Id, supplyChainInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec5.supplyChainInputReceived__c = True;
        update testSpec5;
 
        Specification__c testSpec6 = [SELECT Id, moq__c, moqUom__c, unitCostSqFt__c, shippingCostSqFt__c, pricingAssignmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec6.moq__c = 1;
        testSpec6.moqUom__c = 'Each';
        testSpec6.unitCostSqFt__c = 1;
        testSpec6.shippingCostSqFt__c = 1;
        testSpec6.pricingAssignmentComplete__c = True;
        update testSpec6;
       
        Specification__c testSpec7 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec7.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec7.reminderCompleted__c = false;
        update testSpec7;
        
        Specification__c testSpec8 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec8);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

    // Raw Path 2
    static testMethod void validateRawReminderFinanceReview2() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '9318'; // 9318 is Path 2
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;

        Specification__c testSpec3 = [SELECT Id, productEngineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.productEngineeringInputReceived__c = True;
        update testSpec3;
        
        Specification__c testSpec4 = [SELECT Id, engineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.engineeringInputReceived__c = True;
        update testSpec4;

        Specification__c testSpec5 = [SELECT Id, supplyChainInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec5.supplyChainInputReceived__c = True;
        update testSpec5;
 
        Specification__c testSpec6 = [SELECT Id, moq__c, moqUom__c, unitCostSqFt__c, shippingCostSqFt__c, pricingAssignmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec6.moq__c = 1;
        testSpec6.moqUom__c = 'Each';
        testSpec6.unitCostSqFt__c = 1;
        testSpec6.shippingCostSqFt__c = 1;
        testSpec6.pricingAssignmentComplete__c = True;
        update testSpec6;

        Specification__c testSpec7 = [SELECT Id, finalBusinessCaseComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec7.finalBusinessCaseComplete__c = True;
        update testSpec7; 
       
        Specification__c testSpec8 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec8.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec8.reminderCompleted__c = false;
        update testSpec8;
        
        Specification__c testSpec9 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, recordTypeId, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec9);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

    // Raw Path 2
    static testMethod void validateRawReminderCommercialOpsReview2() {

        List <Specification__c> sList = new List <Specification__c>();
         
        Specification__c testSpec = createNewTestSpec(specRT2, 'TPM');
        testSpec.glassComposition__c = '9318'; // 9318 is Path 2
        testSpec.submitForApproval__c = true;       
        insert testSpec;
        
        string testId = testSpec.id;
        
        Specification__c testSpec2 = [SELECT Id, supplyAllocationInventory__c, supplyAllocInventoryReviewComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec2.supplyAllocationInventory__c = 'Approved';
        testSpec2.supplyAllocInventoryReviewComplete__c = True;
        update testSpec2;

        Specification__c testSpec3 = [SELECT Id, productEngineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec3.productEngineeringInputReceived__c = True;
        update testSpec3;
        
        Specification__c testSpec4 = [SELECT Id, engineeringInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];     
        testSpec4.engineeringInputReceived__c = True;
        update testSpec4;

        Specification__c testSpec5 = [SELECT Id, supplyChainInputReceived__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];               
        testSpec5.supplyChainInputReceived__c = True;
        update testSpec5;
 
        Specification__c testSpec6 = [SELECT Id, moq__c, moqUom__c, unitCostSqFt__c, shippingCostSqFt__c, pricingAssignmentComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec6.moq__c = 1;
        testSpec6.moqUom__c = 'Each';
        testSpec6.unitCostSqFt__c = 1;
        testSpec6.shippingCostSqFt__c = 1;
        testSpec6.pricingAssignmentComplete__c = True;
        update testSpec6;
 
        Specification__c testSpec7 = [SELECT Id, finalBusinessCaseComplete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec7.finalBusinessCaseComplete__c = True;
        update testSpec7; 
       
        Specification__c testSpec8 = [SELECT Id, Finance_Review_Complete__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];       
        testSpec8.Finance_Review_Complete__c = True;
        update testSpec8; 

        Specification__c testSpec9 = [SELECT Id, statusChangeDate__c, reminderCompleted__c, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];
        testSpec9.statusChangeDate__c = System.Date.today().addmonths(-1);
        testSpec9.reminderCompleted__c = false;
        update testSpec9;
        
        Specification__c testSpec10 = [SELECT Id, statusChangeDate__c, productLine__c, reminderCompleted__c, status__c, mtoNotificationPath__c, recordTypeId, Innovation_Type__c FROM Specification__c WHERE id =: testId limit 1];        
        sList.add(testSpec10);
        
        ChatterHelper.specificationReminder( sList ); 
        
    }

}