force-app/main/default/objects/Specification__c/Specification__c.object-meta.xml
<CustomObject>
    <description>Specification/MTO</description>
    <label>Specification</label>
    <nameField>
        <label>Spec Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification__c/fields/opportunity__c.field-meta.xml
<CustomField>
    <fullName>opportunity__c</fullName>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>GG Program, GG Inquiry</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Specifications</relationshipLabel>
    <relationshipName>Specifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Specification__c/fields/previousStepDateTime__c.field-meta.xml
<CustomField>
    <fullName>previousStepDateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Step data/time for previous step - used in the spec&gt;process step duration record creation.</description>
    <inlineHelpText>Step data/time for previous step - used in the spec&gt;process step duration record creation.</inlineHelpText>
    <label>Previous Step Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Innovation Assessment</fullName>
            </value>
            <value>
                <fullName>Missing Information Assessment</fullName>
            </value>
            <value>
                <fullName>Capable Assessment</fullName>
            </value>
            <value>
                <fullName>Standard Assessment</fullName>
            </value>
            <value>
                <fullName>Manufacturer Assignment</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>CM Cost Assessment</fullName>
            </value>
            <value>
                <fullName>Supply, Allocation, and Inventory Review</fullName>
            </value>
            <value>
                <fullName>Product Engineering Input</fullName>
            </value>
            <value>
                <fullName>Plant Engineering Input</fullName>
            </value>
            <value>
                <fullName>Supply Chain Input</fullName>
            </value>
            <value>
                <fullName>Pricing Assignment</fullName>
            </value>
            <value>
                <fullName>Business Case Finalization</fullName>
            </value>
            <value>
                <fullName>Finance Review</fullName>
            </value>
            <value>
                <fullName>Commercial/Ops Review</fullName>
            </value>
            <value>
                <fullName>Pricing Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Business Case Assessment</fullName>
                <isActive>false</isActive>
                <label>Business Case Assessment</label>
            </value>
            <value>
                <fullName>Supply, Allocation, &amp; Inventory Assessment</fullName>
                <isActive>false</isActive>
                <label>Supply, Allocation, &amp; Inventory Assessment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/recordTypes/Parts.recordType-meta.xml
<RecordType>
    <fullName>Parts</fullName>
    <active>true</active>
    <description>Gorilla Glass Parts specification</description>
    <label>Parts</label>
</RecordType>

force-app/main/default/objects/StepDuration__c/StepDuration__c.object-meta.xml
<CustomObject>
    <label>Step Duration</label>
    <nameField>
        <displayFormat>SD-{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Step Durations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/StepDuration__c/fields/opportunity__c.field-meta.xml
<CustomField>
    <fullName>opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Step Durations</relationshipLabel>
    <relationshipName>Step_Durations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StepDuration__c/fields/previousStepDateTime__c.field-meta.xml
<CustomField>
    <fullName>previousStepDateTime__c</fullName>
    <description>Previous status date/time</description>
    <inlineHelpText>Previous status date/time</inlineHelpText>
    <label>Previous Step Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/StepDuration__c/fields/specification__c.field-meta.xml
<CustomField>
    <fullName>specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specification</label>
    <referenceTo>Specification__c</referenceTo>
    <relationshipLabel>Step Durations</relationshipLabel>
    <relationshipName>Step_Durations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StepDurationLoggerTest.cls
///*** Added for Gorilla Glass Implementation ***///
///*** Salesforce Cloud Services - 2/5/2017 ***///
///*** Test Class for Class to log step duration changes for specification and opportunity changes ***///

@isTest
public class StepDurationLoggerTest {
    static TestUtilities tUtils = new TestUtilities();
    private static string acctRT;
    private static string oppRT;
    private static string oppRT2;
    private static string specRT;
    
    static {
        acctRT = tUtils.getRecordTypeId('Account', 'GG Account');
        oppRT = tUtils.getRecordTypeId('Opportunity', 'GG Program');
        oppRT2 = tUtils.getRecordTypeId('Opportunity', 'GG Parts Sample Request');
        specRT = tUtils.getRecordTypeId('Specification__c', 'Parts');
    }
    
    static testMethod void LogSpecificationStepTest() {
        tUtils.SetTriggersOnForTesting();
        Account a = tUtils.addTestAccount(acctRT, 'TPM');
        Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
        Specification__c testSpec = tUtils.addTestSpec(a.id, o.id, specRT);
        Datetime testTime = [SELECT previousStepDateTime__c from Specification__c WHERE Id = :testSpec.Id].previousStepDateTime__c;
        
        integer i = [SELECT Count() FROM StepDuration__c WHERE Opportunity__c = :o.id];
        system.assertEquals(0,i);
            
        testSpec.status__c = 'Standard Assessment';
        update testSpec;
        
    }
    
    static testMethod void LogOpportunityStepTest1() {
        tUtils.SetTriggersOnForTesting();
        Account a = tUtils.addTestAccount(acctRT, 'TPM');
        Opportunity o = tUtils.addTestOppt(a.Id,oppRT2);
        
        Datetime testTime = [SELECT previousStepDateTime__c from Opportunity WHERE Id = :o.Id].previousStepDateTime__c;
        integer i = [SELECT Count() FROM StepDuration__c WHERE Opportunity__c = :o.id];
            
        o.Stagename = '3 - Evaluate Options';
        update o;
        
        test.startTest();
            system.assertEquals(i+1,[SELECT Count() FROM StepDuration__c WHERE Opportunity__c = :o.id]);
            //StepDuration__c post = [SELECT Id, previousStepDateTime__c FROM StepDuration__c WHERE opportunity__c = :o.id];
            //system.assertEquals(testTime,post.previousStepDateTime__c[);
        test.stopTest();
    }

    static testMethod void LogOpportunityStepTest2() {
        tUtils.SetTriggersOnForTesting();
        
        Account a = tUtils.addTestAccount(acctRT, 'TPM');
        Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
        
        Datetime testTime = [SELECT previousStepDateTime__c from Opportunity WHERE Id = :o.Id].previousStepDateTime__c;
        integer i = [SELECT Count() FROM StepDuration__c WHERE Opportunity__c = :o.id];
        system.assertEquals(0,i);
            
        o.Stagename = '3 - Evaluate Options';
        update o;
        
        test.startTest();
            system.assertEquals(0,[SELECT Count() FROM StepDuration__c WHERE Opportunity__c = :o.id]);
        test.stopTest();
    }


    static testMethod void CreateStepDurationRecordTest() {
        list<StepDuration__c> b4List = new list<StepDuration__c>();
        
        Id bId = StepDurationLogger.getMondayFridayBusinessHours();
        system.assertEquals(0,b4List.size());
        
        Account a = tUtils.addTestAccount(acctRT, 'TPM');
        Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
        Specification__c testSpec = tUtils.addTestSpec(a.id, o.id, specRT);
        datetime previousStepDateTime = system.Now();
        StepDurationLogger.CreateStepDurationRecord('SPEC', b4List, testSpec.Id, 'New', 'Standard Assessment', previousStepDateTime, bId);
        
        
        system.assertEquals(1,b4List.size());
    }
}