force-app/main/default/objects/Specification__c/Specification__c.object-meta.xml
<CustomObject>
    <description>Specification/MTO</description>
    <label>Specification</label>
    <nameField>
        <label>Spec Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification__c/fields/opportunity__c.field-meta.xml
<CustomField>
    <fullName>opportunity__c</fullName>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>GG Program, GG Inquiry</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Specifications</relationshipLabel>
    <relationshipName>Specifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Specification__c/fields/previousStepDateTime__c.field-meta.xml
<CustomField>
    <fullName>previousStepDateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Step data/time for previous step - used in the spec&gt;process step duration record creation.</description>
    <inlineHelpText>Step data/time for previous step - used in the spec&gt;process step duration record creation.</inlineHelpText>
    <label>Previous Step Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Innovation Assessment</fullName>
            </value>
            <value>
                <fullName>Missing Information Assessment</fullName>
            </value>
            <value>
                <fullName>Capable Assessment</fullName>
            </value>
            <value>
                <fullName>Standard Assessment</fullName>
            </value>
            <value>
                <fullName>Manufacturer Assignment</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>CM Cost Assessment</fullName>
            </value>
            <value>
                <fullName>Supply, Allocation, and Inventory Review</fullName>
            </value>
            <value>
                <fullName>Product Engineering Input</fullName>
            </value>
            <value>
                <fullName>Plant Engineering Input</fullName>
            </value>
            <value>
                <fullName>Supply Chain Input</fullName>
            </value>
            <value>
                <fullName>Pricing Assignment</fullName>
            </value>
            <value>
                <fullName>Business Case Finalization</fullName>
            </value>
            <value>
                <fullName>Finance Review</fullName>
            </value>
            <value>
                <fullName>Commercial/Ops Review</fullName>
            </value>
            <value>
                <fullName>Pricing Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Business Case Assessment</fullName>
                <isActive>false</isActive>
                <label>Business Case Assessment</label>
            </value>
            <value>
                <fullName>Supply, Allocation, &amp; Inventory Assessment</fullName>
                <isActive>false</isActive>
                <label>Supply, Allocation, &amp; Inventory Assessment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StepDuration__c/StepDuration__c.object-meta.xml
<CustomObject>
    <label>Step Duration</label>
    <nameField>
        <displayFormat>SD-{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Step Durations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/StepDuration__c/fields/calculatedStepDurationHours__c.field-meta.xml
<CustomField>
    <fullName>calculatedStepDurationHours__c</fullName>
    <description>Step duration hours - calculated</description>
    <inlineHelpText>Step duration hours - calculated</inlineHelpText>
    <label>Step Duration (Hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StepDuration__c/fields/newStep__c.field-meta.xml
<CustomField>
    <fullName>newStep__c</fullName>
    <description>New step for the spec or sample opportunity</description>
    <inlineHelpText>New step for the spec or sample opportunity</inlineHelpText>
    <label>New Step</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StepDuration__c/fields/newStepDateTime__c.field-meta.xml
<CustomField>
    <fullName>newStepDateTime__c</fullName>
    <label>New Step Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/StepDuration__c/fields/opportunity__c.field-meta.xml
<CustomField>
    <fullName>opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Step Durations</relationshipLabel>
    <relationshipName>Step_Durations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StepDuration__c/fields/previousStep__c.field-meta.xml
<CustomField>
    <fullName>previousStep__c</fullName>
    <description>Previous step for the spec or sample opportunity</description>
    <inlineHelpText>Previous step for the spec or sample opportunity</inlineHelpText>
    <label>Previous Step</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StepDuration__c/fields/previousStepDateTime__c.field-meta.xml
<CustomField>
    <fullName>previousStepDateTime__c</fullName>
    <description>Previous status date/time</description>
    <inlineHelpText>Previous status date/time</inlineHelpText>
    <label>Previous Step Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/StepDuration__c/fields/specification__c.field-meta.xml
<CustomField>
    <fullName>specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specification</label>
    <referenceTo>Specification__c</referenceTo>
    <relationshipLabel>Step Durations</relationshipLabel>
    <relationshipName>Step_Durations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StepDurationLogger.cls
///*** Added for Gorilla Glass Implementation ***///
///*** Salesforce Cloud Services - 2/5/2017 ***///
///*** Class to log step duration changes for specification and opportunity changes ***///
public class StepDurationLogger {
   static list <string> sampleOppRecordTypes;
   
   //log individual innovation approvals
   private static void logSpecificationInnovationApprovals(Specification__c oldSpec, Specification__c newSpec, list<StepDuration__c> sdList, Id businessHoursId){
       
        //log individual innovation approvals - the fields to be tracked are set up in the InnovationApprovalTrack fieldset
        List<Schema.FieldSetMember> fieldsToTrack = Schema.SObjectType.Specification__c.FieldSets.InnovationApprovalTrack.getFields();
        datetime previousStepDateTime = (oldSpec.previousStepDateTime__c != NULL) ? oldSpec.previousStepDateTime__c : system.Now();
        list<string> fNameList = new list<string>();
        String fPath;
        for (FieldSetMember f: fieldsToTrack){
            fPath = f.getFieldPath();
            if (oldSpec.get(fPath) != newSpec.get(fPath)){
                StepDurationLogger.createStepDurationRecord('SPEC',sdList, newSpec.Id, oldSpec.status__c, newSpec.status__c + ' - ' + f.getLabel() + ' ' + newSpec.get(fPath), previousStepDateTime, businessHoursId);
            }
        }
        
   }
   
   //Create a StepDuration__c record and set spec id/prior step/new step
   public static void LogSpecificationStep(list<Specification__c> afterList, map<ID, Specification__c> beforeMap){
        list<StepDuration__c> sdList = new list<StepDuration__c>();
        Id businessHoursId = getMondayFridayBusinessHours();
        for (Specification__c newSpec : afterList){
            Specification__c oldSpec = beforeMap.get(newSpec.Id);
            if (oldSpec <> NULL && newSpec.status__c <> oldSpec.status__c) {
                newSpec.previousStepDateTime__c = system.Now();
                datetime previousStepDateTime = (oldSpec.previousStepDateTime__c != NULL) ? oldSpec.previousStepDateTime__c : system.Now();
 
                StepDurationLogger.createStepDurationRecord('SPEC',sdList, newSpec.Id, oldSpec.status__c, newSpec.status__c, previousStepDateTime, businessHoursId);
            }
            
            //track innovation changes
            if (oldSpec != null){
                
                logSpecificationInnovationApprovals(oldSpec, newSpec, sdList,businessHoursId);
            }
        }
     
        if (sdList.size() > 0) insert sdList;
    }
    
    //Create a StepDuration__c  record and set optty id/prior step/new step
    public static void LogOpportunityStep(list<Opportunity> afterList, map<ID, Opportunity> beforeMap){
        list<StepDuration__c> sdList = new list<StepDuration__c>();
        set<string> oppRecTypes = new set<string>();
        oppRecTypes = StepDurationLogger.getSampleOppRecordTypes();
        Id businessHoursId = getMondayFridayBusinessHours();
        for (Opportunity newOpp : afterList){
            if (oppRecTypes.contains(newOpp.RecordTypeId)) { 
                Opportunity oldOpp = beforeMap.get(newOpp.Id);
                if (oldOpp <> NULL && newOpp.StageName <> oldOpp.StageName) {
                    newOpp.previousStepDateTime__c = system.Now();
                    datetime previousStepDateTime = (oldOpp.previousStepDateTime__c != NULL) ? oldOpp.previousStepDateTime__c : system.Now();
     
                    StepDurationLogger.createStepDurationRecord('OPP', sdList, newOpp.Id, oldOpp.StageName, newOpp.StageName, previousStepDateTime, businessHoursId);
                }
            }
        }
    
        if (sdList.size() > 0) insert sdList;
    }
    
    //If there is a Monday/Friday business hours record created, use that to calculate business hours
    public static Id getMondayFridayBusinessHours(){
        //get Monday through Friday business hours
        Id bhId = [SELECT Id FROM BusinessHours WHERE IsDefault = true][0].Id;
        for (BusinessHours bh: [SELECT Id FROM BusinessHours WHERE Name = 'Monday-Friday Only' AND IsActive=True]){
            bhId = bh.Id;
            break;
        } 
        return bhId;
    }
    
    //create a step duration record 
    @TestVisible
    private static void CreateStepDurationRecord(string obj, list<StepDuration__c> theList, Id recId, String priorStep, String newStep, Datetime stepTime, Id businessHoursId) {
        StepDuration__c newSD = new StepDuration__c();
        if (obj == 'SPEC') {
            newSD.specification__c = recId;
        }
        else if (obj =='OPP'){
            newSD.opportunity__c = recId;
        }
        
        newSD.previousStep__c = priorStep;
        newSD.newStep__c = newStep;
        newSD.previousStepDateTime__c = stepTime;
        newSd.newStepDateTime__c = DateTime.Now();
        //calculate step duration using businesshours
        //BusinessHours.diff returns time difference in miliseconds, convert it to seconds, minutes and then to hour
        newSD.calculatedStepDurationHours__c = (BusinessHours.diff(businesshoursId, newSD.previousStepDateTime__c, newSD.newStepDateTime__c)*0.001)/60/60;
        //
        
        theList.add(newSD);
        
    }
    
    @TestVisible
    private static set<string> getSampleOppRecordTypes() {
        list<RecordType> rtList = new list<RecordType>();
        set<string> rtSet = new set<string>();
        
        string fnd = '%' + 'Sample' + '%';
        rtList = [SELECT Id FROM RecordType WHERE sObjectTYPE = 'Opportunity' AND Name LIKE :FND];
        
        for (RecordType rt : rtList) {
            rtSet.add(rt.Id);
        }
        return rtSet;
    }
}