force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Only used for Raw Glass and Concore to link to the account for which this price is defined. The account should be the corporate level account.</description>
    <inlineHelpText>Only used for Raw Glass and Concore to link to the account for which this price is defined. The account should be the corporate level account.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/isMTO__c.field-meta.xml
<CustomField>
    <fullName>isMTO__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for sharing rules and updated via trigger. Was previously a formula pulling down the value from Product.</description>
    <label>Is MTO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/IsStandard__c.field-meta.xml
<CustomField>
    <fullName>IsStandard__c</fullName>
    <formula>product__r.isStandard__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsStandard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/priceUnit__c.field-meta.xml
<CustomField>
    <fullName>priceUnit__c</fullName>
    <description>Price/unit</description>
    <inlineHelpText>Price/unit</inlineHelpText>
    <label>Price/Unit (with Shipping)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/product__c.field-meta.xml
<CustomField>
    <fullName>product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/productFamily__c.field-meta.xml
<CustomField>
    <fullName>productFamily__c</fullName>
    <description>Used in sharing rule and updated via trigger.</description>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Raw Glass</fullName>
            </value>
            <value>
                <fullName>Concore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PriceTriggerHelperTest.cls
///*** Added for Gorilla Glass Implementation ***///
///*** Salesforce Cloud Services - 4/18/2017 ***///
///*** Class to test price trigger ***///

@isTest
private class PriceTriggerHelperTest {
    static TestUtilities tUtils = new TestUtilities();
    private static string acctRT;
    private static string oppRT;
    private static string oppRT2;
    private static string quoteRT;
    private static string profileId;
    private static string profileId2;
    private static string profileId3;
    private static string roleId;
    private static string roleId2;
    
    static {
        acctRT = tUtils.getRecordTypeId('Account', 'GG Account');
        roleId = tUtils.getRoleId('GG Sales Mgr Americas/EMEA');
    }
    
    static testMethod void setAvailableToTest() {
        // TO DO: implement unit test
        
    }
    
    static testMethod void setIsMtoTest() {
        User ta;
        
        tUtils.SetTriggersOnForTesting();
        
        Account a = tUtils.addTestAccount(acctRT);
        Account tpm = tUtils.createTestAccount(acctRT);
        tpm.containsPricing__c = true;
        insert tpm;
        Account finisher = tUtils.createTestAccount(acctRT);
        finisher.containsPricing__c = true;
        insert finisher;
        
	    List<Product2> prods = new List<Product2>();
        List<PricebookEntry> priceentries = new List<PricebookEntry>();
          
        prods.add(new Product2(Name = 'Test raw glass', Family = Label.GGProductTypeRaw, isStandard__c = true, isActive=true, isMTO__c = false));   
        prods.add(new Product2(Name = 'Test raw glass', Family = Label.GGProductTypeRaw, isStandard__c = true, isActive=true, isMTO__c = true));   
        prods.add(new Product2(Name = 'Test concore', Family = Label.GGProductTypeConcore, isStandard__c = false, isActive=true, isMTO__c = false));   
        prods.add(new Product2(Name = 'Test concore', Family = Label.GGProductTypeConcore, isStandard__c = false, isActive=true, isMTO__c = true)); 
        insert prods;
	        
        test.startTest();
	        List<Price__c> prices = new List<Price__C>();
	        Price__c pr;
	        integer i = 1;
	        for (Product2 p: prods){
	            if (p.Family == Label.GGProductTypeRaw){
	                pr = new Price__c(Product__c = p.Id, PriceUnit__c = 5*i);
	                pr.Account__c = finisher.Id;
	                prices.add(pr);
	                
	                pr = new Price__c(Product__c = p.Id, PriceUnit__c = 6*i);
	                pr.Account__c = tpm.Id;
	                prices.add(pr);
	            }
	            if (p.Family == Label.GGProductTypeConcore){
	                pr = new Price__c(Product__c = p.Id, PriceUnit__c = 5*i);
	                pr.Account__c = tpm.Id;
	                prices.add(pr);
	            }
	            i++;
	        }
	        insert prices;
	        
	        system.assertEquals (3,[SELECT Count() FROM Price__c WHERE isMTO__c = true AND Product__c IN :Prods]);
	        system.assertEquals (2,[SELECT Count() FROM Price__c WHERE productFamily__c = :Label.GGProductTypeConcore AND Product__c IN :Prods]);
	        system.assertEquals (4,[SELECT Count() FROM Price__c WHERE productFamily__c = :Label.GGProductTypeRaw AND Product__c IN :Prods]);
    	test.stopTest();
    }
}