force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/specification__c.field-meta.xml
<CustomField>
    <fullName>specification__c</fullName>
    <formula>product__r.specification__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Specification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Specification__c/Specification__c.object-meta.xml
<CustomObject>
    <description>Specification/MTO</description>
    <label>Specification</label>
    <nameField>
        <label>Spec Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification__c/fields/pricingAssignmentComplete__c.field-meta.xml
<CustomField>
    <fullName>pricingAssignmentComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pricing Assignment Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Innovation Assessment</fullName>
            </value>
            <value>
                <fullName>Missing Information Assessment</fullName>
            </value>
            <value>
                <fullName>Capable Assessment</fullName>
            </value>
            <value>
                <fullName>Standard Assessment</fullName>
            </value>
            <value>
                <fullName>Manufacturer Assignment</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>CM Cost Assessment</fullName>
            </value>
            <value>
                <fullName>Supply, Allocation, and Inventory Review</fullName>
            </value>
            <value>
                <fullName>Product Engineering Input</fullName>
            </value>
            <value>
                <fullName>Plant Engineering Input</fullName>
            </value>
            <value>
                <fullName>Supply Chain Input</fullName>
            </value>
            <value>
                <fullName>Pricing Assignment</fullName>
            </value>
            <value>
                <fullName>Business Case Finalization</fullName>
            </value>
            <value>
                <fullName>Finance Review</fullName>
            </value>
            <value>
                <fullName>Commercial/Ops Review</fullName>
            </value>
            <value>
                <fullName>Pricing Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Business Case Assessment</fullName>
                <isActive>false</isActive>
                <label>Business Case Assessment</label>
            </value>
            <value>
                <fullName>Supply, Allocation, &amp; Inventory Assessment</fullName>
                <isActive>false</isActive>
                <label>Supply, Allocation, &amp; Inventory Assessment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/submitForApproval__c.field-meta.xml
<CustomField>
    <fullName>submitForApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit for Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/TPM__c.field-meta.xml
<CustomField>
    <fullName>TPM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TPM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.isTPM__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Specifications (TPM)</relationshipLabel>
    <relationshipName>SpecificationsTPM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specification__c/recordTypes/Concore.recordType-meta.xml
<RecordType>
    <fullName>Concore</fullName>
    <active>true</active>
    <description>Gorilla Glass Concore MTO specification</description>
    <label>Concore</label>
</RecordType>

force-app/main/default/objects/Specification__c/recordTypes/Parts.recordType-meta.xml
<RecordType>
    <fullName>Parts</fullName>
    <active>true</active>
    <description>Gorilla Glass Parts specification</description>
    <label>Parts</label>
</RecordType>

force-app/main/default/classes/ProductSearchUtilityTest.cls
/**
 * @File Name          : ProductSearchUtilityTest.cls
 * @Description        : 
 * @Author             : Adam Nicholson?
 * @Group              : 
 * @Last Modified By   : Arquimidez Mora
 * @Last Modified On   : 2/7/2020 14:09:15
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.1    2/7/2020   Arquimidez Mora            Fixing Test Class
**/
///*** Added for Gorilla Glass Implementation ***///
///*** Salesforce Cloud Services - 3/29/2017 ***///
///*** Class to test ProductSearchUtility ***///

@IsTest
private class ProductSearchUtilityTest {
    static TestUtilities tUtils = new TestUtilities();
    private static string acctRT;
    private static string oppRT;
    private static string oppRT2;
    private static string quoteRT;
    private static string quoteRT2;
    private static string specRT;
    private static string profileId;
    private static string roleId;

    static {
        acctRT = tUtils.getRecordTypeId('Account', 'GG Account');
        oppRT = tUtils.getRecordTypeId('Opportunity', 'GG Program');
        oppRT2 = tUtils.getRecordTypeId('Opportunity', 'GG Parts Sample Request');
        quoteRT = tUtils.getRecordTypeId('Quote', 'GG Parts');
        quoteRT2 = tUtils.getRecordTypeId('Quote', 'GG Concore');
        specRT = tUtils.getRecordTypeId('Specification__c', 'Parts');
        profileId = tUtils.getProfileId('GG Account Manager');
        roleId = tUtils.getRoleId('GG Sales Mgr Americas/EMEA');

    }
    
    static testMethod void getMTOSpecProductsTestOpp() {
        tUtils.SetTriggersOnForTesting();
        //tUtils.SetAutoNotificationSettingsForTesting();
        User ta;
        User thisUser = [Select Id From User Where Id =: UserInfo.getUserId() ];
        system.runAs ( thisUser ) {
            ta = (tUtils.addTestUsers(profileId,1,roleId))[0];
        }
        
        system.runAs ( ta ) {
            Account a = tUtils.addTestAccount(acctRT);
            Account tpm = tUtils.createTestAccount(acctRT);
            tpm.containsPricing__c = true;
            tpm.accountType__c = 'TPM';
            insert tpm;
            Account finisher = tUtils.createTestAccount(acctRT);
            finisher.containsPricing__c = true;
            insert finisher;
            Opportunity o = tUtils.addTestOppt(a.Id,oppRT);

            Specification__c testSpec = tUtils.createTestSpec(a.id, o.id, specRT);
            testSpec.TPM__c = tpm.id; 
            testSpec.Status__c = 'New';
            insert testSpec;
            
            //testSpec.submitForApproval__c = true;
            //update testSpec;
            
            tUtils.AddTestGGProductAndPriceBookEntry(o, tpm, finisher); 
                        
            test.startTest();
                ProductSearchWrapper theWrapper = ProductSearchUtility.getMTOSpecProducts(o.id, Label.GGProductTypeConcore, 0, false, 10, false, false, false); 
                system.assertEquals(1,theWrapper.totalRecordCount);
                system.assertNotEquals(null,theWrapper.searchResults);
                system.assertEquals(0,theWrapper.requestedPageNumber);
            test.stopTest();
        }
    }
    
    static testMethod void getMTOSpecProductsTestQuote() {
        tUtils.SetTriggersOnForTesting();
        //tUtils.SetAutoNotificationSettingsForTesting();
        User ta;
        User thisUser = [Select Id From User Where Id =: UserInfo.getUserId() ];
        system.runAs ( thisUser ) {
            ta = (tUtils.addTestUsers(profileId,1,roleId))[0];
        }
        
        system.runAs ( ta ) {
            Account a = tUtils.addTestAccount(acctRT);
            Account tpm = tUtils.createTestAccount(acctRT);
            tpm.containsPricing__c = true;
            tpm.accountType__c = 'TPM';            
            insert tpm;
            Account finisher = tUtils.createTestAccount(acctRT);
            finisher.containsPricing__c = true;
            insert finisher;
 
            Opportunity o = tUtils.addTestOppt(a.Id,oppRT); 
			Opportunity o2 = tUtils.createTestOppt(a.Id,oppRT2);
            o2.massProductionOpportunity__c = o.Id;
            o2.pricingAssignmentComplete__c = true;
            insert o2;
            
            Specification__c testSpec = tUtils.createTestSpec(a.id, o.id, specRT);
            testSpec.TPM__c = tpm.id; 
            testSpec.Status__c = 'New';
            insert testSpec;
            
            //testSpec.submitForApproval__c = true;
            //update testSpec;
            
            Quote q = tUtils.addTestQuote(a.Id,o.Id, o2.Id,quoteRt);
            
            tUtils.AddTestGGProductAndPriceBookEntry(o, tpm, finisher); 
            
            test.startTest();
                ProductSearchWrapper theWrapper = ProductSearchUtility.getMTOSpecProducts(q.id, Label.GGProductTypeParts, 0, false, 10, false, false, false); 
                system.assertEquals(1,theWrapper.totalRecordCount);
                system.assertNotEquals(null,theWrapper.searchResults);
                system.assertEquals(0,theWrapper.requestedPageNumber);
            test.stopTest();
        }
    }
    
    static testMethod void searchProductsConcoreTest() {
        tUtils.SetTriggersOnForTesting();
        //tUtils.SetAutoNotificationSettingsForTesting();
        User ta;
        User thisUser = [Select Id From User Where Id =: UserInfo.getUserId() ];
        system.runAs ( thisUser ) {
            ta = (tUtils.addTestUsers(profileId,1,roleId))[0];
        }
        
        system.runAs ( ta ) {
            Account a = tUtils.addTestAccount(acctRT);
            Account tpm = tUtils.createTestAccount(acctRT);
            tpm.containsPricing__c = true;
            tpm.accountType__c = 'TPM';            
            insert tpm;
            Account finisher = tUtils.createTestAccount(acctRT);
            finisher.containsPricing__c = true;
            insert finisher;
            Opportunity o1 = tUtils.addTestOppt(a.Id,oppRT);

            Opportunity o = tUtils.addTestOppt(a.Id,oppRT2, false); 
            o.massProductionOpportunity__c = o1.Id;
            o.pricingAssignmentComplete__c = true;
            insert o;
            
            Quote q = tUtils.addTestQuote(a.Id,o.Id,quoteRt);
            
            Specification__c testSpec = tUtils.createTestSpec(a.id, o1.id, specRT);
            testSpec.TPM__c = tpm.id; 
            testSpec.Status__c = 'New';
            insert testSpec;
            
            //testSpec.submitForApproval__c = true;
            //update testSpec;
            
            tUtils.AddTestGGProductAndPriceBookEntry(o1, tpm, finisher); 
            List<Id> pIds = new List<Id>();
            integer i = 0;
            for (Price__c p : [SELECT Id FROM Price__c]){
                pIds.add(p.Id);
            }      
            
            OptyQuoteLIUtility util = new OptyQuoteLIUtility(o.Id, pIds);
            util.addLineItems();
            
            string filterStr = 'Test';
            
            //Set SOSL Search results
            Test.setFixedSearchResults(pIds);
            
            test.startTest();
                ProductSearchWrapper theWrapper = ProductSearchUtility.searchProducts(o.Id, 'Concore', filterStr, 0, false, 10, false, false, false);
                system.assertEquals(true, theWrapper.totalRecordCount > 0);
            test.stoptest();
        }
    }
    
    static testMethod void searchProductsPartsTest() {
        tUtils.SetTriggersOnForTesting();
        //tUtils.SetAutoNotificationSettingsForTesting();
        User ta;
        User thisUser = [Select Id From User Where Id =: UserInfo.getUserId() ];
        system.runAs ( thisUser ) {
            ta = (tUtils.addTestUsers(profileId,1,roleId))[0];
        }
        
        system.runAs ( ta ) {
            Account a = tUtils.addTestAccount(acctRT);
            Account tpm = tUtils.createTestAccount(acctRT);
            tpm.containsPricing__c = true;
            tpm.accountType__c = 'TPM';
            insert tpm;
            Account finisher = tUtils.createTestAccount(acctRT);
            finisher.containsPricing__c = true;
            insert finisher;
            Opportunity o1 = tUtils.addTestOppt(a.Id,oppRT);

            Opportunity o = tUtils.addTestOppt(a.Id,oppRT2, false); 
            o.massProductionOpportunity__c = o1.Id;
            o.pricingAssignmentComplete__c = true;
            insert o;
            
            Specification__c testSpec = tUtils.createTestSpec(a.id, o1.id, specRT);
            testSpec.TPM__c = tpm.id; 
            testSpec.Status__c = 'New';
            insert testSpec;
            
            //testSpec.submitForApproval__c = true;
            //update testSpec;
            
            Quote q = tUtils.addTestQuote(a.Id,o.Id,quoteRt);
            
            tUtils.AddTestGGProductAndPriceBookEntry(o1, tpm, finisher); 
            List<Id> pIds = new List<Id>();
            integer i = 0;
            for (Price__c p : [SELECT Id FROM Price__c]){
                pIds.add(p.Id);
            }      
            
            OptyQuoteLIUtility util = new OptyQuoteLIUtility(o.Id, pIds);
            util.addLineItems();
            
            string filterStr = 'Test';
            
            //Set SOSL Search results
            Test.setFixedSearchResults(pIds);
            
            test.startTest();
                ProductSearchWrapper theWrapper = ProductSearchUtility.searchProducts(o.Id, 'Parts', filterStr, 0, false, 10, false, false, false);
                system.assertEquals(true, theWrapper.totalRecordCount > 0);
            test.stoptest();
        }       
    }
}