force-app/main/default/objects/GG_Blue_Pricing_Settings__c/GG_Blue_Pricing_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used by Pricing Trigger to map Opportunity.Owner_Role__c to Price__c.AvailableTo__c value</description>
    <label>GG Blue Pricing Settings</label>
</CustomObject>

force-app/main/default/objects/GG_Blue_Pricing_Settings__c/fields/availableTo__c.field-meta.xml
<CustomField>
    <fullName>availableTo__c</fullName>
    <label>AvailableTo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GG_Blue_Pricing_Settings__c/fields/ownerRole__c.field-meta.xml
<CustomField>
    <fullName>ownerRole__c</fullName>
    <label>Owner Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Price Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Only used for Raw Glass and Concore to link to the account for which this price is defined. The account should be the corporate level account.</description>
    <inlineHelpText>Only used for Raw Glass and Concore to link to the account for which this price is defined. The account should be the corporate level account.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/availableTo__c.field-meta.xml
<CustomField>
    <fullName>availableTo__c</fullName>
    <description>Used to control price record visibility in sharing rules</description>
    <inlineHelpText>Used to control price record visibility in sharing rules</inlineHelpText>
    <label>Available to</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All Customers</fullName>
                <default>true</default>
                <label>All Customers</label>
            </value>
            <value>
                <fullName>Blue Only</fullName>
            </value>
            <value>
                <fullName>Non-finisher AMs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price__c/fields/isMTO__c.field-meta.xml
<CustomField>
    <fullName>isMTO__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for sharing rules and updated via trigger. Was previously a formula pulling down the value from Product.</description>
    <label>Is MTO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/mpQuotePrice1__c.field-meta.xml
<CustomField>
    <fullName>mpQuotePrice1__c</fullName>
    <label>MP Accepted Price 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/mpQuotePrice2__c.field-meta.xml
<CustomField>
    <fullName>mpQuotePrice2__c</fullName>
    <label>MP Accepted Price 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/mpQuotePrice3__c.field-meta.xml
<CustomField>
    <fullName>mpQuotePrice3__c</fullName>
    <label>MP Accepted Price 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/mpQuotePrice4__c.field-meta.xml
<CustomField>
    <fullName>mpQuotePrice4__c</fullName>
    <label>MP Accepted Price 4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/price1__c.field-meta.xml
<CustomField>
    <fullName>price1__c</fullName>
    <description>Parts price for mass production tier 1.</description>
    <inlineHelpText>Parts price for mass production tier 1.</inlineHelpText>
    <label>Price1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/price2__c.field-meta.xml
<CustomField>
    <fullName>price2__c</fullName>
    <description>Parts price for mass production tier 2.</description>
    <inlineHelpText>Parts price for mass production tier 2.</inlineHelpText>
    <label>Price2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/price3__c.field-meta.xml
<CustomField>
    <fullName>price3__c</fullName>
    <description>Parts price for mass production tier 3.</description>
    <inlineHelpText>Parts price for mass production tier 3.</inlineHelpText>
    <label>Price3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/price4__c.field-meta.xml
<CustomField>
    <fullName>price4__c</fullName>
    <description>Parts price for mass production tier 4.</description>
    <inlineHelpText>Parts price for mass production tier 4.</inlineHelpText>
    <label>Price4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/product__c.field-meta.xml
<CustomField>
    <fullName>product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Prices</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/productFamily__c.field-meta.xml
<CustomField>
    <fullName>productFamily__c</fullName>
    <description>Used in sharing rule and updated via trigger.</description>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parts</fullName>
            </value>
            <value>
                <fullName>Raw Glass</fullName>
            </value>
            <value>
                <fullName>Concore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price__c/fields/samplePrice__c.field-meta.xml
<CustomField>
    <fullName>samplePrice__c</fullName>
    <label>Sample Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Price__c/fields/specification__c.field-meta.xml
<CustomField>
    <fullName>specification__c</fullName>
    <formula>product__r.specification__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Specification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Specification__c/Specification__c.object-meta.xml
<CustomObject>
    <description>Specification/MTO</description>
    <label>Specification</label>
    <nameField>
        <label>Spec Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>MTO Finisher or TPM</description>
    <inlineHelpText>MTO Finisher or TPM</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Specifications</relationshipLabel>
    <relationshipName>Specifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/currentPrice1__c.field-meta.xml
<CustomField>
    <fullName>currentPrice1__c</fullName>
    <label>Current Price 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/currentPrice2__c.field-meta.xml
<CustomField>
    <fullName>currentPrice2__c</fullName>
    <label>Current Price 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/currentPrice3__c.field-meta.xml
<CustomField>
    <fullName>currentPrice3__c</fullName>
    <label>Current Price 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/currentPrice4__c.field-meta.xml
<CustomField>
    <fullName>currentPrice4__c</fullName>
    <label>Current Price 4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/currentSamplePrice__c.field-meta.xml
<CustomField>
    <fullName>currentSamplePrice__c</fullName>
    <label>Current Sample Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/isMTO__c.field-meta.xml
<CustomField>
    <fullName>isMTO__c</fullName>
    <formula>IF( CONTAINS(RecordType.DeveloperName, &quot;Raw&quot;) || 
CONTAINS(RecordType.DeveloperName, &quot;Concore&quot;), True,False)</formula>
    <label>IsMTO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/mpQuotePrice1__c.field-meta.xml
<CustomField>
    <fullName>mpQuotePrice1__c</fullName>
    <label>MP Quote Price 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/mpQuotePrice2__c.field-meta.xml
<CustomField>
    <fullName>mpQuotePrice2__c</fullName>
    <label>MP Quote Price 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/mpQuotePrice3__c.field-meta.xml
<CustomField>
    <fullName>mpQuotePrice3__c</fullName>
    <label>MP Quote Price 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/mpQuotePrice4__c.field-meta.xml
<CustomField>
    <fullName>mpQuotePrice4__c</fullName>
    <label>MP Quote Price 4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/opportunity__c.field-meta.xml
<CustomField>
    <fullName>opportunity__c</fullName>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>GG Program, GG Inquiry</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Specifications</relationshipLabel>
    <relationshipName>Specifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Specification__c/fields/price1__c.field-meta.xml
<CustomField>
    <fullName>price1__c</fullName>
    <label>Price 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/price2__c.field-meta.xml
<CustomField>
    <fullName>price2__c</fullName>
    <label>Price 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/price3__c.field-meta.xml
<CustomField>
    <fullName>price3__c</fullName>
    <label>Price 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/price4__c.field-meta.xml
<CustomField>
    <fullName>price4__c</fullName>
    <label>Price 4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/samplePrice__c.field-meta.xml
<CustomField>
    <fullName>samplePrice__c</fullName>
    <label>Sample Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specification__c/recordTypes/Parts.recordType-meta.xml
<RecordType>
    <fullName>Parts</fullName>
    <active>true</active>
    <description>Gorilla Glass Parts specification</description>
    <label>Parts</label>
</RecordType>

force-app/main/default/classes/PriceTriggerHelper.cls
///*** Added for Gorilla Glass Implementation ***///
///*** Salesforce Cloud Services - 3/14/2017 ***///
///*** Class to help Price trigger ***///
//This class shouldn't be run "with sharing" since the MTO flag, product family values, availableTo are set on price trigger
//The price trigger is executed in the PLM user. 
public /*with sharing*/ class PriceTriggerHelper {
    static Utilities Utils = new Utilities();
    
     public static void setAvailableTo(List<Price__c> priceRecs){ 
        map <id,Price__c> priceMap = new map<id,Price__c>();
        set <id> accountOwnerIdSet = new set<id>();
        set <id> specificationIdSet = new set<id>();
        map<id,id> specToPriceMap = new map<id,id>();
        map<id,id> userToPriceMap = new map<id,id>();
        
        for (Price__c price : priceRecs){
            priceMap.put(price.id,price);
        }
        
        //Create list of Price records with the related values we need to test
        list<Price__c> screeningList = [SELECT Id, Account__c, Account__r.OwnerId, Product__c, 
                                        Product__r.Specification__c
                                    FROM Price__c
                                    WHERE Id IN :priceMap.Keyset()]; 
        
        for (Price__c screen : screeningList){
            //Separate those with Specification values from those without 
            if (screen.Product__r.Specification__c <> null){
                //Create set of User Id's to query and create map to link Users to Prices
                specificationIdSet.add(screen.Product__r.Specification__c);
                specToPriceMap.put(screen.Product__r.Specification__c,screen.id);
            }
            else {
                //completely exclude those with no Spec OR Account      
                if (screen.Account__c <> null) {
                    //Create set of User Id's to query and create map to link Users to Prices
                    accountOwnerIdSet.add(screen.Account__r.OwnerId);
                    userToPriceMap.put(screen.Account__r.OwnerId,screen.id);
                }
                else {
                    //Do nothing
                }
            }
        }
        
        //Retrieve custom settings
        map<string,string> pricingMap = new map<string,string>();
        for (GG_Blue_Pricing_Settings__c setting : [SELECT ownerRole__c, availableTo__c FROM GG_Blue_Pricing_Settings__c]){
            pricingMap.put(setting.ownerRole__c,setting.availableTo__c); 
        }

        //Run the User query and Update AvailableTo based on Setting value
        for (User theUser : [SELECT Id, UserRole.Name FROM User WHERE Id IN :accountOwnerIdSet]) {
            if (pricingMap.keyset().contains(theUser.UserRole.Name)){
                //Update the incoming instance of the Price record with the correct value
                priceMap.get(userToPriceMap.get(theUser.Id)).availableTo__c = pricingMap.get(theUser.UserRole.Name);
            }
        }
        
        //Run the Spec query and Update AvailableTo based on Setting value
        for (Specification__c theSpec : [SELECT Id, Opportunity__r.Owner_Role__c FROM Specification__c WHERE Id IN :specificationIdSet]) {
            if (pricingMap.keyset().contains(theSpec.Opportunity__r.Owner_Role__c)){
                //Update the incoming instance of the Price record with the correct value
                priceMap.get(specToPriceMap.get(theSpec.Id)).availableTo__c = pricingMap.get(theSpec.Opportunity__r.Owner_Role__c);
            }
        }           
    }
     
    public static void setIsMTO(List<Price__c> priceRecs){ 
        map <id,Price__c> priceMap = new map<id,Price__c>();
        
        for (Price__c price : priceRecs){
            priceMap.put(price.id,price);
        }
        
        //Create list of Price records with the related values we need to test
        list<Price__c> screeningList = [SELECT Id, Product__c, Product__r.family, Product__r.isMTO__c
                                    FROM Price__c
                                    WHERE Id IN :priceMap.Keyset()]; 
                                    
        for (Price__c screeningRec : screeningList) {
            Price__c recToUpdate = priceMap.get(screeningRec.id);
            recToUpdate.productFamily__c = screeningRec.Product__r.family;
            if (screeningRec.Product__r.isMTO__c == true) {
                recToUpdate.isMto__c = true;
            }   
        }
    }
    
    public static void setSpecPricing(List<Price__c> priceRecs) { 

        system.debug('*** priceRecs: ' + priceRecs.size());

        set <Id> specSet = new set<Id>();
        map <Id, Price__c> specMap = new map<Id, Price__c>();

        // filter out non-parts
        for (Price__c p : priceRecs) {
            system.debug('*** ' + p.id + ' | ' + p.productFamily__c);
            if (p.productFamily__c == 'Parts' && p.specification__c != Null) {
                ID i = Id.valueOf(p.specification__c);
                specSet.add(i);
                specMap.put(i,p);
            }
        }
        
        // query the assoiated specs
        list<Specification__c> specList = [SELECT Id, currentSamplePrice__c, currentPrice1__c, currentPrice2__c, currentPrice3__c, currentPrice4__c, mpQuotePrice1__c, mpQuotePrice2__c, mpQuotePrice3__c, mpQuotePrice4__c
                                    FROM Specification__c WHERE Id IN :specSet];
        
        // update the spec with current pricing
        for (Specification__c s : specList) {
            s.currentPrice1__c = specMap.get((ID)s.id).price1__c; 
            s.currentPrice2__c = specMap.get((ID)s.id).price2__c;
            s.currentPrice3__c = specMap.get((ID)s.id).price3__c;
            s.currentPrice4__c = specMap.get((ID)s.id).price4__c;
            s.currentSamplePrice__c = specMap.get((ID)s.id).samplePrice__c;
            s.mpQuotePrice1__c = specMap.get((ID)s.id).mpQuotePrice1__c; 
            s.mpQuotePrice2__c = specMap.get((ID)s.id).mpQuotePrice2__c;
            s.mpQuotePrice3__c = specMap.get((ID)s.id).mpQuotePrice3__c;
            s.mpQuotePrice4__c = specMap.get((ID)s.id).mpQuotePrice4__c;
        }

        update specList;                        
 
    }
}