force-app/main/default/objects/StandardProductInventoryLoader__c/StandardProductInventoryLoader__c.object-meta.xml
<CustomObject>
    <label>Standard Product Inventory Loader</label>
    <nameField>
        <displayFormat>DATA-{00000000}</displayFormat>
        <label>Standard Product Import Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Product Inventory Loader</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StandardProductInventoryLoader__c/fields/glassComposition__c.field-meta.xml
<CustomField>
    <fullName>glassComposition__c</fullName>
    <label>Glass Composition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlassComposition</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/StandardProductInventoryLoader__c/fields/productLine__c.field-meta.xml
<CustomField>
    <fullName>productLine__c</fullName>
    <description>This data loader only supports standard raw glass product adds and updates.</description>
    <inlineHelpText>This data loader only supports standard raw glass product adds and updates.</inlineHelpText>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Raw Glass</fullName>
                <default>true</default>
                <label>Raw Glass</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StandardProductInventoryLoader__c/fields/standardProductInventoryMatrix__c.field-meta.xml
<CustomField>
    <fullName>standardProductInventoryMatrix__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Standard Product Inventory Matrix</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>StandardProductInventoryMatrix__c.isActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>StandardProductInventoryMatrix__c</referenceTo>
    <relationshipLabel>Standard Product Inventory Loader</relationshipLabel>
    <relationshipName>Standard_Product_Inventory_Loader</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StandardProductInventoryLoader__c/fields/thickness__c.field-meta.xml
<CustomField>
    <fullName>thickness__c</fullName>
    <label>Thickness</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>.95</fullName>
            </value>
            <value>
                <fullName>0.25</fullName>
            </value>
            <value>
                <fullName>0.33</fullName>
            </value>
            <value>
                <fullName>0.40</fullName>
            </value>
            <value>
                <fullName>0.405</fullName>
            </value>
            <value>
                <fullName>0.50</fullName>
            </value>
            <value>
                <fullName>0.505</fullName>
            </value>
            <value>
                <fullName>0.55</fullName>
            </value>
            <value>
                <fullName>0.555</fullName>
            </value>
            <value>
                <fullName>0.60</fullName>
            </value>
            <value>
                <fullName>0.605</fullName>
            </value>
            <value>
                <fullName>0.65</fullName>
            </value>
            <value>
                <fullName>0.70</fullName>
            </value>
            <value>
                <fullName>0.80</fullName>
            </value>
            <value>
                <fullName>0.81</fullName>
            </value>
            <value>
                <fullName>0.89</fullName>
            </value>
            <value>
                <fullName>0.90</fullName>
            </value>
            <value>
                <fullName>0.95</fullName>
            </value>
            <value>
                <fullName>1.00</fullName>
            </value>
            <value>
                <fullName>1.05</fullName>
            </value>
            <value>
                <fullName>1.10</fullName>
            </value>
            <value>
                <fullName>1.20</fullName>
            </value>
            <value>
                <fullName>1.30</fullName>
            </value>
            <value>
                <fullName>1.35</fullName>
            </value>
            <value>
                <fullName>1.40</fullName>
            </value>
            <value>
                <fullName>1.50</fullName>
            </value>
            <value>
                <fullName>1.60</fullName>
            </value>
            <value>
                <fullName>1.62</fullName>
            </value>
            <value>
                <fullName>1.70</fullName>
            </value>
            <value>
                <fullName>1.76</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StandardProductInventoryMatrix__c/StandardProductInventoryMatrix__c.object-meta.xml
<CustomObject>
    <label>Standard Product Inventory Matrix</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Product Inventory Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/customLength__c.field-meta.xml
<CustomField>
    <fullName>customLength__c</fullName>
    <label>Length</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/customWidth__c.field-meta.xml
<CustomField>
    <fullName>customWidth__c</fullName>
    <label>Width</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/glassComposition__c.field-meta.xml
<CustomField>
    <fullName>glassComposition__c</fullName>
    <label>Glass Composition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlassComposition</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/length__c.field-meta.xml
<CustomField>
    <fullName>length__c</fullName>
    <label>xLength</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>300</fullName>
            </value>
            <value>
                <fullName>576</fullName>
            </value>
            <value>
                <fullName>581</fullName>
            </value>
            <value>
                <fullName>585</fullName>
            </value>
            <value>
                <fullName>602</fullName>
            </value>
            <value>
                <fullName>607</fullName>
            </value>
            <value>
                <fullName>611</fullName>
            </value>
            <value>
                <fullName>632</fullName>
            </value>
            <value>
                <fullName>633</fullName>
            </value>
            <value>
                <fullName>634</fullName>
            </value>
            <value>
                <fullName>637</fullName>
            </value>
            <value>
                <fullName>639</fullName>
            </value>
            <value>
                <fullName>641</fullName>
            </value>
            <value>
                <fullName>642</fullName>
            </value>
            <value>
                <fullName>650</fullName>
            </value>
            <value>
                <fullName>1010</fullName>
            </value>
            <value>
                <fullName>1110</fullName>
            </value>
            <value>
                <fullName>1130</fullName>
            </value>
            <value>
                <fullName>1160</fullName>
            </value>
            <value>
                <fullName>1230</fullName>
            </value>
            <value>
                <fullName>1250</fullName>
            </value>
            <value>
                <fullName>1258</fullName>
            </value>
            <value>
                <fullName>1278</fullName>
            </value>
            <value>
                <fullName>1328</fullName>
            </value>
            <value>
                <fullName>1330</fullName>
            </value>
            <value>
                <fullName>1422</fullName>
            </value>
            <value>
                <fullName>1460</fullName>
            </value>
            <value>
                <fullName>1494</fullName>
            </value>
            <value>
                <fullName>1500</fullName>
            </value>
            <value>
                <fullName>1540</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/productLine__c.field-meta.xml
<CustomField>
    <fullName>productLine__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Raw Glass</fullName>
                <default>true</default>
                <label>Raw Glass</label>
            </value>
            <value>
                <fullName>Concore</fullName>
                <isActive>false</isActive>
                <label>Concore</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/thickness__c.field-meta.xml
<CustomField>
    <fullName>thickness__c</fullName>
    <label>Thickness</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>.95</fullName>
            </value>
            <value>
                <fullName>0.25</fullName>
            </value>
            <value>
                <fullName>0.33</fullName>
            </value>
            <value>
                <fullName>0.40</fullName>
            </value>
            <value>
                <fullName>0.405</fullName>
            </value>
            <value>
                <fullName>0.50</fullName>
            </value>
            <value>
                <fullName>0.505</fullName>
            </value>
            <value>
                <fullName>0.55</fullName>
            </value>
            <value>
                <fullName>0.555</fullName>
            </value>
            <value>
                <fullName>0.60</fullName>
            </value>
            <value>
                <fullName>0.605</fullName>
            </value>
            <value>
                <fullName>0.65</fullName>
            </value>
            <value>
                <fullName>0.70</fullName>
            </value>
            <value>
                <fullName>0.80</fullName>
            </value>
            <value>
                <fullName>0.81</fullName>
            </value>
            <value>
                <fullName>0.89</fullName>
            </value>
            <value>
                <fullName>0.90</fullName>
            </value>
            <value>
                <fullName>0.95</fullName>
            </value>
            <value>
                <fullName>1.00</fullName>
            </value>
            <value>
                <fullName>1.05</fullName>
            </value>
            <value>
                <fullName>1.10</fullName>
            </value>
            <value>
                <fullName>1.20</fullName>
            </value>
            <value>
                <fullName>1.30</fullName>
            </value>
            <value>
                <fullName>1.35</fullName>
            </value>
            <value>
                <fullName>1.40</fullName>
            </value>
            <value>
                <fullName>1.50</fullName>
            </value>
            <value>
                <fullName>1.60</fullName>
            </value>
            <value>
                <fullName>1.62</fullName>
            </value>
            <value>
                <fullName>1.70</fullName>
            </value>
            <value>
                <fullName>1.76</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/width__c.field-meta.xml
<CustomField>
    <fullName>width__c</fullName>
    <label>xWidth</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>217</fullName>
            </value>
            <value>
                <fullName>225</fullName>
            </value>
            <value>
                <fullName>229</fullName>
            </value>
            <value>
                <fullName>237</fullName>
            </value>
            <value>
                <fullName>245</fullName>
            </value>
            <value>
                <fullName>248</fullName>
            </value>
            <value>
                <fullName>250</fullName>
            </value>
            <value>
                <fullName>265</fullName>
            </value>
            <value>
                <fullName>276</fullName>
            </value>
            <value>
                <fullName>279</fullName>
            </value>
            <value>
                <fullName>280</fullName>
            </value>
            <value>
                <fullName>300</fullName>
            </value>
            <value>
                <fullName>650</fullName>
            </value>
            <value>
                <fullName>1094</fullName>
            </value>
            <value>
                <fullName>1164</fullName>
            </value>
            <value>
                <fullName>1166</fullName>
            </value>
            <value>
                <fullName>1230</fullName>
            </value>
            <value>
                <fullName>1241</fullName>
            </value>
            <value>
                <fullName>1274</fullName>
            </value>
            <value>
                <fullName>1300</fullName>
            </value>
            <value>
                <fullName>1330</fullName>
            </value>
            <value>
                <fullName>1340</fullName>
            </value>
            <value>
                <fullName>1400</fullName>
            </value>
            <value>
                <fullName>1427</fullName>
            </value>
            <value>
                <fullName>1445</fullName>
            </value>
            <value>
                <fullName>1450</fullName>
            </value>
            <value>
                <fullName>1478</fullName>
            </value>
            <value>
                <fullName>1490</fullName>
            </value>
            <value>
                <fullName>1514</fullName>
            </value>
            <value>
                <fullName>1518</fullName>
            </value>
            <value>
                <fullName>1520</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/GlassComposition.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1805</fullName>
    </customValue>
    <customValue>
        <fullName>1807</fullName>
    </customValue>
    <customValue>
        <fullName>1811</fullName>
    </customValue>
    <customValue>
        <fullName>1815</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2317</fullName>
    </customValue>
    <customValue>
        <fullName>2318</fullName>
    </customValue>
    <customValue>
        <fullName>2319</fullName>
    </customValue>
    <customValue>
        <fullName>2320 (GG3)</fullName>
    </customValue>
    <customValue>
        <fullName>2521 (GG3+)</fullName>
    </customValue>
    <customValue>
        <fullName>3318</fullName>
    </customValue>
    <customValue>
        <fullName>4318</fullName>
    </customValue>
    <customValue>
        <fullName>5318 (GG4)</fullName>
    </customValue>
    <customValue>
        <fullName>7321 (GG5)</fullName>
    </customValue>
    <customValue>
        <fullName>7418</fullName>
    </customValue>
    <customValue>
        <fullName>7431 (GG6)</fullName>
    </customValue>
    <customValue>
        <fullName>7541 (Victus)</fullName>
    </customValue>
    <customValue>
        <fullName>7518</fullName>
    </customValue>
    <customValue>
        <fullName>9218</fullName>
    </customValue>
    <customValue>
        <fullName>9318</fullName>
    </customValue>
    <customValue>
        <fullName>9319</fullName>
    </customValue>
    <customValue>
        <fullName>9724</fullName>
    </customValue>
    <customValue>
        <fullName>9726</fullName>
    </customValue>
    <customValue>
        <fullName>Maxwell GC</fullName>
    </customValue>
    <customValue>
        <fullName>MGC</fullName>
    </customValue>
    <customValue>
        <fullName>MM-B</fullName>
    </customValue>
    <customValue>
        <fullName>MX-B</fullName>
    </customValue>
    <customValue>
        <fullName>PHY2</fullName>
    </customValue>
    <customValue>
        <fullName>PHY2.1</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Glass Composition</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/StandardProductDataToProductUtilityTest.cls
///*** Added for Gorilla Glass Implementation ***///
///*** Corning - 5/2/2017 ***///

@isTest
private class StandardProductDataToProductUtilityTest {
    static TestUtilities tUtils = new TestUtilities();
    private static string acctRT;

    static {
        acctRT = tUtils.getRecordTypeId('Account', 'GG Account');
    }

    static testMethod void checkContainsPricingTest() {
        // tUtils.createTestMatrixRecord();
        
        Pricebook2 standardPricebook = new Pricebook2(Id=Test.getStandardPricebookId(),IsActive = true);
        update standardPricebook;
        
        Pricebook2 customPB = new Pricebook2(Name='GG Price Book', isActive=true);
        insert customPB;
        
        Account a1 = tUtils.createTestAccount(acctRT);
        a1.containsPricing__c = true;
        insert a1;
        
         //create product matrix record
        StandardProductInventoryMatrix__c m = new StandardProductInventoryMatrix__c();
        m.name = 'x';
        m.glassComposition__c = '2320 (GG3)';// 11-16-20 jd (change to '2320 (GG3)'')
        m.thickness__c = '0.40';
        m.width__c = '1520';
        m.customwidth__c = 1520;
        m.length__c = '1460';
        m.customlength__c = 1460;
        m.productLine__c = 'Raw Glass';
        m.isActive__c = TRUE;
        m.estimatedCrateSheetCount__c = 450;
        m.maximumCrateDimensions__c = '1690 x 1910 x 900';
        m.moq__c = 450;
        m.moqUnits__c = 'Each';
        insert m;
        
        //test.startTest();
            StandardProductInventoryLoader__c l = new StandardProductInventoryLoader__c();
            l.glassComposition__c = '2320 (GG3)'; // 11-16-20 jd (change to '2320 (GG3)'')
            l.thickness__c = '0.40';
            l.pricePerSqFt__c = 16.33;
            l.account__c = a1.id;
            l.productLine__c = 'Raw Glass';
            insert l;
        //test.stopTest();
    }

}