force-app/main/default/objects/StandardProductInventoryMatrix__c/StandardProductInventoryMatrix__c.object-meta.xml
<CustomObject>
    <label>Standard Product Inventory Matrix</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Product Inventory Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/customLength__c.field-meta.xml
<CustomField>
    <fullName>customLength__c</fullName>
    <label>Length</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/customWidth__c.field-meta.xml
<CustomField>
    <fullName>customWidth__c</fullName>
    <label>Width</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/externalId__c.field-meta.xml
<CustomField>
    <fullName>externalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>120</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/glassComposition__c.field-meta.xml
<CustomField>
    <fullName>glassComposition__c</fullName>
    <label>Glass Composition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GlassComposition</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/productLine__c.field-meta.xml
<CustomField>
    <fullName>productLine__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Raw Glass</fullName>
                <default>true</default>
                <label>Raw Glass</label>
            </value>
            <value>
                <fullName>Concore</fullName>
                <isActive>false</isActive>
                <label>Concore</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StandardProductInventoryMatrix__c/fields/thickness__c.field-meta.xml
<CustomField>
    <fullName>thickness__c</fullName>
    <label>Thickness</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>.95</fullName>
            </value>
            <value>
                <fullName>0.25</fullName>
            </value>
            <value>
                <fullName>0.33</fullName>
            </value>
            <value>
                <fullName>0.40</fullName>
            </value>
            <value>
                <fullName>0.405</fullName>
            </value>
            <value>
                <fullName>0.50</fullName>
            </value>
            <value>
                <fullName>0.505</fullName>
            </value>
            <value>
                <fullName>0.55</fullName>
            </value>
            <value>
                <fullName>0.555</fullName>
            </value>
            <value>
                <fullName>0.60</fullName>
            </value>
            <value>
                <fullName>0.605</fullName>
            </value>
            <value>
                <fullName>0.65</fullName>
            </value>
            <value>
                <fullName>0.70</fullName>
            </value>
            <value>
                <fullName>0.80</fullName>
            </value>
            <value>
                <fullName>0.81</fullName>
            </value>
            <value>
                <fullName>0.89</fullName>
            </value>
            <value>
                <fullName>0.90</fullName>
            </value>
            <value>
                <fullName>0.95</fullName>
            </value>
            <value>
                <fullName>1.00</fullName>
            </value>
            <value>
                <fullName>1.05</fullName>
            </value>
            <value>
                <fullName>1.10</fullName>
            </value>
            <value>
                <fullName>1.20</fullName>
            </value>
            <value>
                <fullName>1.30</fullName>
            </value>
            <value>
                <fullName>1.35</fullName>
            </value>
            <value>
                <fullName>1.40</fullName>
            </value>
            <value>
                <fullName>1.50</fullName>
            </value>
            <value>
                <fullName>1.60</fullName>
            </value>
            <value>
                <fullName>1.62</fullName>
            </value>
            <value>
                <fullName>1.70</fullName>
            </value>
            <value>
                <fullName>1.76</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/GlassComposition.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1805</fullName>
    </customValue>
    <customValue>
        <fullName>1807</fullName>
    </customValue>
    <customValue>
        <fullName>1811</fullName>
    </customValue>
    <customValue>
        <fullName>1815</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2317</fullName>
    </customValue>
    <customValue>
        <fullName>2318</fullName>
    </customValue>
    <customValue>
        <fullName>2319</fullName>
    </customValue>
    <customValue>
        <fullName>2320 (GG3)</fullName>
    </customValue>
    <customValue>
        <fullName>2521 (GG3+)</fullName>
    </customValue>
    <customValue>
        <fullName>3318</fullName>
    </customValue>
    <customValue>
        <fullName>4318</fullName>
    </customValue>
    <customValue>
        <fullName>5318 (GG4)</fullName>
    </customValue>
    <customValue>
        <fullName>7321 (GG5)</fullName>
    </customValue>
    <customValue>
        <fullName>7418</fullName>
    </customValue>
    <customValue>
        <fullName>7431 (GG6)</fullName>
    </customValue>
    <customValue>
        <fullName>7541 (Victus)</fullName>
    </customValue>
    <customValue>
        <fullName>7518</fullName>
    </customValue>
    <customValue>
        <fullName>9218</fullName>
    </customValue>
    <customValue>
        <fullName>9318</fullName>
    </customValue>
    <customValue>
        <fullName>9319</fullName>
    </customValue>
    <customValue>
        <fullName>9724</fullName>
    </customValue>
    <customValue>
        <fullName>9726</fullName>
    </customValue>
    <customValue>
        <fullName>Maxwell GC</fullName>
    </customValue>
    <customValue>
        <fullName>MGC</fullName>
    </customValue>
    <customValue>
        <fullName>MM-B</fullName>
    </customValue>
    <customValue>
        <fullName>MX-B</fullName>
    </customValue>
    <customValue>
        <fullName>PHY2</fullName>
    </customValue>
    <customValue>
        <fullName>PHY2.1</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Glass Composition</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MatrixTriggerHelper.cls
public without sharing class MatrixTriggerHelper {

    // make sure duplicate matrix records so not get created
    public static void setExternalId(List<StandardProductInventoryMatrix__c> mList) {
        
        Set<String> matrixNameSet = new Set<String>(); 
        List<StandardProductInventoryMatrix__c> currentList = [Select Name from StandardProductInventoryMatrix__c];
        
        for (StandardProductInventoryMatrix__c c: currentList) {
            matrixNameSet.add(c.Name);
        }

        for (StandardProductInventoryMatrix__c m: mList) {
            m.externalId__c = m.glassComposition__c+'; '+m.thickness__c+'mm; '+m.customwidth__c+'mm x '+m.customlength__c+'mm; '+m.productLine__c;            
            
            if (!matrixNameSet.contains(m.externalId__c)) {
                matrixNameSet.add(m.externalId__c);
            } else {
                m.addError('Matrix entry already exists.');
            }                       
        }

    }

    // make sure Glass Composition, Thickness, Width, Length are immutable
    public static void checkForChanges(List<StandardProductInventoryMatrix__c> mList, Map<Id, StandardProductInventoryMatrix__c> oldMap) {

         for (StandardProductInventoryMatrix__c m: mList) {
             
            if (((oldMap.get(m.ID).customWidth__c != m.customWidth__c) && oldMap.get(m.ID).customWidth__c != Null) ||
             ((oldMap.get(m.ID).customLength__c != m.customLength__c) && oldMap.get(m.ID).customLength__c != Null) ||
             (oldMap.get(m.ID).thickness__c != m.thickness__c) ||
             (oldMap.get(m.ID).glassComposition__c != m.glassComposition__c)) {          
                m.addError('Glass Composition, Thickness, Width and Length cannot be changed.');
            }                       
        }       
        
    }    
    
    // make sure the Product2 active status is set
    public static void productActivation(List<StandardProductInventoryMatrix__c> mList, Map<Id, StandardProductInventoryMatrix__c> oldMap) {
        
        Map<String, Boolean> changeMap = new Map<String, Boolean>();
        List<String> productNameList = new List<String>();
        List<Product2> prodUpdateList = new List<Product2>();
        
        for (StandardProductInventoryMatrix__c m: mList) {
             
            if (oldMap.get(m.ID).isActive__c != m.isActive__c) {
                changeMap.put(m.name,m.isActive__c);
                productNameList.add(m.name);
            }                       
        }   
        
        List<Product2> prod2List = [SELECT id, name, isActive FROM Product2 WHERE name IN :productNameList];
        
        for (Product2 p: prod2List) {
        
            if( changeMap.ContainsKey(p.name) ){
                p.IsActive = changeMap.get(p.name);
                prodUpdateList.add(p);
            }
                                     
        }
        
        if (prodUpdateList.size() > 0) {
            update prodUpdateList;
        }
        
    }    
    
}