force-app/main/default/objects/rfiConfiguration__c/rfiConfiguration__c.object-meta.xml
<CustomObject>
    <label>RFI Configuration</label>
    <nameField>
        <label>RFI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFI Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification__c/Specification__c.object-meta.xml
<CustomObject>
    <description>Specification/MTO</description>
    <label>Specification</label>
    <nameField>
        <label>Spec Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specification__c/fields/accountAEId__c.field-meta.xml
<CustomField>
    <fullName>accountAEId__c</fullName>
    <formula>opportunity__r.Account.ae__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account AE Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/dsLocation__c.field-meta.xml
<CustomField>
    <fullName>dsLocation__c</fullName>
    <label>Secondary CM Selected Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Manufacturing_Facility</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/dsReminderCompleted__c.field-meta.xml
<CustomField>
    <fullName>dsReminderCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/dsStatus__c.field-meta.xml
<CustomField>
    <fullName>dsStatus__c</fullName>
    <label>Secondary CM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Manufacturer Assignment</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>CM Cost Assessment</fullName>
            </value>
            <value>
                <fullName>Cost Assessment Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Omitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/dsStatusChangeDate__c.field-meta.xml
<CustomField>
    <fullName>dsStatusChangeDate__c</fullName>
    <label>Status Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/Innovation_Type__c.field-meta.xml
<CustomField>
    <fullName>Innovation_Type__c</fullName>
    <label>Innovation Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AntiGlare (AG)</fullName>
            </value>
            <value>
                <fullName>AntiMicrobial</fullName>
            </value>
            <value>
                <fullName>ArtEng</fullName>
            </value>
            <value>
                <fullName>DAR2.0</fullName>
            </value>
            <value>
                <fullName>DX</fullName>
            </value>
            <value>
                <fullName>DXPlus</fullName>
                <label>DX+</label>
            </value>
            <value>
                <fullName>DXC</fullName>
            </value>
            <value>
                <fullName>EZ/AR</fullName>
            </value>
            <value>
                <fullName>AR – Camera Hole</fullName>
            </value>
            <value>
                <fullName>FPS</fullName>
            </value>
            <value>
                <fullName>Glass Back</fullName>
            </value>
            <value>
                <fullName>Glass Ceramics</fullName>
            </value>
            <value>
                <fullName>IT Size 3D</fullName>
            </value>
            <value>
                <fullName>Large Cover Glass</fullName>
            </value>
            <value>
                <fullName>NextGenSRPlus</fullName>
                <label>Next Gen SR+</label>
            </value>
            <value>
                <fullName>non-CE AR</fullName>
            </value>
            <value>
                <fullName>Corning Bendable Glass</fullName>
            </value>
            <value>
                <fullName>Screen Protector</fullName>
            </value>
            <value>
                <fullName>SRPlus</fullName>
                <label>SR+</label>
            </value>
            <value>
                <fullName>Vibrant</fullName>
            </value>
            <value>
                <fullName>Phire 2.0</fullName>
                <isActive>false</isActive>
                <label>Phire 2.0</label>
            </value>
            <value>
                <fullName>Phire 3.0</fullName>
                <isActive>false</isActive>
                <label>Phire 3.0</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <formula>IF( ISPICKVAL(status__c, &quot;Pricing Approved&quot;) , True, 
IF( ISPICKVAL(status__c, &quot;Declined&quot;) , True, False))</formula>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/isOmega__c.field-meta.xml
<CustomField>
    <fullName>isOmega__c</fullName>
    <formula>IF(text( opportunity__r.marketSegment__c ) = &apos;Screen Protector - Amplify&apos;, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Omega</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/location__c.field-meta.xml
<CustomField>
    <fullName>location__c</fullName>
    <description>Manufacturing facility/location</description>
    <label>Primary CM Selected Locations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Manufacturing_Facility</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/mtoNotificationPath__c.field-meta.xml
<CustomField>
    <fullName>mtoNotificationPath__c</fullName>
    <formula>CASE(  glassComposition__c  , 
&quot;1805&quot;, &quot;Path 1&quot;,
&quot;1807&quot;, &quot;Path 1&quot;,
&quot;2320&quot;, &quot;Path 1&quot;, 
&quot;2521&quot;, &quot;Path 1&quot;,  
&quot;4318&quot;, &quot;Path 1&quot;, 
&quot;5318&quot;, &quot;Path 1&quot;, 
&quot;7321&quot;, &quot;Path 1&quot;, 
&quot;7418&quot;, &quot;Path 1&quot;, 
&quot;7431&quot;, &quot;Path 1&quot;,
&quot;7518&quot;, &quot;Path 2&quot;, 
&quot;9318&quot;, &quot;Path 2&quot;,  
&quot;9319&quot;, &quot;Path 2&quot;,
&quot;9726&quot;, &quot;Path 2&quot;,
&quot;Path 1&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MTO Notification Path</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/opportunityName__c.field-meta.xml
<CustomField>
    <fullName>opportunityName__c</fullName>
    <formula>opportunity__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/productLine__c.field-meta.xml
<CustomField>
    <fullName>productLine__c</fullName>
    <formula>IF( CONTAINS(RecordType.DeveloperName, &quot;Raw&quot;), &quot;Raw Glass&quot;,
IF( CONTAINS(RecordType.DeveloperName, &quot;Parts&quot;), &quot;Parts&quot;, &quot;Concore&quot;))</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/reminderCompleted__c.field-meta.xml
<CustomField>
    <fullName>reminderCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reminder Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Specification__c/fields/rfiConfiguration__c.field-meta.xml
<CustomField>
    <fullName>rfiConfiguration__c</fullName>
    <label>RFI Configuration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acer standard IT full feature spec. (ex. Origins)</fullName>
            </value>
            <value>
                <fullName>Asus standard HH 2.5D full feature spec. (ex. Zenfone 5)</fullName>
            </value>
            <value>
                <fullName>Corning standard 2.5D HH full feature spec.</fullName>
            </value>
            <value>
                <fullName>Corning standard 2D HH full feature spec.</fullName>
            </value>
            <value>
                <fullName>Corning standard 2D IT blank part spec.</fullName>
            </value>
            <value>
                <fullName>Corning standard 2D IT full feature spec.</fullName>
            </value>
            <value>
                <fullName>Dell A11 AR/ETC spec. (IT AR/ETC ; ex. Augusta)</fullName>
            </value>
            <value>
                <fullName>Garmin standard full feature spec (wearable)</fullName>
            </value>
            <value>
                <fullName>HP standard full feature spec. (AG &amp; non-AG version ; ex. Bumblebee)</fullName>
            </value>
            <value>
                <fullName>HP standard IT AG spec. (IT AG ; ex. Damon)</fullName>
            </value>
            <value>
                <fullName>Lenovo AR/ETC spec. (IT AR/ETC ; ex. Storm 3)</fullName>
            </value>
            <value>
                <fullName>MSFT standard IT Blank spec. (ex. IM37/IM40)</fullName>
            </value>
            <value>
                <fullName>OPPO standard HH 2.5D full feature spec. (ex. DD005)</fullName>
            </value>
            <value>
                <fullName>SOMC standard HH 2.5D full feature spec. (ex. PF13)</fullName>
            </value>
            <value>
                <fullName>SOMC standard HH 3D Vibrant full feature spec. (ex. Akashuki)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Innovation Assessment</fullName>
            </value>
            <value>
                <fullName>Missing Information Assessment</fullName>
            </value>
            <value>
                <fullName>Capable Assessment</fullName>
            </value>
            <value>
                <fullName>Standard Assessment</fullName>
            </value>
            <value>
                <fullName>Manufacturer Assignment</fullName>
            </value>
            <value>
                <fullName>Risk Assessment</fullName>
            </value>
            <value>
                <fullName>CM Cost Assessment</fullName>
            </value>
            <value>
                <fullName>Supply, Allocation, and Inventory Review</fullName>
            </value>
            <value>
                <fullName>Product Engineering Input</fullName>
            </value>
            <value>
                <fullName>Plant Engineering Input</fullName>
            </value>
            <value>
                <fullName>Supply Chain Input</fullName>
            </value>
            <value>
                <fullName>Pricing Assignment</fullName>
            </value>
            <value>
                <fullName>Business Case Finalization</fullName>
            </value>
            <value>
                <fullName>Finance Review</fullName>
            </value>
            <value>
                <fullName>Commercial/Ops Review</fullName>
            </value>
            <value>
                <fullName>Pricing Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Business Case Assessment</fullName>
                <isActive>false</isActive>
                <label>Business Case Assessment</label>
            </value>
            <value>
                <fullName>Supply, Allocation, &amp; Inventory Assessment</fullName>
                <isActive>false</isActive>
                <label>Supply, Allocation, &amp; Inventory Assessment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Specification__c/fields/statusChangeDate__c.field-meta.xml
<CustomField>
    <fullName>statusChangeDate__c</fullName>
    <label>Status Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Manufacturing_Facility.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Biel</fullName>
    </customValue>
    <customValue>
        <fullName>BOE</fullName>
    </customValue>
    <customValue>
        <fullName>BYD-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>CGK</fullName>
    </customValue>
    <customValue>
        <fullName>CPM</fullName>
    </customValue>
    <customValue>
        <fullName>Crystal</fullName>
    </customValue>
    <customValue>
        <fullName>DSBJ</fullName>
    </customValue>
    <customValue>
        <fullName>Fuzhou</fullName>
    </customValue>
    <customValue>
        <fullName>GIS</fullName>
    </customValue>
    <customValue>
        <fullName>GO</fullName>
    </customValue>
    <customValue>
        <fullName>GTOC</fullName>
    </customValue>
    <customValue>
        <fullName>HDC</fullName>
    </customValue>
    <customValue>
        <fullName>HH-LowR</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong Warehouse</fullName>
    </customValue>
    <customValue>
        <fullName>Hony</fullName>
    </customValue>
    <customValue>
        <fullName>HTF</fullName>
    </customValue>
    <customValue>
        <fullName>Huaqing</fullName>
    </customValue>
    <customValue>
        <fullName>J3D</fullName>
    </customValue>
    <customValue>
        <fullName>Jiangmen</fullName>
    </customValue>
    <customValue>
        <fullName>JNTC-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>Kaymao</fullName>
    </customValue>
    <customValue>
        <fullName>KOTL-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>LCE-LR</fullName>
    </customValue>
    <customValue>
        <fullName>LENS-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>LOT</fullName>
    </customValue>
    <customValue>
        <fullName>MFD-TQ</fullName>
    </customValue>
    <customValue>
        <fullName>NGS</fullName>
    </customValue>
    <customValue>
        <fullName>NVD</fullName>
    </customValue>
    <customValue>
        <fullName>Opton</fullName>
    </customValue>
    <customValue>
        <fullName>RKL</fullName>
    </customValue>
    <description>Manufacturing facility selected in the spec</description>
    <masterLabel>Manufacturing Facility</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/SpecificationReminderBatch.cls
/*******************************************************************************************************
Class Name       : 
Purpose          : 
Author           : Adam Nicholson
Revision History : 
 * *****************************************************************************************************/
global class SpecificationReminderBatch implements Database.Batchable<sObject> , Database.Stateful{
    
    global integer failedRecCount = 0;
    global integer totalRecCount = 0;
        global integer totalRecCount2 = 0;
    global List<Specification__c> totalProcessedSpecs = new List<Specification__c>();
    
    global Database.QueryLocator start(Database.BatchableContext BC) {        
        return Database.getQueryLocator( [SELECT id, createdbyid, opportunityName__c, rfiConfiguration__c, recordtypeid, innovation_type__c, productLine__c, mtoNotificationPath__c, accountAEId__c, isOmega__c, location__c, reminderCompleted__c, statusChangeDate__c, status__c, dsLocation__c, dsReminderCompleted__c, dsStatusChangeDate__c, dsStatus__c FROM Specification__c 
                                          WHERE isClosed__c = False AND ( (statusChangeDate__c != null AND reminderCompleted__c = False) OR (dsStatusChangeDate__c != null AND dsReminderCompleted__c = False) )] );
    }

    global void execute(Database.BatchableContext BC, List<Specification__c> scope) {
        try{
            if(scope!=null){
                totalReccount = totalReccount + scope.size();
                system.debug('TRC Original: ' + totalReccount);
            } 
            
            // call chatter helper class
            List<Specification__c> specListForUpdate = ChatterHelper.specificationReminder(Scope);
            system.debug('TRC: ' + totalReccount);
            
            //totalProcessedSpecs.addAll(specListForUpdate);
            //system.debug('TPS: ' + totalProcessedSpecs.size()); 
            
            List<Database.SaveResult> results = new List<Database.SaveResult>();                        
            system.debug('RES: ' + results.size());
            
            results = Database.update(specListForUpdate, false);
            
            // errors count
            for(database.SaveResult ds : results){                
                if (!ds.isSuccess()){
                    failedRecCount++;
                }  
            }   
        }
        Catch(Exception e){
            system.debug('Exception In Execute ' + e);
        }
    }    
    
    global void finish(Database.BatchableContext BC) {
        System.debug('Number of Records Processed -  ' + totalReccount );
        System.debug('Number of Records Failed  - ' + failedRecCount );
        System.debug('Number of Records Passed  - ' + (totalRecCount-failedRecCount) );
    }
    
}