force-app/main/default/objects/SupplyChain__c/SupplyChain__c.object-meta.xml
<CustomObject>
    <label>Supply Chain</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Chains</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SupplyChain__c/fields/application__c.field-meta.xml
<CustomField>
    <fullName>application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>application</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SupplyChain__c/fields/decisionMaker__c.field-meta.xml
<CustomField>
    <fullName>decisionMaker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Decision Maker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supply Chains (Decision Maker)</relationshipLabel>
    <relationshipName>Supply_Chains3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SupplyChain__c/fields/finisher__c.field-meta.xml
<CustomField>
    <fullName>finisher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finisher</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account does not contain pricing</errorMessage>
        <filterItems>
            <field>Account.containsPricing__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supply Chains (Finisher)</relationshipLabel>
    <relationshipName>Supply_Chains2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SupplyChain__c/fields/lcm__c.field-meta.xml
<CustomField>
    <fullName>lcm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LCM</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supply Chains (LCM)</relationshipLabel>
    <relationshipName>Supply_Chains4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SupplyChain__c/fields/odm__c.field-meta.xml
<CustomField>
    <fullName>odm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ODM</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supply Chains (ODM)</relationshipLabel>
    <relationshipName>Supply_Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SupplyChain__c/fields/opportunity__c.field-meta.xml
<CustomField>
    <fullName>opportunity__c</fullName>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>GG Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Supply Chains</relationshipLabel>
    <relationshipName>Supply_Chains</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SupplyChain__c/fields/panelMaker__c.field-meta.xml
<CustomField>
    <fullName>panelMaker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel Maker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supply Chains (Panel Maker)</relationshipLabel>
    <relationshipName>Supply_Chains5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SupplyChain__c/fields/tpm__c.field-meta.xml
<CustomField>
    <fullName>tpm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TPM</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supply Chains (TPM)</relationshipLabel>
    <relationshipName>Supply_Chains1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/application.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Back Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Camera Lens Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Front Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Home Button</fullName>
    </customValue>
    <customValue>
        <fullName>LCM</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Scanner Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Screen Protector</fullName>
    </customValue>
    <customValue>
        <fullName>Touch Keypad Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Touch Sensor</fullName>
    </customValue>
    <masterLabel>Application</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/SupplyChainTest.cls
///*** Added for Gorilla Glass Implementation ***///
///*** AN - 7/8/2018 ***///
///*** Test Class for supply chain ***///

@isTest
public class SupplyChainTest {
    static TestUtilities tUtils = new TestUtilities();
    private static string acctRT;
    private static string oppRT;
    
    static {
        acctRT = tUtils.getRecordTypeId('Account', 'GG Account');
        oppRT = tUtils.getRecordTypeId('Opportunity', 'GG Program');
    }
    
    static testMethod void TestSupplyChain() {
        tUtils.SetTriggersOnForTesting();
        Account a = tUtils.addTestAccount(acctRT);
        a.containsPricing__c = TRUE;
        update a;
        
        Opportunity o = tUtils.addTestOppt(a.Id,oppRT);
        SupplyChain__c sc = new SupplyChain__c();
        
        sc.opportunity__c = o.id;
        sc.application__c = 'Other';
        sc.decisionMaker__c = a.id;
        sc.odm__c = a.id;
        sc.tpm__c = a.id;
        sc.odm__c = a.id;
        sc.finisher__c = a.id;
        sc.panelMaker__c = a.id;
        sc.lcm__c = a.id; 
        
        insert sc;

    }
}